# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@babel/code-frame@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/code-frame/-/code-frame-7.29.7.tgz";
    hash = "sha512-Aup7aUOfpbAUg2ROOJN6Iw5f9DMBlzu0mIkm/malLQFN/YQgO48wCj0Kxa3sEHJvPVFg7siR+qRInwXd2qhQKw==";
    name = "code-frame-7.29.7.tgz";
  };
  "@babel/helper-validator-identifier@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/helper-validator-identifier/-/helper-validator-identifier-7.29.7.tgz";
    hash = "sha512-qehxGkRj55h/ff8EMaJ+cYhyaKlHIxqYDn682wQD7RNp9UujOQsHog2uS0r2vzr4pW+sXf90NeeayjcNaX3fFg==";
    name = "helper-validator-identifier-7.29.7.tgz";
  };
  "@babel/runtime@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/runtime/-/runtime-7.29.7.tgz";
    hash = "sha512-Nq8OhGWiZIZGV6hLHoyAKLLcJihP/xFeBMGJoUrxTX2psI8dCifzLhZISFb+VWS3wFMRDmCGw5R+dOySCqPLhw==";
    name = "runtime-7.29.7.tgz";
  };
  "@blazediff/core@1.10.0" = fetchurl {
    url = "https://npm.flatt.tech/@blazediff/core/-/core-1.10.0.tgz";
    hash = "sha512-AOQff0zgR7cGsZL+4E7hVkmujoPUpm0J9xzWGWZj5wCjd3gmxESXAPfKyuzs93VdpQNFhHlBhfOjrcZ+XTERtQ==";
    name = "core-1.10.0.tgz";
  };
  "@jridgewell/resolve-uri@3.1.2" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
    hash = "sha512-bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
    name = "resolve-uri-3.1.2.tgz";
  };
  "@jridgewell/sourcemap-codec@1.6.0" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.6.0.tgz";
    hash = "sha512-T7jf+5zgsZHwNJ4lvQ7/aezbyk0nNX+zJVWpmHA7VYsEx7a7qr5Rg5IbtJFqkgze5Y2sruq1RUY8Q837Od7iFw==";
    name = "sourcemap-codec-1.6.0.tgz";
  };
  "@jridgewell/trace-mapping@0.3.31" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
    hash = "sha512-zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
    name = "trace-mapping-0.3.31.tgz";
  };
  "@oxc-project/runtime@0.153.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/runtime/-/runtime-0.153.0.tgz";
    hash = "sha512-rXJvtlsVG4xJNq64hiaUTIatE7jbBgpa6l4QgmEa2jLgT3ULH9scUBkpsC9N1DfmqixLEyT6DuK6OSXozziIlw==";
    name = "runtime-0.153.0.tgz";
  };
  "@oxc-project/types@0.149.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/types/-/types-0.149.0.tgz";
    hash = "sha512-Efcc+iF0j3Bf67YjEqIqWXbX5XddXoK/Mw4K1/JuXwRCZ8N16VR7iT23nlCc9XrveFVh/E5Rqs2StT0V8v9LdA==";
    name = "types-0.149.0.tgz";
  };
  "@oxc-project/types@0.153.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/types/-/types-0.153.0.tgz";
    hash = "sha512-jSNrRIyvPVLL5E1z/tS5zLAprosGz/FuI1PWwEOz59j3E4TTTzSpqKb/RDGqJhhW0QHYISGXxq582wGx6T11Tw==";
    name = "types-0.153.0.tgz";
  };
  "@oxfmt/binding-android-arm-eabi@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-android-arm-eabi/-/binding-android-arm-eabi-0.72.0.tgz";
    hash = "sha512-u4U1uaDOVBuorGNC/07NLm48nECHOiJJka002YGML16Md2DRvf38RGBt01lH60EOGvNlFVmbLoksQedNBoZHKw==";
    name = "binding-android-arm-eabi-0.72.0.tgz";
  };
  "@oxfmt/binding-android-arm64@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-android-arm64/-/binding-android-arm64-0.72.0.tgz";
    hash = "sha512-GCnM+Ae2mWOKC+92y3FOb6eZJeVnBAVz82e3lITUUg+kxukYKzBNAvJ/hhHIfa2A0md55SYYhdWPddSSy3KPVA==";
    name = "binding-android-arm64-0.72.0.tgz";
  };
  "@oxfmt/binding-darwin-arm64@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-darwin-arm64/-/binding-darwin-arm64-0.72.0.tgz";
    hash = "sha512-LjQ8tlevdtwraFlWC6AnQ1Forzde0clRmnsP3QmK+ydSElDt/J+5Jc+m+//Ly1G97aP7WCNUw110QMIUw2K7xA==";
    name = "binding-darwin-arm64-0.72.0.tgz";
  };
  "@oxfmt/binding-darwin-x64@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-darwin-x64/-/binding-darwin-x64-0.72.0.tgz";
    hash = "sha512-+ZbcxhB1C34RQR5IldSyY6Z/yalJIxHXhP36PGE4sEq0f/lgL5jCLmOKoDeVm8dqd9gFGDsd1bNWHSGCAwdSkw==";
    name = "binding-darwin-x64-0.72.0.tgz";
  };
  "@oxfmt/binding-freebsd-x64@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-freebsd-x64/-/binding-freebsd-x64-0.72.0.tgz";
    hash = "sha512-yGPhA8sePEBFV9iGcprhyOk3Bz3fZshswMH3DpYIPZFLT1DG5LjiZ0j6AJQpSueaL6bUK0av1K+5+fe+ldy5EQ==";
    name = "binding-freebsd-x64-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-arm-gnueabihf@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-0.72.0.tgz";
    hash = "sha512-/g5axuqFMcAtoQrFLR5EJEMDjR5Ea4GuzpdDmMpPWAgrF1DmL4kD1NPNVlpXEOxpFJnD6lPvLKYj1lzdlrfifA==";
    name = "binding-linux-arm-gnueabihf-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-arm-musleabihf@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-0.72.0.tgz";
    hash = "sha512-InVitdHbS09PM+w+WinIiyX37rC9R3L7lUP9mKy9uKTEDSUFaLjWsLoreRIxKivnv7Ndqc6Trvi+K+b6ZzhiJg==";
    name = "binding-linux-arm-musleabihf-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-arm64-gnu@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.72.0.tgz";
    hash = "sha512-WKjlyRAxpPjXoqeuwFBim5LscgvY+RNEiZ971C9JlRQZONhJTsXDki/oHFYQE+fzzRpzXh3owZvOdT3kNL2g+g==";
    name = "binding-linux-arm64-gnu-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-arm64-musl@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.72.0.tgz";
    hash = "sha512-poafnbsPpJhR+5Mbwpf8CscugTyiRAzjTOxRVn8ra3X2jnURs2xL5Du2xl5g2iW85lICMglpmLf8jDjZEbNgzQ==";
    name = "binding-linux-arm64-musl-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-ppc64-gnu@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-0.72.0.tgz";
    hash = "sha512-zNUi0gKRsO7S3IfPzsTbnm88OedPuX32hmZFWZRWHvWJlAoZRwVbeO6Nb3hng4vDgL7qUKp4TGqzPz1mhsycYg==";
    name = "binding-linux-ppc64-gnu-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-riscv64-gnu@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-0.72.0.tgz";
    hash = "sha512-qTY7z/iyF/rWI2HWwWMevXqZW5PZUOofUy2afK7v6rseXnpld3yjgyIk6pCux3DqWQ0lB+f5atvLJNBwzLvFsw==";
    name = "binding-linux-riscv64-gnu-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-riscv64-musl@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-0.72.0.tgz";
    hash = "sha512-w18qfo8vEMD6EKEHtzTvjc6jH8yCyXIT1Bn7PFWJd0PpZyzH/VQDx4xvjCh0LGz6GRzqiezbisTdG9AoXtpkZQ==";
    name = "binding-linux-riscv64-musl-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-s390x-gnu@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-0.72.0.tgz";
    hash = "sha512-grW8HwEir+vK7fCcq1ZgL3NHQCfZ1PidiERE9Hbf+24xGys+DoDaoqTht4ccfn0PcBwbViLkwkda/KNpJu2KRQ==";
    name = "binding-linux-s390x-gnu-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-x64-gnu@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.72.0.tgz";
    hash = "sha512-wQJRQfWBRIn88Pkr449EUViwRayrYUScg7ty+Ihiem21mQ9BUA6S9e/4RAgyNk9lMag0KBouyKskjq61rOC0WQ==";
    name = "binding-linux-x64-gnu-0.72.0.tgz";
  };
  "@oxfmt/binding-linux-x64-musl@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-x64-musl/-/binding-linux-x64-musl-0.72.0.tgz";
    hash = "sha512-T1B0uQzafxuGPjjaPrZJ497nxoi1BiI65JfsYc56nNpmev3msfb/iaTmH2kQuNFqa8PKxpMlf3GhWrWBvBPORQ==";
    name = "binding-linux-x64-musl-0.72.0.tgz";
  };
  "@oxfmt/binding-openharmony-arm64@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-openharmony-arm64/-/binding-openharmony-arm64-0.72.0.tgz";
    hash = "sha512-OKxxgTurl7+hypVplO8QRAbbQlwEs0j1Y6FZv+ZN2qNbdxQk2muMlzuJNBGTCWwxQ0rkkOD1uK/DW1fvzoUSJA==";
    name = "binding-openharmony-arm64-0.72.0.tgz";
  };
  "@oxfmt/binding-win32-arm64-msvc@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-0.72.0.tgz";
    hash = "sha512-L78TKzURqvjuZOCo88ixMbPXf/RP7u31Y0cmjJ/KEmrHmfYhmhEvsDaTYPiyTRne64jUgCbADfY0YeoQk4/Xyw==";
    name = "binding-win32-arm64-msvc-0.72.0.tgz";
  };
  "@oxfmt/binding-win32-ia32-msvc@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-0.72.0.tgz";
    hash = "sha512-gQtFW+Ii8BWgtJTAD17TY/WsdNS5gUfAPov8iI1jeq4r9lRRYImmxPL08UU00/RLaCfBJwh2UgINnDY0iOiZ+A==";
    name = "binding-win32-ia32-msvc-0.72.0.tgz";
  };
  "@oxfmt/binding-win32-x64-msvc@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-x64-msvc/-/binding-win32-x64-msvc-0.72.0.tgz";
    hash = "sha512-uhooIN+DCzWX5uH7mQkSVCsODqsGluGJ4n3ch4+mITtWKpESMDjUJUSDBAVFuYQDwqY2McPDKdKJbM0oZVW/Qw==";
    name = "binding-win32-x64-msvc-0.72.0.tgz";
  };
  "@oxlint-tsgolint/darwin-arm64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/darwin-arm64/-/darwin-arm64-7.0.2003.tgz";
    hash = "sha512-TgV33rXr6ueXBwvc+0nssUkTBSXHJxv77I8p4RCjDjCnvexHtmoPiudVRDfj3S3puMDdeQdHW6jdUgUPy3nr/w==";
    name = "darwin-arm64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/darwin-x64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/darwin-x64/-/darwin-x64-7.0.2003.tgz";
    hash = "sha512-hY3FMAjIaPDdK3FNxyRXRfHPOFeoBn6dmnLyKZgQ2IbTTD1adXhl6PfCIqHhCPvurigv7nf7mYuWZZ19MmJzmg==";
    name = "darwin-x64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/linux-arm64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/linux-arm64/-/linux-arm64-7.0.2003.tgz";
    hash = "sha512-eAET4JpyfBbg8SO0K74o4R55tEjVC292pIyxGOw2XGf8x/HrPNyxwQ478jMYOM54FIVOHc8sJ6VRHxluy6lucw==";
    name = "linux-arm64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/linux-x64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/linux-x64/-/linux-x64-7.0.2003.tgz";
    hash = "sha512-GXdyO/XyqDJ3s/llR/oOktLsYNjZtWSQBy0JMc+/0gsNPvTcseKPhn9c6KcFyWmnr6H4vljYALbujonqSzzEGw==";
    name = "linux-x64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/win32-arm64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/win32-arm64/-/win32-arm64-7.0.2003.tgz";
    hash = "sha512-TWauXnPfet0VgpmrstoAK58eJ4gbuwPUuUTQmYQAzE/RG1CpnxXtrKUJULf6lyerPE4KN3gM+DflIA1hOH+38Q==";
    name = "win32-arm64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/win32-x64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/win32-x64/-/win32-x64-7.0.2003.tgz";
    hash = "sha512-DoRmfe7j8VqNlukp8liRVW45GQDhzRccNenjD/pdzelgtffW47pCMd1xbJLkPaPbKnTwID3onn3VZlL7JbebEA==";
    name = "win32-x64-7.0.2003.tgz";
  };
  "@oxlint/binding-android-arm-eabi@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-android-arm-eabi/-/binding-android-arm-eabi-1.87.0.tgz";
    hash = "sha512-22tVIHlB9898OYsBKmYB6He1MCSqdTmK1BVWuSNUTVrpS0KWNege+U9uEYqGJ+KatQag0r/oU44i3OOs46z7HQ==";
    name = "binding-android-arm-eabi-1.87.0.tgz";
  };
  "@oxlint/binding-android-arm64@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-android-arm64/-/binding-android-arm64-1.87.0.tgz";
    hash = "sha512-JfZQ3MWf74n8ov0DojZpkOduIubYJvZL5tbTMMhDutsal6u1xH1QuNpN+lK+EQwF8AeAfgwTR2fgh5U2br27XA==";
    name = "binding-android-arm64-1.87.0.tgz";
  };
  "@oxlint/binding-darwin-arm64@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-darwin-arm64/-/binding-darwin-arm64-1.87.0.tgz";
    hash = "sha512-rkx6Xvvw93z2GImVOyvbZwAZcoY0Z6MJW177XNsSB+i/CBsH7ANyelTp01VZyIkM3iSXtqKVb4+ptBgPHap5pQ==";
    name = "binding-darwin-arm64-1.87.0.tgz";
  };
  "@oxlint/binding-darwin-x64@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-darwin-x64/-/binding-darwin-x64-1.87.0.tgz";
    hash = "sha512-cw5nYw7L/pQ2SgGBgOcg/Qo89llQre3vIc/kuBLhSICzu1r5s8L76H3ug6AIFsD98WpROj8/z5JVzkf4daxHaQ==";
    name = "binding-darwin-x64-1.87.0.tgz";
  };
  "@oxlint/binding-freebsd-x64@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-freebsd-x64/-/binding-freebsd-x64-1.87.0.tgz";
    hash = "sha512-x/SuznE6loRZK9gz9AS4ZmzNzSu+5KdeoCS+sVHhnrE8HM6AD8UyTjwldQTTqlXGvkwHASgB0NiTNOc3o3PdAg==";
    name = "binding-freebsd-x64-1.87.0.tgz";
  };
  "@oxlint/binding-linux-arm-gnueabihf@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.87.0.tgz";
    hash = "sha512-+JEDmCAXiiFmKhAjZhgAOwaHWY6WENOQ5QA+lFuY59tgsUCDOTRi46B+lENK6CWvtxsXpwkZXNOgpjAQcpIpnA==";
    name = "binding-linux-arm-gnueabihf-1.87.0.tgz";
  };
  "@oxlint/binding-linux-arm-musleabihf@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-1.87.0.tgz";
    hash = "sha512-/uC9XqXLAC9AHFLNycwmSQEvKqGrOCgU+uXALI7gNW0DG81TJ/3T2eHnKdRvcb5R1gFEfjxDwI4e4zIa29rICQ==";
    name = "binding-linux-arm-musleabihf-1.87.0.tgz";
  };
  "@oxlint/binding-linux-arm64-gnu@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.87.0.tgz";
    hash = "sha512-FTRYPsBy/M728vnUv7l+KAwSAa3Qi4BQbhVvy7NYuMTZ0sUa/OWsbMx79HVFw6u/5KWcaYayDsoOiv7xbevzDg==";
    name = "binding-linux-arm64-gnu-1.87.0.tgz";
  };
  "@oxlint/binding-linux-arm64-musl@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.87.0.tgz";
    hash = "sha512-6sC+N7IY0h1egd8SrYUGNN7CUyKJZ4bIZakKa7V7hfinf4jfi8Kq4+klJvFp5DqXcwMn44I5MeBwmJluO1odFg==";
    name = "binding-linux-arm64-musl-1.87.0.tgz";
  };
  "@oxlint/binding-linux-ppc64-gnu@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.87.0.tgz";
    hash = "sha512-d5Mnn+ICbhoJPi37Ccjy+86T5qfH2+mSTrTMBXNPfB+wqSWOayBBLLIrCXdUy1YssluCVdGkl+DO9w5r5ODmUA==";
    name = "binding-linux-ppc64-gnu-1.87.0.tgz";
  };
  "@oxlint/binding-linux-riscv64-gnu@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-1.87.0.tgz";
    hash = "sha512-sf5YWuUo1Dx9loqWCgF8P278MycfcD4JHjDC/LV5j11L3Lqa4PFiwCjD6B8kP4AjsgZZkLn3xbpJEtZBaccs4Q==";
    name = "binding-linux-riscv64-gnu-1.87.0.tgz";
  };
  "@oxlint/binding-linux-riscv64-musl@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-1.87.0.tgz";
    hash = "sha512-+aCraYbmK3uU3P0rFojjeaK9pGY6JvBDXh/0CM+gPyWKmNmXmnFe0qj4qj02U4ibFpbd9Pa9CmDvIdjJUd29rA==";
    name = "binding-linux-riscv64-musl-1.87.0.tgz";
  };
  "@oxlint/binding-linux-s390x-gnu@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.87.0.tgz";
    hash = "sha512-7rzbZQIljo6VLWVPqUyLa2P/WV3VFsJB4M52R4NCUJn1A50yjtUsHxiMHFL9opEKGFIiTbZ3VQzmtcJOPUq4NQ==";
    name = "binding-linux-s390x-gnu-1.87.0.tgz";
  };
  "@oxlint/binding-linux-x64-gnu@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.87.0.tgz";
    hash = "sha512-Dry46Fa+AXE/xt9J/YriujU1pU9mzfNWHGQwtOYibAFH8HLrKWCi93AhIGnuUMiwn2JbuBkRyz51f50Ly4r4ow==";
    name = "binding-linux-x64-gnu-1.87.0.tgz";
  };
  "@oxlint/binding-linux-x64-musl@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-x64-musl/-/binding-linux-x64-musl-1.87.0.tgz";
    hash = "sha512-f/HMZez74gJvnRpGz+b5sdGyWrEgRLmFTXg9sNoqjPWogGxYHUhXKTKyMiYsu9rUGR2ciYqL3fk+Ua4JhMJbRA==";
    name = "binding-linux-x64-musl-1.87.0.tgz";
  };
  "@oxlint/binding-openharmony-arm64@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-openharmony-arm64/-/binding-openharmony-arm64-1.87.0.tgz";
    hash = "sha512-lEC6ZfPZm/07JlB7FsOWX9o1RiHlXiBW594LSUGuXmekC8LZmvUPP9XzE2WZcNxJi5cHA/Fw56o02c3JxgMA5g==";
    name = "binding-openharmony-arm64-1.87.0.tgz";
  };
  "@oxlint/binding-win32-arm64-msvc@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.87.0.tgz";
    hash = "sha512-afBWKOD36dUiA9AenaiWpCg8xfyUVPYznyAAVXu413brK4RA5UI/Xoc4yfeGIT8G1a44MV+JR7hioryerBDzGQ==";
    name = "binding-win32-arm64-msvc-1.87.0.tgz";
  };
  "@oxlint/binding-win32-ia32-msvc@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-1.87.0.tgz";
    hash = "sha512-daptNsEOuru4/nJTxV4DBHNJ5GepzmaBVQf+jjgKQGi9NRlZKik+RFq4hUL7ewsF1pwjKM+SkYaMbF82UwFGnw==";
    name = "binding-win32-ia32-msvc-1.87.0.tgz";
  };
  "@oxlint/binding-win32-x64-msvc@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.87.0.tgz";
    hash = "sha512-k+m/EShyXE29J/r1fjk0HlAzhN5JhIvj044oSJkXTEkCLrWZQgXb/3r4q5LTw/eaKW/4GuMXG2xmiJs3s5rPNw==";
    name = "binding-win32-x64-msvc-1.87.0.tgz";
  };
  "@oxlint/plugins@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/plugins/-/plugins-1.79.0.tgz";
    hash = "sha512-S0uyoxakDINJ4DPgqxGlEEvrdSMeQb7Z2lKVjxoY2gwsbZbfg2Xr8Klfeo5ZeraHmmdBCELFUHkSe6KEmBpMvg==";
    name = "plugins-1.79.0.tgz";
  };
  "@polka/url@1.0.0-next.29" = fetchurl {
    url = "https://npm.flatt.tech/@polka/url/-/url-1.0.0-next.29.tgz";
    hash = "sha512-wwQAWhWSuHaag8c4q/KN/vCoeOJYshAIvMQwD4GpSb3OiZklFfvAgmj0VCBBImRpuF/aFgIRzllXlVX93Jevww==";
    name = "url-1.0.0-next.29.tgz";
  };
  "@rolldown/binding-android-arm-eabi@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-android-arm-eabi/-/binding-android-arm-eabi-1.2.8.tgz";
    hash = "sha512-tN5aztYkKCte4i5SIrrz5yK/HMjEuCqCSCJa418jOV8tZ1cBY3YF2otxB1ktPxzsLA1BeTqwapK0bfjxNvHJVw==";
    name = "binding-android-arm-eabi-1.2.8.tgz";
  };
  "@rolldown/binding-android-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-android-arm64/-/binding-android-arm64-1.2.8.tgz";
    hash = "sha512-dIYTWl9XprMUiQFoc55KUyk/oS8SKYH3zFl0LTR7RT0Xj4hgSVyuJcroH8JUu8RcpF8fTB6E0aOwCkZoYPcDSQ==";
    name = "binding-android-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-darwin-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-darwin-arm64/-/binding-darwin-arm64-1.2.8.tgz";
    hash = "sha512-PCSDQGXD2IyTEFrcgPyBM8jJuGmrbCMuoIOXdbEGVemruKACXoLQJrb+A45Z0L5t1RQkdfJprAYPkikbh7dzdA==";
    name = "binding-darwin-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-darwin-x64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-darwin-x64/-/binding-darwin-x64-1.2.8.tgz";
    hash = "sha512-Uk7lRsGhPFHVX/sAUC6D5H9Ol30dFHd6iquokll2th3LpdJ3F5CzQB+7DHn0Ri2mG+U7k2zXiPHDrwZenXhwSA==";
    name = "binding-darwin-x64-1.2.8.tgz";
  };
  "@rolldown/binding-freebsd-x64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-freebsd-x64/-/binding-freebsd-x64-1.2.8.tgz";
    hash = "sha512-DjszaTEVogPqA5bYzsEeqDCQxbcp2fexQwKcRspYji2yzR68fCf+e4fx6kBSRDwX5/brZaHw/hWS9+A/+/w9sQ==";
    name = "binding-freebsd-x64-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm-gnueabihf@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.2.8.tgz";
    hash = "sha512-zmwa7FTmdzB6aaEEuuls18H6Ap5JmJPSoPTuXixeJZV6tG40SyLkApQtz1g8ptZtiEKqj9OM0oNLPh1AgvE31Q==";
    name = "binding-linux-arm-gnueabihf-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.2.8.tgz";
    hash = "sha512-KdYQDPHwJVnbFwdTGMgxsI9SqblBlz6STGM+w1We/d5B8OWWidYH0MwkU/uA1wM5fIpO2MkOVxXrNzzuZhw9ew==";
    name = "binding-linux-arm64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm64-musl@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.2.8.tgz";
    hash = "sha512-jFJTifHnNPY+yzOoNZQfSIysrVyXzEQPhPnOUjmD1bcQGHH6s7c8cViKWar8YplQImE5N9JRqMCLrM2CdxOrZA==";
    name = "binding-linux-arm64-musl-1.2.8.tgz";
  };
  "@rolldown/binding-linux-ppc64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.2.8.tgz";
    hash = "sha512-FhiOziBDWPBjbcmRzfLyIJnaP7AVMFXT7YCXPjXxj7wKU3vx24RjrCNN/zjvVa+N2vVoHJwCoUBvsrN/DG3zIA==";
    name = "binding-linux-ppc64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-s390x-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.2.8.tgz";
    hash = "sha512-WnHfADMzOV2Y55wlx1hzzQnar/wDt/VdvWSD99r18Mz9ylNieIGOkRx3UV21h7m/eJvjySYJkO26VvGNFkwsIQ==";
    name = "binding-linux-s390x-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-x64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.2.8.tgz";
    hash = "sha512-H9tRr5ibfXFVLxbPOseVewewFpl28zcEdjRDt2FTUZU7odxP0gEv1ki4/kGmcGOh78oRwZuuQllGLZ9zTJp84g==";
    name = "binding-linux-x64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-x64-musl@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-x64-musl/-/binding-linux-x64-musl-1.2.8.tgz";
    hash = "sha512-UefiqfM3D6IVNlZ8tSGs9+Ejjud2T+oxO0IHADU45Y+lyEjD2dVFyZHbkfX0LUb5Zugo/oIv1eCO/KVYhgYJYA==";
    name = "binding-linux-x64-musl-1.2.8.tgz";
  };
  "@rolldown/binding-openharmony-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-openharmony-arm64/-/binding-openharmony-arm64-1.2.8.tgz";
    hash = "sha512-637Ke4kWSy6rp9cxQ9gMOXlxPgIw/c1beASV4M//3+9I4uwBVOOl74G+e3zyU3u19U7RkRl/HuewixZ/Z6+Rjg==";
    name = "binding-openharmony-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-win32-arm64-msvc@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.2.8.tgz";
    hash = "sha512-xWBkPOF1Q9k/Gv1nQXnVdLxKu74jXppuOM4Z3mnypVUJJJwLsMl7hNJGRAUJoG8A5MgOI1ACKM+wBFxSJzKy4A==";
    name = "binding-win32-arm64-msvc-1.2.8.tgz";
  };
  "@rolldown/binding-win32-x64-msvc@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.2.8.tgz";
    hash = "sha512-uz2ZvfgXbxqNwijjjbxrnvALwpyODDcgc1T1N8N3rf/DXKQmaFwmB4LX4yyjggpwN2obdQLb2rgirX5ffCWYng==";
    name = "binding-win32-x64-msvc-1.2.8.tgz";
  };
  "@rolldown/pluginutils@1.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/pluginutils/-/pluginutils-1.0.1.tgz";
    hash = "sha512-2j9bGt5Jh8hj+vPtgzPtl72j0yRxHAyumoo6TNfAjsLB04UtpSvPbPcDcBMxz7n+9CYB0c1GxQFxYRg2jimqGw==";
    name = "pluginutils-1.0.1.tgz";
  };
  "@testing-library/dom@10.4.1" = fetchurl {
    url = "https://npm.flatt.tech/@testing-library/dom/-/dom-10.4.1.tgz";
    hash = "sha512-o4PXJQidqJl82ckFaXUeoAW+XysPLauYI43Abki5hABd853iMhitooc6znOnczgbTYmEP6U6/y1ZyKAIsvMKGg==";
    name = "dom-10.4.1.tgz";
  };
  "@testing-library/user-event@14.6.7" = fetchurl {
    url = "https://npm.flatt.tech/@testing-library/user-event/-/user-event-14.6.7.tgz";
    hash = "sha512-MPCpX8bxe8zS+JmmTwLp8jd0dy1rAm60Te/SL8JrQM3qvQJcBOs1d7IefJMyZzqM3EWBrDn/LWDt1BCGu4ASfg==";
    name = "user-event-14.6.7.tgz";
  };
  "@tsconfig/node-ts@23.6.4" = fetchurl {
    url = "https://npm.flatt.tech/@tsconfig/node-ts/-/node-ts-23.6.4.tgz";
    hash = "sha512-37BMJvNQZ+vTgd1xG2TGBkJ6ENeT4eO4Wh2CHrnn0IwH7ybLFCzh4Uc//kc7UIvqiRac4uGdIc1meKOjMSlKzw==";
    name = "node-ts-23.6.4.tgz";
  };
  "@tsconfig/strictest@2.0.8" = fetchurl {
    url = "https://npm.flatt.tech/@tsconfig/strictest/-/strictest-2.0.8.tgz";
    hash = "sha512-XnQ7vNz5HRN0r88GYf1J9JJjqtZPiHt2woGJOo2dYqyHGGcd6OLGqSlBB6p1j9mpzja6Oe5BoPqWmeDx6X9rLw==";
    name = "strictest-2.0.8.tgz";
  };
  "@types/aria-query@5.0.4" = fetchurl {
    url = "https://npm.flatt.tech/@types/aria-query/-/aria-query-5.0.4.tgz";
    hash = "sha512-rfT93uj5s0PRL7EzccGMs3brplhcrghnDoV26NqKhCAS1hVo+WdNsPvE/yb6ilfr5hi2MEk6d5EWJTKdxg8jVw==";
    name = "aria-query-5.0.4.tgz";
  };
  "@types/chai@5.2.3" = fetchurl {
    url = "https://npm.flatt.tech/@types/chai/-/chai-5.2.3.tgz";
    hash = "sha512-Mw558oeA9fFbv65/y4mHtXDs9bPnFMZAL/jxdPFUpOHHIXX91mcgEHbS5Lahr+pwZFR8A7GQleRWeI6cGFC2UA==";
    name = "chai-5.2.3.tgz";
  };
  "@types/deep-eql@4.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@types/deep-eql/-/deep-eql-4.0.2.tgz";
    hash = "sha512-c9h9dVVMigMPc4bwTvC5dxqtqJZwQPePsWjPlpSOnojbor6pGqdk541lfA7AqFQr5pB1BRdq0juY9db81BwyFw==";
    name = "deep-eql-4.0.2.tgz";
  };
  "@types/estree@1.0.9" = fetchurl {
    url = "https://npm.flatt.tech/@types/estree/-/estree-1.0.9.tgz";
    hash = "sha512-GhdPgy1el4/ImP05X05Uw4cw2/M93BCUmnEvWZNStlCzEKME4Fkk+YpoA5OiHNQmoS7Cafb8Xa3Pya8m1Qrzeg==";
    name = "estree-1.0.9.tgz";
  };
  "@types/node@24.13.4" = fetchurl {
    url = "https://npm.flatt.tech/@types/node/-/node-24.13.4.tgz";
    hash = "sha512-YJ7EqCstVTzIr0fMr7qul/977en+pQHrfmuKIo6Zr9i75Be21dr3MovcfvGtyvi2HAUrRerWps5sMO9I7WaxDw==";
    name = "node-24.13.4.tgz";
  };
  "@typescript/typescript-aix-ppc64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-aix-ppc64/-/typescript-aix-ppc64-7.0.2.tgz";
    hash = "sha512-MTKKkWB7p/0E9xi1d1tHtZ5PiLkGEMIq88pK2CubZjOsLtYTLqhgIgi6zepFa+9GHZ6h05NMCkQxGKiPXMxXtQ==";
    name = "typescript-aix-ppc64-7.0.2.tgz";
  };
  "@typescript/typescript-darwin-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-darwin-arm64/-/typescript-darwin-arm64-7.0.2.tgz";
    hash = "sha512-gowzar9MwS/aRWp6f3a4KUqzRjAZjOsmGNCM6LcTgXum+dBfgsBVMN+AgvOCCbguXyick6LJhpBszxMebJ8syA==";
    name = "typescript-darwin-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-darwin-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-darwin-x64/-/typescript-darwin-x64-7.0.2.tgz";
    hash = "sha512-SZ9xZInqApNlNGc9s0W1VSsktYSOe9cFqNOIqmN1Gs8SmkjKZYFt017G4VwPxASInODuAdbTW7sXiFUf893RgA==";
    name = "typescript-darwin-x64-7.0.2.tgz";
  };
  "@typescript/typescript-freebsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-freebsd-arm64/-/typescript-freebsd-arm64-7.0.2.tgz";
    hash = "sha512-W5NH4y/J0plIIS5b2xvTEkU7JFxyqdMAOgf+Ilhl0vHQXKO5dZoxd+C/jEtq56c4F3wk71RB4BMRQ2XdI+bwYQ==";
    name = "typescript-freebsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-freebsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-freebsd-x64/-/typescript-freebsd-x64-7.0.2.tgz";
    hash = "sha512-UMGDx5sTpzNw3WiPebH7l90IWfJggEd+egHt/q6p7/Cm3zqoV7VxkGXt+3DxPIw8CcmvAB0j3sVVfbhX+M4Tpw==";
    name = "typescript-freebsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-arm64/-/typescript-linux-arm64-7.0.2.tgz";
    hash = "sha512-Qh4eU4/y3yDjnfjjyPYihMj5/ODIlmt+Bzu17OI+fiSRDW57QmU5SiN63exPRNJPKUzcc1INa1NXdrJ+MqHjUQ==";
    name = "typescript-linux-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-arm@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-arm/-/typescript-linux-arm-7.0.2.tgz";
    hash = "sha512-gffT3xPz9sR7j/YJExkyPntrI0P2EP9XbOyWzth2/Gs0RstK+90RBcO0ncXoXy/beYll1SXw846Nf2zdnEz0QQ==";
    name = "typescript-linux-arm-7.0.2.tgz";
  };
  "@typescript/typescript-linux-loong64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-loong64/-/typescript-linux-loong64-7.0.2.tgz";
    hash = "sha512-uEHck9i8hoAzXPiYRib1O7miOnz23SxIeVl6F4LXox+qov1K35jHcEW6VHKvZI+pyvl7fZEP4MCU5LYvIq1GuQ==";
    name = "typescript-linux-loong64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-mips64el@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-mips64el/-/typescript-linux-mips64el-7.0.2.tgz";
    hash = "sha512-R4KvAMnE43W5Qeqb0Ly56O3mWMWIAgsMyz36DCaycd5nbg/9kzm0liw3JocfRqyJY0KPmzFjbswozXyW0DnIYA==";
    name = "typescript-linux-mips64el-7.0.2.tgz";
  };
  "@typescript/typescript-linux-ppc64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-ppc64/-/typescript-linux-ppc64-7.0.2.tgz";
    hash = "sha512-DORx5b3sd/4S7eayxm4FQv+A7CrkUIGRaHiwI8oiHTAI1fAPWhF4J0vAlkC8biAlHSVVwxMQ3tjZ2/DVbnQiiA==";
    name = "typescript-linux-ppc64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-riscv64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-riscv64/-/typescript-linux-riscv64-7.0.2.tgz";
    hash = "sha512-wf0jqEDOjrPRnKwYRyyJDRo11KMbvMFrU+q4zqKyChODBzvlkbhNQfKvLxQCcwTpdDaXSHZTVuh0JoCrKCUMHQ==";
    name = "typescript-linux-riscv64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-s390x@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-s390x/-/typescript-linux-s390x-7.0.2.tgz";
    hash = "sha512-IkwJc3L7yhytWd/ewjyxNDfOmswCm9GWMJT/ue/dU4aZNbwZeYAetq42VyLmsmSjvoX7z74X6ZaYCtzAr0EuGw==";
    name = "typescript-linux-s390x-7.0.2.tgz";
  };
  "@typescript/typescript-linux-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-x64/-/typescript-linux-x64-7.0.2.tgz";
    hash = "sha512-EYdf2cNg7rgCWJnxCdJ+F3V39O8ihb37eHAu1LK8oAFizgTQbPOK7zHHXbPt8rX24COqODXeI3sIf0fCXG7H/A==";
    name = "typescript-linux-x64-7.0.2.tgz";
  };
  "@typescript/typescript-netbsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-netbsd-arm64/-/typescript-netbsd-arm64-7.0.2.tgz";
    hash = "sha512-+polYF4MF04aPpO5FTkHran9yUQDSXqy5GiSDKpsll5jy3l3+g9QLhpf39T+ePtefhXLOGrLl0QIjkQP6VnelA==";
    name = "typescript-netbsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-netbsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-netbsd-x64/-/typescript-netbsd-x64-7.0.2.tgz";
    hash = "sha512-8YIT0EHM/3dq10ZOVF/A7pc/YSMtbcecct4rWtexrnSCHOPcpC2KTLXfTCR6vDpnSiY12heNb1GiN/wu+T/FyA==";
    name = "typescript-netbsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-openbsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-openbsd-arm64/-/typescript-openbsd-arm64-7.0.2.tgz";
    hash = "sha512-APT8+ClYnuYm1u9+kgGXoMj2VzWzcymwh2gNSQVySHfkRDGOTVkoWLjCmOQSaO+PoqQ57B0flRp9SA+7GnnkzQ==";
    name = "typescript-openbsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-openbsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-openbsd-x64/-/typescript-openbsd-x64-7.0.2.tgz";
    hash = "sha512-yX7s+Q0Dln0Dt9tEzZsAjXXR/+ytBM7AlglaqyeMPxQszJ1JhlJdZ6jLA+IzldHtflX81em7lDao1xXu+aRRkg==";
    name = "typescript-openbsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-sunos-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-sunos-x64/-/typescript-sunos-x64-7.0.2.tgz";
    hash = "sha512-dLJDGaLZ1D4HPQn62u1n8mBDkJREwMsAkCdkwd4Ieqw+x3TUyTsqY0YiBCtE6H6OzzgGk3iuZ3vFWRS+E8/d1g==";
    name = "typescript-sunos-x64-7.0.2.tgz";
  };
  "@typescript/typescript-win32-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-win32-arm64/-/typescript-win32-arm64-7.0.2.tgz";
    hash = "sha512-Gyl1Vy6OsWesLzmq+EP0Fb7b4Nid5232AvcA2SFcdYreldpNtYFFofPjnt62y9hQy7VTaZp65ICJjuAQRaVcIQ==";
    name = "typescript-win32-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-win32-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-win32-x64/-/typescript-win32-x64-7.0.2.tgz";
    hash = "sha512-0BQ3HkAHHlKLSp1qRvf3SUhGpGsDuhB/jgFw75guyqbxJqEaS0Cw/VFO8i2nHglJUzQCRtMMR/IBAKE3ETMC4g==";
    name = "typescript-win32-x64-7.0.2.tgz";
  };
  "@vitest/browser-preview@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/browser-preview/-/browser-preview-5.0.3.tgz";
    hash = "sha512-jfnEBv5yDRPR1MeiTlTW5bcZoPsiI7MBhpZR8IJiSxVhdK6Pa4gPk3tLHTRxVHy24kkWxY2TnUbnszU3J1bQJw==";
    name = "browser-preview-5.0.3.tgz";
  };
  "@vitest/browser@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/browser/-/browser-5.0.3.tgz";
    hash = "sha512-7KHIkVA/gTRxQV9qPa9qLK+g5INZG6iRrlwXSFG5EKsOomW3UzzW7wsdt1Yp5PufzQ43lniuONlb4lUVCC2qSg==";
    name = "browser-5.0.3.tgz";
  };
  "@vitest/mocker@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/mocker/-/mocker-5.0.3.tgz";
    hash = "sha512-T8sWAIbkSyAjkwTcaEc3Iu0o9A27X1/kdXrizhZkGuSKScRQtRzclfAMpOTcGdXCsqxeWlpGy3XjqaW8CpLORg==";
    name = "mocker-5.0.3.tgz";
  };
  "@vitest/pretty-format@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/pretty-format/-/pretty-format-5.0.3.tgz";
    hash = "sha512-3hr5eV5z2ff0l2Q1vaKQbB4j3M3tElw8stDokEOTqXJB3Es5VrT8gBRIMY59gGuFp8Y61sWlWFK1aNUH5dHDYw==";
    name = "pretty-format-5.0.3.tgz";
  };
  "@vitest/snapshot@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/snapshot/-/snapshot-5.0.3.tgz";
    hash = "sha512-SK4YTg9jL+jwakHIZxfciuvyOQsbY15AueR3USGtsXzmy+3FbJgqjAbC+ac20mRLwfEDtO5sfTqK6bUCDTRVPA==";
    name = "snapshot-5.0.3.tgz";
  };
  "@vitest/spy@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/spy/-/spy-5.0.3.tgz";
    hash = "sha512-XhFysQTB8AZ+P4gMi+Lpo99vg2AZi0qKpaB9yXQl37+CaMEAPO3iH/wGVnSyL5MPERiLezpqTVtrR6UZH5GCXg==";
    name = "spy-5.0.3.tgz";
  };
  "@vitest/ui@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/ui/-/ui-5.0.3.tgz";
    hash = "sha512-9dfvqDBvSbHM6y9YVXxAypkl2z7mrWozK/JFo237qI0cj/3M/kzDKiVZqzi3TE54Ler7Jditud7OMBZCyUvRHA==";
    name = "ui-5.0.3.tgz";
  };
  "@vitest/utils@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/utils/-/utils-5.0.3.tgz";
    hash = "sha512-77fDTZv8eu1CzlIfgPU2yrl5MXSUaUAOvgdZEeVm3X3WIxUubIX2SforqS6176lT32HCF6uBVMYVqfHxw7o6eg==";
    name = "utils-5.0.3.tgz";
  };
  "@voidzero-dev/vite-plus-core@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-core/-/vite-plus-core-1.1.0.tgz";
    hash = "sha512-Ai6HQP1zG0H3ZrmStEaMVKtDzW0xU3VgMzm3LFaXDQMEp8nAqvp0VGoU8HmpB9xv9vDSl+UxiSNOpuY9T714OQ==";
    name = "vite-plus-core-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-darwin-arm64@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-darwin-arm64/-/vite-plus-darwin-arm64-1.1.0.tgz";
    hash = "sha512-iWJdQZBRZWB6X1Aadk0Rrs/NJeP32Qb0OGeWnu1AYL0g6ZCj1yy3l9Oa+HasDyG97s+4UYo523LdBAAv3dlFwg==";
    name = "vite-plus-darwin-arm64-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-darwin-x64@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-darwin-x64/-/vite-plus-darwin-x64-1.1.0.tgz";
    hash = "sha512-IYSQ2KdigRMuVkKCC+e5uNliCTSHa8j3ajHsFG2cfXoiGHS1f4ausbMEzNYtn9Tcn0Xsyo7l0LN8lvB7MapJhA==";
    name = "vite-plus-darwin-x64-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-arm64-gnu@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-arm64-gnu/-/vite-plus-linux-arm64-gnu-1.1.0.tgz";
    hash = "sha512-PmrJG8Md5KCWi/akWJz5GRjei2QfRf48R4rPB9CfualzAAlpMOmaMGeV3eloWVAFye85uhdtzCmIAqN5OUVBJA==";
    name = "vite-plus-linux-arm64-gnu-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-arm64-musl@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-arm64-musl/-/vite-plus-linux-arm64-musl-1.1.0.tgz";
    hash = "sha512-zFr57++m5U474XEMcFGV025TOv9V2I5d87yylcuI/SvxQwDE9P7T5iRl55vGzQOzzInSnQuru6ByNIfmGa+84A==";
    name = "vite-plus-linux-arm64-musl-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-x64-gnu@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-x64-gnu/-/vite-plus-linux-x64-gnu-1.1.0.tgz";
    hash = "sha512-DXeRuTMylEbIVCQX+pSBM27lSPQwAKO6PDnGBJ6nFGhu37AmNeVl7cIChtcniXOuykbFduhSt3eIr/6CZHoEag==";
    name = "vite-plus-linux-x64-gnu-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-x64-musl@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-x64-musl/-/vite-plus-linux-x64-musl-1.1.0.tgz";
    hash = "sha512-J7/Mb/kxtENUsL5Gh+8SSr/p054fSqU4oj0GEthr/2VEFSwZouOUigk6CzE7ANKFeTNJm40n8QCnjm7Oiy09pQ==";
    name = "vite-plus-linux-x64-musl-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-win32-arm64-msvc@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-win32-arm64-msvc/-/vite-plus-win32-arm64-msvc-1.1.0.tgz";
    hash = "sha512-EXWz8Tt7skmI0fLMSq5zYcuHo6SCF0reG55qDB/NMvWVIAca6Dborq7D1HyKA8v6p39zOl8r07gR7yXuYv7eeQ==";
    name = "vite-plus-win32-arm64-msvc-1.1.0.tgz";
  };
  "@voidzero-dev/vite-plus-win32-x64-msvc@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-win32-x64-msvc/-/vite-plus-win32-x64-msvc-1.1.0.tgz";
    hash = "sha512-K9k77Mj/TszFHKsZePKsyfsIPo8HbjKeJUxaSJ6YZKAmSh9QvDsMFe4i4/HALwyii/PR1EQ8N0iN1nf9cNimGQ==";
    name = "vite-plus-win32-x64-msvc-1.1.0.tgz";
  };
  "@yuku-codegen/binding-android-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-android-arm64/-/binding-android-arm64-0.9.5.tgz";
    hash = "sha512-jrOY5WM+AaAqkv51fHP1x28ifto4WgcZVzodLUyMU1jMWn5Sq+VciRdk/n8E0Ey5w4p4cWWE+m5GfXWOYh7Kzw==";
    name = "binding-android-arm64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-darwin-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-darwin-arm64/-/binding-darwin-arm64-0.9.5.tgz";
    hash = "sha512-4O4lkCQIzPZGjiNB1GORSI6hBECbiiSBS/APZXPvNKYH+nhY4uuqv03LNXA+SET3hoBjvr95P5rIhY8KQaQUBA==";
    name = "binding-darwin-arm64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-darwin-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-darwin-x64/-/binding-darwin-x64-0.9.5.tgz";
    hash = "sha512-9EvoUO0SEhD6/d8VHdWuPerepPMSR1y84+UEgz8Un1Ope14Oe7xMvePpEQLTLovoIFZ8Zg3iZ8z8E11pZMqC3g==";
    name = "binding-darwin-x64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-freebsd-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-freebsd-x64/-/binding-freebsd-x64-0.9.5.tgz";
    hash = "sha512-HqT78WwgHTmp8lwujoUa9CrIortX4DdpuiVC18ZPSGvuuJf4ylpIEI6QrQEM78Zwz3muhAWAOXZ5irdiYY+AyA==";
    name = "binding-freebsd-x64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm-gnu/-/binding-linux-arm-gnu-0.9.5.tgz";
    hash = "sha512-QJXwIW6Ms3QIawbcBIedmrmXnfdpuAOjZJ/eAABq5XTzWvSxZ7lutu9W5yIHahlaTaFnBo7ikrVMD1szLTpPUw==";
    name = "binding-linux-arm-gnu-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm-musl/-/binding-linux-arm-musl-0.9.5.tgz";
    hash = "sha512-eHbFy3IHGb+IYarrYwAo0yWSEQV3eAmEn6VrsKA6I1Wy1YPJxWqSJlV69JhqsHtJuJlljUIF3ex0y46yaKIu9w==";
    name = "binding-linux-arm-musl-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.9.5.tgz";
    hash = "sha512-ByoJMbySTaDhjAXSu8q6Lh7HKg3YoesXpcT72aYk0Aiw4PCznmY4ybpLTq0RCvp0RIPhFm/6yECFiGBwyCC1nw==";
    name = "binding-linux-arm64-gnu-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.9.5.tgz";
    hash = "sha512-gD9vfXIoBw1toSxhO9rgmSu/FEfy3PMznJAxVjIuH8DrWEiDKXmJO0pJKfj1Ltbe/TmtWVZR+TjISqeSIGQzMg==";
    name = "binding-linux-arm64-musl-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-x64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.9.5.tgz";
    hash = "sha512-BARvdnvqMGjOr5Iel2JH+9H5vAIE0R6H0Z2fsT02xrvmI/1ZXNB8lkuX+ZGevPhZb3zJ9WeC/R8JZstrsUOK5g==";
    name = "binding-linux-x64-gnu-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-x64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-x64-musl/-/binding-linux-x64-musl-0.9.5.tgz";
    hash = "sha512-x8flcevS1fbb7ESrmpOY/pON4eInSaE/7Ktjqx2udOE2W33BNSZmJuwpyUgo54AoHNqrcaM7szqydyJn5fNvew==";
    name = "binding-linux-x64-musl-0.9.5.tgz";
  };
  "@yuku-codegen/binding-win32-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-win32-arm64/-/binding-win32-arm64-0.9.5.tgz";
    hash = "sha512-KOL/rBatWqH4ZpCNoF8ZtSNdOJbAxBJLmk/VeRciepGROPTbPum1A9t67GpFgOU7qrkUWlPJdJ+KHKbvbmOt+w==";
    name = "binding-win32-arm64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-win32-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-win32-x64/-/binding-win32-x64-0.9.5.tgz";
    hash = "sha512-FxENahEjWSan59Syh/us/Kf4wNq8qrJLFJ3R2N4Oiwtb6yNdz/rWLNTIoNSssnsp7IoWJdUP6o/Z8ppg7lXMcg==";
    name = "binding-win32-x64-0.9.5.tgz";
  };
  "@yuku-parser/binding-android-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-android-arm64/-/binding-android-arm64-0.9.5.tgz";
    hash = "sha512-A2JCFCSHfnficqYEw4Iujpx7XrkMM3UfFcgJFmYpZSo9zM4nyhmdIIE0FogSduuU60lhM0/UcfuUBXIVNBMlGQ==";
    name = "binding-android-arm64-0.9.5.tgz";
  };
  "@yuku-parser/binding-darwin-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-darwin-arm64/-/binding-darwin-arm64-0.9.5.tgz";
    hash = "sha512-3PiyU+Eare4YuKaQ22N98/yAiROPY5o/NQJHraICzDvk4pgS+m+bgLKOvkGBRn33OnV95Vdv1Mn38b+MQHpULQ==";
    name = "binding-darwin-arm64-0.9.5.tgz";
  };
  "@yuku-parser/binding-darwin-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-darwin-x64/-/binding-darwin-x64-0.9.5.tgz";
    hash = "sha512-blFMAFI7AInI83XaiOF8cIeiRM46Nz9EfpZtZPRLbKxSA9aAr5v8aHYpmfN6NoyXxAv/10pwS4gsAuc1W6fy5Q==";
    name = "binding-darwin-x64-0.9.5.tgz";
  };
  "@yuku-parser/binding-freebsd-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-freebsd-x64/-/binding-freebsd-x64-0.9.5.tgz";
    hash = "sha512-TsNuL4qsZdO0tHp5GW43Y5fHeLPpPHA675wdcPNTcdq2ZO5AvsQWFFoiDg8CH4oBktfsQ9tdvKhjLnLYwKvp4g==";
    name = "binding-freebsd-x64-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm-gnu/-/binding-linux-arm-gnu-0.9.5.tgz";
    hash = "sha512-b0afYK5gHeV8RdmOcqAlgM8ONsye4cax4DMnIBaoJyPMd1UTGvTbpkqQcPVdhmHlcfcGVGMV1laeVovlr/dscw==";
    name = "binding-linux-arm-gnu-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm-musl/-/binding-linux-arm-musl-0.9.5.tgz";
    hash = "sha512-fD3lKzl+r6j6n8DwiMY53qnh5DLqD8KJjCp+NbVud54Nnh3Q9Wprqss3YzyMHP3NSJk663Wlg1E1X5qOuFVFig==";
    name = "binding-linux-arm-musl-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.9.5.tgz";
    hash = "sha512-aRU/aCphV1MWCl/lvI6NX8LgucHQ68Fx+vz7NBb/5MEr2EuzCxiPOQqeFcMdWh+2AED/p0AvAREch0c+cSnlhA==";
    name = "binding-linux-arm64-gnu-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.9.5.tgz";
    hash = "sha512-5+Guro0l8H473YXlEjVNBRLN/IbPbJdnQh1zo0OLt49xxnON+XMJRRaEyTOTfkn9QSRg0+BhEKGR4W9Gu2uZJQ==";
    name = "binding-linux-arm64-musl-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-x64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.9.5.tgz";
    hash = "sha512-pwwSyV9q+GlvzSXlsMZBMlgk22L5bud714/vqZCdeUTivzeUVltQzUaf3IQXOGXdpc59JYTeuMCtbGquaAUoCA==";
    name = "binding-linux-x64-gnu-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-x64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-x64-musl/-/binding-linux-x64-musl-0.9.5.tgz";
    hash = "sha512-z18j6JN3lBHH8vzN7gG1M8fI0nlgItSfnC9PfbmUbt97iHViKfw2iA2G9fGwRMe5LyPRZBrejIlapbygPbpdaw==";
    name = "binding-linux-x64-musl-0.9.5.tgz";
  };
  "@yuku-parser/binding-win32-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-win32-arm64/-/binding-win32-arm64-0.9.5.tgz";
    hash = "sha512-s6Gwttb1dQvtPX6Bgkw+UPC9IO3UBDXc6Zezog8MMgvu3UfJBBB9TQqKBX/2quu0Eyh+lLSAyNlIyyecaagUPg==";
    name = "binding-win32-arm64-0.9.5.tgz";
  };
  "@yuku-parser/binding-win32-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-win32-x64/-/binding-win32-x64-0.9.5.tgz";
    hash = "sha512-FrERt9YWatY3bJfSUdi4YWY+6iQcyo3MzCC821BxlWM5TFZEHijnpz/bknR79VHlXY/9CvXz8ZlaAGPsTtN3nw==";
    name = "binding-win32-x64-0.9.5.tgz";
  };
  "@yuku-toolchain/types@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-toolchain/types/-/types-0.9.5.tgz";
    hash = "sha512-KiuLNNgX9uNealaWAR+G3/cMXnRk9x4TY2EkYe/KIag+UPdwiA0RRf1hr1WAxzTP8KGzCTkqUdLPvqh32sEO3w==";
    name = "types-0.9.5.tgz";
  };
  "ansi-regex@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/ansi-regex/-/ansi-regex-5.0.1.tgz";
    hash = "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
    name = "ansi-regex-5.0.1.tgz";
  };
  "ansi-styles@5.2.0" = fetchurl {
    url = "https://npm.flatt.tech/ansi-styles/-/ansi-styles-5.2.0.tgz";
    hash = "sha512-Cxwpt2SfTzTtXcfOlzGEee8O+c+MmUgGrNiBcXnuWxuFJHe6a5Hz7qwhwe5OgaSYI0IJvkLqWX1ASG+cJOkEiA==";
    name = "ansi-styles-5.2.0.tgz";
  };
  "aria-query@5.3.0" = fetchurl {
    url = "https://npm.flatt.tech/aria-query/-/aria-query-5.3.0.tgz";
    hash = "sha512-b0P0sZPKtyu8HkeRAfCq0IfURZK+SuwMjY1UXGBU27wpAiTwQAIlq56IbIO+ytk/JjS1fMR14ee5WBBfKi5J6A==";
    name = "aria-query-5.3.0.tgz";
  };
  "assertion-error@2.0.1" = fetchurl {
    url = "https://npm.flatt.tech/assertion-error/-/assertion-error-2.0.1.tgz";
    hash = "sha512-Izi8RQcffqCeNVgFigKli1ssklIbpHnCYc6AknXGYoB6grJqyeby7jv12JUQgmTAnIDnbck1uxksT4dzN3PWBA==";
    name = "assertion-error-2.0.1.tgz";
  };
  "chai@6.2.2" = fetchurl {
    url = "https://npm.flatt.tech/chai/-/chai-6.2.2.tgz";
    hash = "sha512-NUPRluOfOiTKBKvWPtSD4PhFvWCqOi0BGStNWs57X9js7XGTprSmFoz5F0tWhR4WPjNeR9jXqdC7/UpSJTnlRg==";
    name = "chai-6.2.2.tgz";
  };
  "convert-source-map@2.0.0" = fetchurl {
    url = "https://npm.flatt.tech/convert-source-map/-/convert-source-map-2.0.0.tgz";
    hash = "sha512-Kvp459HrV2FEJ1CAsi1Ku+MY3kasH19TFykTz2xWmMeq6bk2NU3XXvfJ+Q61m0xktWwt+1HSYf3JZsTms3aRJg==";
    name = "convert-source-map-2.0.0.tgz";
  };
  "dequal@2.0.3" = fetchurl {
    url = "https://npm.flatt.tech/dequal/-/dequal-2.0.3.tgz";
    hash = "sha512-0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
    name = "dequal-2.0.3.tgz";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://npm.flatt.tech/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
    name = "detect-libc-2.1.2.tgz";
  };
  "dom-accessibility-api@0.5.16" = fetchurl {
    url = "https://npm.flatt.tech/dom-accessibility-api/-/dom-accessibility-api-0.5.16.tgz";
    hash = "sha512-X7BJ2yElsnOJ30pZF4uIIDfBEVgF4XEBxL9Bxhy6dnrm5hkzqmsWHGTiHqRiITNhMyFLyAiWndIJP7Z1NTteDg==";
    name = "dom-accessibility-api-0.5.16.tgz";
  };
  "es-module-lexer@2.3.2" = fetchurl {
    url = "https://npm.flatt.tech/es-module-lexer/-/es-module-lexer-2.3.2.tgz";
    hash = "sha512-poHGpORABojJJucnV9KbOavETW8lBVnphkW77ER5/BQ5Fz7oXSoCNek7IH3vR5nRjdsEz926ibFYX8KtLQmdyw==";
    name = "es-module-lexer-2.3.2.tgz";
  };
  "estree-walker@3.0.3" = fetchurl {
    url = "https://npm.flatt.tech/estree-walker/-/estree-walker-3.0.3.tgz";
    hash = "sha512-7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
    name = "estree-walker-3.0.3.tgz";
  };
  "expect-type@1.4.0" = fetchurl {
    url = "https://npm.flatt.tech/expect-type/-/expect-type-1.4.0.tgz";
    hash = "sha512-KfYbmpRm0VbLjEvVa9yGwCi9GI34xvi7A/HXYWQO65CSD2u3MczUJSuwXKFIxlGsgBQizV9q5J9NHj4VG0n+pA==";
    name = "expect-type-1.4.0.tgz";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://npm.flatt.tech/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
    name = "fdir-6.5.0.tgz";
  };
  "fflate@0.8.3" = fetchurl {
    url = "https://npm.flatt.tech/fflate/-/fflate-0.8.3.tgz";
    hash = "sha512-tbZNuJrLwGUp3zshBtdy4W+ORxZuIh8a5ilyIEQDC5rY1f3U20JMry0Ll3WBzU58EZKsEuJFXhb5gwv8CsPvgA==";
    name = "fflate-0.8.3.tgz";
  };
  "flatted@3.4.4" = fetchurl {
    url = "https://npm.flatt.tech/flatted/-/flatted-3.4.4.tgz";
    hash = "sha512-5+ybhBZANEJxaH3X5evAFatUxLfEHSr7n6kYJ+1Qd0mUqr4eu9gIf6GDbWHf8RJijHrjjO8G+la14SlL2SeS1Q==";
    name = "flatted-3.4.4.tgz";
  };
  "fsevents@2.3.3" = fetchurl {
    url = "https://npm.flatt.tech/fsevents/-/fsevents-2.3.3.tgz";
    hash = "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==";
    name = "fsevents-2.3.3.tgz";
  };
  "js-tokens@4.0.0" = fetchurl {
    url = "https://npm.flatt.tech/js-tokens/-/js-tokens-4.0.0.tgz";
    hash = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
    name = "js-tokens-4.0.0.tgz";
  };
  "lightningcss-android-arm64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-android-arm64/-/lightningcss-android-arm64-1.33.0.tgz";
    hash = "sha512-gEpRTalKdosp4Bb8qWtc2iOgE5SeIHlpS1up9bFq2wAyYhl1UdTObYiHe98zEM9SQvSoqQZ1IQD0JNpg3Ml5pg==";
    name = "lightningcss-android-arm64-1.33.0.tgz";
  };
  "lightningcss-darwin-arm64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-darwin-arm64/-/lightningcss-darwin-arm64-1.33.0.tgz";
    hash = "sha512-Sciaz8eenNTKn9b3t7+xr0ipTp9YxKQY4npwQ3mrRuL0BAVHBLyZxofhaKBAVtzmtRZ/zTyo0/to4B1uWG/Djg==";
    name = "lightningcss-darwin-arm64-1.33.0.tgz";
  };
  "lightningcss-darwin-x64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-darwin-x64/-/lightningcss-darwin-x64-1.33.0.tgz";
    hash = "sha512-Z5UPAxzrjlWNNyGy6i65cJzzvgJ5D3T6wMvs+gWpY9d7qRhANrxqAp6LhxIgZhWEw18RfJTGcRxjuLIBr+m8XQ==";
    name = "lightningcss-darwin-x64-1.33.0.tgz";
  };
  "lightningcss-freebsd-x64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-freebsd-x64/-/lightningcss-freebsd-x64-1.33.0.tgz";
    hash = "sha512-QQM/Ti/hQajJwCY+RiWuCZ9sdtI/XQk7nDK5vC8kkdwixezOlDgvDx7+RT+QjK6FcFT4MpsuoBnHIo/O3StRRg==";
    name = "lightningcss-freebsd-x64-1.33.0.tgz";
  };
  "lightningcss-linux-arm-gnueabihf@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm-gnueabihf/-/lightningcss-linux-arm-gnueabihf-1.33.0.tgz";
    hash = "sha512-N7FVBe6iS24MlM6R/4RBTxGhQheZGs7tiQ9U32UtF75NzP5Q7xWPRqLBCKxlRQRk3rY1jCIPLzx7WzOhuUIRLQ==";
    name = "lightningcss-linux-arm-gnueabihf-1.33.0.tgz";
  };
  "lightningcss-linux-arm64-gnu@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm64-gnu/-/lightningcss-linux-arm64-gnu-1.33.0.tgz";
    hash = "sha512-j2v/itmy4HlNxlc6voKXYgBqNi0Ng2LShg4z7GufpEgs05P+2suBVyi9I6YHq5uoVFx9ETin3eCEhLVyXGQnKg==";
    name = "lightningcss-linux-arm64-gnu-1.33.0.tgz";
  };
  "lightningcss-linux-arm64-musl@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm64-musl/-/lightningcss-linux-arm64-musl-1.33.0.tgz";
    hash = "sha512-yiO5ROMuYQgXbC60yjZU5CYSFZGKXL0HFATXt9mHJn1+zW55oCtMI9NfcVhYLMFDL7gV7oBPon/EmMMGg2OvtQ==";
    name = "lightningcss-linux-arm64-musl-1.33.0.tgz";
  };
  "lightningcss-linux-x64-gnu@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.33.0.tgz";
    hash = "sha512-ar+Ju7LmcN0Jo4FpL4hpFybwNG9/3A/Br5KW2n2jyODg3MEZXaDYADdemoNS+BDNfMgKvylJLj4S5tyRActuAg==";
    name = "lightningcss-linux-x64-gnu-1.33.0.tgz";
  };
  "lightningcss-linux-x64-musl@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-x64-musl/-/lightningcss-linux-x64-musl-1.33.0.tgz";
    hash = "sha512-RYiYbkokw0trfKqqzfF55lginwEPrD3OJDfTuJzFs1MK6iFnDenaz1fqLLtX4ITG3OktJQXOeTaw1awrBAlZPw==";
    name = "lightningcss-linux-x64-musl-1.33.0.tgz";
  };
  "lightningcss-win32-arm64-msvc@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-win32-arm64-msvc/-/lightningcss-win32-arm64-msvc-1.33.0.tgz";
    hash = "sha512-1K+MPfLSFVpphzpdbfkhlWk6wBrTObBzS2T6db10PNOZgR9GoVsAWzwNyuhUYYbTp23j+4RrncfujZ4uAzXvwA==";
    name = "lightningcss-win32-arm64-msvc-1.33.0.tgz";
  };
  "lightningcss-win32-x64-msvc@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-win32-x64-msvc/-/lightningcss-win32-x64-msvc-1.33.0.tgz";
    hash = "sha512-OlEICDx/Xl0FqSp4bry8zFnCvGpig3Gl4gCquvYwHuqJKEC1+n9NgDniFvqHGmMv1ZkqDJrDqKKSykTDX+ehuA==";
    name = "lightningcss-win32-x64-msvc-1.33.0.tgz";
  };
  "lightningcss@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss/-/lightningcss-1.33.0.tgz";
    hash = "sha512-WkUDrojuJs0xkgGf2udWxa3yGBRxPtxUkB79i6aCZLRgc7PM8fZe9TosfPDcvEpQZbuFASnHYmRLBLUbmLOIIA==";
    name = "lightningcss-1.33.0.tgz";
  };
  "lz-string@1.5.0" = fetchurl {
    url = "https://npm.flatt.tech/lz-string/-/lz-string-1.5.0.tgz";
    hash = "sha512-h5bgJWpxJNswbU7qCrV0tIKQCaS3blPDrqKWx+QxzuzL1zGUzij9XCWLrSLsJPu5t+eWA/ycetzYAO5IOMcWAQ==";
    name = "lz-string-1.5.0.tgz";
  };
  "magic-string@1.4.3" = fetchurl {
    url = "https://npm.flatt.tech/magic-string/-/magic-string-1.4.3.tgz";
    hash = "sha512-z12OxmaPGE0F4xlpGdjuAUckipLpQlTAuAmyGhNoD7ODpYUzvDfvtxUbjM/jwznyP178oju/KDdyi220wNJ0RQ==";
    name = "magic-string-1.4.3.tgz";
  };
  "mrmime@2.0.1" = fetchurl {
    url = "https://npm.flatt.tech/mrmime/-/mrmime-2.0.1.tgz";
    hash = "sha512-Y3wQdFg2Va6etvQ5I82yUhGdsKrcYox6p7FfL1LbK2J4V01F9TGlepTIhnK24t7koZibmg82KGglhA1XK5IsLQ==";
    name = "mrmime-2.0.1.tgz";
  };
  "nanoid@3.3.19" = fetchurl {
    url = "https://npm.flatt.tech/nanoid/-/nanoid-3.3.19.tgz";
    hash = "sha512-Y2tUNy4ouw6tq5oDSKeQYGOyhkUBhNOcGV/02KC+6kd9eDGqdZd++mjMiIDilrBYvjEnCYvVtsuHCuP+okSfug==";
    name = "nanoid-3.3.19.tgz";
  };
  "obug@2.2.1" = fetchurl {
    url = "https://npm.flatt.tech/obug/-/obug-2.2.1.tgz";
    hash = "sha512-XrsrhT5sybtKI6wakr2SPOlGZWWYbUXZ7a0jT8/QOeAPau+1X/bSegNe5YR75oJmEZQbKningirmGOEJCIk61Q==";
    name = "obug-2.2.1.tgz";
  };
  "oxfmt@0.72.0" = fetchurl {
    url = "https://npm.flatt.tech/oxfmt/-/oxfmt-0.72.0.tgz";
    hash = "sha512-16OQeL0uhPZbfmT9S9WWM0Nv9+BmVi8Ra1uTYaSKj/qSCs6FB30KOhz9JoNYw6thT+K5bVxsk/tSEOu497i34g==";
    name = "oxfmt-0.72.0.tgz";
  };
  "oxlint-tsgolint@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/oxlint-tsgolint/-/oxlint-tsgolint-7.0.2003.tgz";
    hash = "sha512-VnK4zlqgmgq/7ZcjzCk/WpN8kKFsYGcB85Io9qT3wL4K8Un3RKmJkp793crNETieMusPMKOA4a+Mw2wbteI6TQ==";
    name = "oxlint-tsgolint-7.0.2003.tgz";
  };
  "oxlint@1.87.0" = fetchurl {
    url = "https://npm.flatt.tech/oxlint/-/oxlint-1.87.0.tgz";
    hash = "sha512-drxVlaW7Oqq7wSy1CN25znRu00aRq8n57Q2wniJRxCmtYVz07ufCm7EVDPQFZURrTgQIjzKrVEHAD/HcvJXObg==";
    name = "oxlint-1.87.0.tgz";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://npm.flatt.tech/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
    name = "pathe-2.0.3.tgz";
  };
  "picocolors@1.1.1" = fetchurl {
    url = "https://npm.flatt.tech/picocolors/-/picocolors-1.1.1.tgz";
    hash = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
    name = "picocolors-1.1.1.tgz";
  };
  "picomatch@4.0.7" = fetchurl {
    url = "https://npm.flatt.tech/picomatch/-/picomatch-4.0.7.tgz";
    hash = "sha512-qcJu88Q2IWqJsDD529JKMdwGm/dvInW4HvQnRwiH9JtihJvzGOscDtHE3x1pBKeUOTysQ8kVmLnJ2kJu7yhcGA==";
    name = "picomatch-4.0.7.tgz";
  };
  "pngjs@7.0.0" = fetchurl {
    url = "https://npm.flatt.tech/pngjs/-/pngjs-7.0.0.tgz";
    hash = "sha512-LKWqWJRhstyYo9pGvgor/ivk2w94eSjE3RGVuzLGlr3NmD8bf7RcYGze1mNdEHRP6TRP6rMuDHk5t44hnTRyow==";
    name = "pngjs-7.0.0.tgz";
  };
  "postcss@8.5.28" = fetchurl {
    url = "https://npm.flatt.tech/postcss/-/postcss-8.5.28.tgz";
    hash = "sha512-RRuzqDtt5Y9h3quz5hWhK+TPnsmVs6WwSU6LkJMeY4HstUEDuYTG8UJSdawMRzmzAtV+KEoG8N3Qg2qLy5vM/A==";
    name = "postcss-8.5.28.tgz";
  };
  "pretty-format@27.5.1" = fetchurl {
    url = "https://npm.flatt.tech/pretty-format/-/pretty-format-27.5.1.tgz";
    hash = "sha512-Qb1gy5OrP5+zDf2Bvnzdl3jsTf1qXVMazbvCoKhtKqVs4/YK4ozX4gKQJJVyNe+cajNPn0KoC0MC3FUmaHWEmQ==";
    name = "pretty-format-27.5.1.tgz";
  };
  "react-is@17.0.2" = fetchurl {
    url = "https://npm.flatt.tech/react-is/-/react-is-17.0.2.tgz";
    hash = "sha512-w2GsyukL62IJnlaff/nRegPQR94C/XXamvMWmSHRJ4y7Ts/4ocGRmTHvOs8PSE6pB3dWOrD/nueuU5sduBsQ4w==";
    name = "react-is-17.0.2.tgz";
  };
  "rolldown@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/rolldown/-/rolldown-1.2.8.tgz";
    hash = "sha512-Z67nTmhZe7anqnM/EjI392w5i/ANUinjip7QYsOyN37oayduxt3ksdX0hf5OOamkAd53BiIHfbfSzfUmzKFQqQ==";
    name = "rolldown-1.2.8.tgz";
  };
  "sirv@3.0.2" = fetchurl {
    url = "https://npm.flatt.tech/sirv/-/sirv-3.0.2.tgz";
    hash = "sha512-2wcC/oGxHis/BoHkkPwldgiPSYcpZK3JU28WoMVv55yHJgcZ8rlXvuG9iZggz+sU1d4bRgIGASwyWqjxu3FM0g==";
    name = "sirv-3.0.2.tgz";
  };
  "source-map-js@1.2.1" = fetchurl {
    url = "https://npm.flatt.tech/source-map-js/-/source-map-js-1.2.1.tgz";
    hash = "sha512-UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
    name = "source-map-js-1.2.1.tgz";
  };
  "std-env@4.2.0" = fetchurl {
    url = "https://npm.flatt.tech/std-env/-/std-env-4.2.0.tgz";
    hash = "sha512-oCUKSupKTHX53EyjDtuZQ64pjLJ6yYCtpmEw0goYxtjG9KpbRe8KAsl2tBUGU9DyMcJ0RwJ8GqJAFzMXcXW1Rw==";
    name = "std-env-4.2.0.tgz";
  };
  "tinybench@6.2.1" = fetchurl {
    url = "https://npm.flatt.tech/tinybench/-/tinybench-6.2.1.tgz";
    hash = "sha512-IAbQaPJIIdhVxi0mqy9lez1wEwje0UQf9F1vwtbelEG5Nbgn0nPOxCvU+mNeNS9gyJTAhrHp74CbUaSynQpZcQ==";
    name = "tinybench-6.2.1.tgz";
  };
  "tinyexec@1.3.1" = fetchurl {
    url = "https://npm.flatt.tech/tinyexec/-/tinyexec-1.3.1.tgz";
    hash = "sha512-GCvB3aoys96IuDFBMcTB46JOR6mdMtAToqwiW8JlWhsoh1mhHi/xn9ss/Dg7N555GiJyEt2qzoG/NHCwM6h1EA==";
    name = "tinyexec-1.3.1.tgz";
  };
  "tinyglobby@0.2.17" = fetchurl {
    url = "https://npm.flatt.tech/tinyglobby/-/tinyglobby-0.2.17.tgz";
    hash = "sha512-wXR/dYpcqKmfWpEdZjiKJOwCNFndD0DMnrW/cYjVGttEkBfVgcLFHoNrlj47mjOVic9yyNu65alsgF4NQyTa2g==";
    name = "tinyglobby-0.2.17.tgz";
  };
  "tinypool@2.2.0" = fetchurl {
    url = "https://npm.flatt.tech/tinypool/-/tinypool-2.2.0.tgz";
    hash = "sha512-jBrmx4lYmaC9k/mgPbylxs7kBUxHtD8256up+HjLaDFfXScKJQyil+SWXSvhAtT7XHo+yTVlpB81PGmHP8oLSQ==";
    name = "tinypool-2.2.0.tgz";
  };
  "tinyrainbow@3.1.1" = fetchurl {
    url = "https://npm.flatt.tech/tinyrainbow/-/tinyrainbow-3.1.1.tgz";
    hash = "sha512-yau8yJdTt989Mm0Bd/236QnzEiPf2xLLTqUZRUJOo/3CB078LSwzei343DgtJVmfJKJE3TMINY1u42SQsP6mXw==";
    name = "tinyrainbow-3.1.1.tgz";
  };
  "totalist@3.0.1" = fetchurl {
    url = "https://npm.flatt.tech/totalist/-/totalist-3.0.1.tgz";
    hash = "sha512-sf4i37nQ2LBx4m3wB74y+ubopq6W/dIzXg0FDGjsYnZHVa1Da8FH853wlL2gtUhg+xJXjfk3kUZS3BRoQeoQBQ==";
    name = "totalist-3.0.1.tgz";
  };
  "typescript@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/typescript/-/typescript-7.0.2.tgz";
    hash = "sha512-8FYau96o3NKOhbjKi/qNvG/W5jhzxkbdm5sj9AbZ/5T5sWqn3hJgLfGx27sRKZWTvyzCP8dLRBTf5tBTSRVUNA==";
    name = "typescript-7.0.2.tgz";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://npm.flatt.tech/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
    name = "undici-types-7.18.2.tgz";
  };
  "vite-plus@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/vite-plus/-/vite-plus-1.1.0.tgz";
    hash = "sha512-khkRlY70qqbBV0QmF9QKXSrhxIRYftb1H05AJMowMoq7iouchmAoXYeReZ8pKKMOadqrWVxFa3S9BA2m7w59iA==";
    name = "vite-plus-1.1.0.tgz";
  };
  "vite@8.3.0" = fetchurl {
    url = "https://npm.flatt.tech/vite/-/vite-8.3.0.tgz";
    hash = "sha512-lhZBVvEHefgE+HQZC9O7EBJgCU/nVzFNl7vkS4RE0APtWLP02/8QVIkQtzBxPquh7lq5/78NHipTj7ODQ6XuyQ==";
    name = "vite-8.3.0.tgz";
  };
  "vitest@5.0.3" = fetchurl {
    url = "https://npm.flatt.tech/vitest/-/vitest-5.0.3.tgz";
    hash = "sha512-xMw97S3rjdtj5dkVat7jCsqWBpvchs3RlpQctUqwJD0KkERk40vz2fJ77lDwW/Vzh/pk18eItYAzkodhSes3jQ==";
    name = "vitest-5.0.3.tgz";
  };
  "why-is-node-running@3.2.1" = fetchurl {
    url = "https://registry.npmjs.org/why-is-node-running/-/why-is-node-running-3.2.1.tgz";
    hash = "sha512-Tb2FUhB4vUsGQlfSquQLYkApkuPAFQXGFzxWKHHumVz2dK+X1RUm/HnID4+TfIGYJ1kTcwOaCk/buYCEJr6YjQ==";
  };
  "ws@8.21.3" = fetchurl {
    url = "https://npm.flatt.tech/ws/-/ws-8.21.3.tgz";
    hash = "sha512-201TZ/kPWxoPr/OKWjquZR1SWKXcvxdH+e1xrx89b3YbmzLMFCLfnaG1HFIgWzJOEWZ7MvpK++odZufgYR50Rw==";
    name = "ws-8.21.3.tgz";
  };
  "yuku-ast@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/yuku-ast/-/yuku-ast-0.9.5.tgz";
    hash = "sha512-Q8qW8WwQnN5Cm0ZZivdRIfv0sRLTjUq0YumXJkw8CYN1aCdICH9rk4C47/4n6kA5EqDtlj+F608twoTSV2MwdQ==";
    name = "yuku-ast-0.9.5.tgz";
  };
  "yuku-codegen@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/yuku-codegen/-/yuku-codegen-0.9.5.tgz";
    hash = "sha512-zGUVyDpSK4b6c9B0yyxi2P0wujn1XZTbG9dCb7d6gyAoP63EMgyLzUwPUvwxPG5jgYqhlI7w+S3oCyapqGr4PA==";
    name = "yuku-codegen-0.9.5.tgz";
  };
  "yuku-parser@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/yuku-parser/-/yuku-parser-0.9.5.tgz";
    hash = "sha512-IBnAdNVMswWbJcM7woPluOudectJzFjJ1N8jVRxP9Uq4CIv5hZdBIcdmtRbFDYF/Ph2j2gVup4YJ4N9mh0jYFA==";
    name = "yuku-parser-0.9.5.tgz";
  };
}