# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@babel/code-frame@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/code-frame/-/code-frame-7.29.7.tgz";
    hash = "sha512-Aup7aUOfpbAUg2ROOJN6Iw5f9DMBlzu0mIkm/malLQFN/YQgO48wCj0Kxa3sEHJvPVFg7siR+qRInwXd2qhQKw==";
    name = "code-frame-7.29.7.tgz";
  };
  "@babel/helper-validator-identifier@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/helper-validator-identifier/-/helper-validator-identifier-7.29.7.tgz";
    hash = "sha512-qehxGkRj55h/ff8EMaJ+cYhyaKlHIxqYDn682wQD7RNp9UujOQsHog2uS0r2vzr4pW+sXf90NeeayjcNaX3fFg==";
    name = "helper-validator-identifier-7.29.7.tgz";
  };
  "@babel/runtime@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/runtime/-/runtime-7.29.7.tgz";
    hash = "sha512-Nq8OhGWiZIZGV6hLHoyAKLLcJihP/xFeBMGJoUrxTX2psI8dCifzLhZISFb+VWS3wFMRDmCGw5R+dOySCqPLhw==";
    name = "runtime-7.29.7.tgz";
  };
  "@blazediff/core@1.9.1" = fetchurl {
    url = "https://npm.flatt.tech/@blazediff/core/-/core-1.9.1.tgz";
    hash = "sha512-ehg3jIkYKulZh+8om/O25vkvSsXXwC+skXmyA87FFx6A/45eqOkZsBltMw/TVteb0mloiGT8oGRTcjRAz66zaA==";
    name = "core-1.9.1.tgz";
  };
  "@jridgewell/sourcemap-codec@1.6.0" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.6.0.tgz";
    hash = "sha512-T7jf+5zgsZHwNJ4lvQ7/aezbyk0nNX+zJVWpmHA7VYsEx7a7qr5Rg5IbtJFqkgze5Y2sruq1RUY8Q837Od7iFw==";
    name = "sourcemap-codec-1.6.0.tgz";
  };
  "@oxc-project/runtime@0.146.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/runtime/-/runtime-0.146.0.tgz";
    hash = "sha512-lbXHIpZ1MmK6zuw5txlMdIZ2waLVUIU5Gnm3sEuwJOiqDfQfbtjeHscatmeBoxbv8+If9LFM6PGh/3DcDWYIYw==";
    name = "runtime-0.146.0.tgz";
  };
  "@oxc-project/types@0.146.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/types/-/types-0.146.0.tgz";
    hash = "sha512-XC0QsnnhVe7sLIWmYmdPw7x5P0h4W8vUU3Nv1ySgWXtvCz8NizoAEpGXA0sOYoJQV2Rl13LgURAHQ5cI5ILCSA==";
    name = "types-0.146.0.tgz";
  };
  "@oxc-project/types@0.149.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/types/-/types-0.149.0.tgz";
    hash = "sha512-Efcc+iF0j3Bf67YjEqIqWXbX5XddXoK/Mw4K1/JuXwRCZ8N16VR7iT23nlCc9XrveFVh/E5Rqs2StT0V8v9LdA==";
    name = "types-0.149.0.tgz";
  };
  "@oxfmt/binding-android-arm-eabi@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-android-arm-eabi/-/binding-android-arm-eabi-0.64.0.tgz";
    hash = "sha512-o6uzh/jTOQeAY5TdkAeXdqv7MBRcPxiRA08zrcBtkKj5cSu/FMu0Hl7Q6Fi1KCKyCWZ6lJVjBzdsJvsKltUsGQ==";
    name = "binding-android-arm-eabi-0.64.0.tgz";
  };
  "@oxfmt/binding-android-arm64@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-android-arm64/-/binding-android-arm64-0.64.0.tgz";
    hash = "sha512-jRGSUeeP7p3Gynw2YaCVtjBIA6ZxY6bEB/ES5i54OhqmRTyuVg7ZgstEtzgq6GOAJd+2QZ5pvf+bFfmW5Mp9cw==";
    name = "binding-android-arm64-0.64.0.tgz";
  };
  "@oxfmt/binding-darwin-arm64@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-darwin-arm64/-/binding-darwin-arm64-0.64.0.tgz";
    hash = "sha512-JINwtU2lW7nOFSqi+H2qplipNUqah9Gc1jgGmB82kTD4UnZrZIVxCJ9qEmFiKfjNq27gYLFhrUb0to86aCwMjw==";
    name = "binding-darwin-arm64-0.64.0.tgz";
  };
  "@oxfmt/binding-darwin-x64@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-darwin-x64/-/binding-darwin-x64-0.64.0.tgz";
    hash = "sha512-gCmuswrgrOSajV4HCRFkVCGIruPq8bjYuPYgSE2WQB3mD6XrdyZ3JMSRZCkQ8zCxOyGWriBo6QoZ5nmMHQ1BfA==";
    name = "binding-darwin-x64-0.64.0.tgz";
  };
  "@oxfmt/binding-freebsd-x64@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-freebsd-x64/-/binding-freebsd-x64-0.64.0.tgz";
    hash = "sha512-Ab8g7a38pT0MMImjh7anRSTve6buWBIlcXIFBYa5xl4s6UxEgKSc2xOOhbGtLwvXnEi2PsEDGoJh3oUU7xkehQ==";
    name = "binding-freebsd-x64-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-arm-gnueabihf@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-0.64.0.tgz";
    hash = "sha512-BgvS3CoQ+Xy2deoZqEN8JVKabcCZi2RxA3yant8G9OAv9KuPJ9TCjHkqigzdHUVwErZxEP5d2bzLIEyKYyBDLg==";
    name = "binding-linux-arm-gnueabihf-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-arm-musleabihf@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-0.64.0.tgz";
    hash = "sha512-QXpNxwoMj0YvnceCNZadNSden3bIcnvjn/sDp/rwZhRoZoZYGpHvtPyhGsdJz9uvT9GkaMW7SsLddurU56dt8w==";
    name = "binding-linux-arm-musleabihf-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-arm64-gnu@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.64.0.tgz";
    hash = "sha512-BBgH3I1ppDsI5pZ4Pdhw0ceYxwVCfbU/bZEBCeZ6caRS9x0ZabErxubP7riGUn11PXZBhe8DYdjkDKP1FlVQ5w==";
    name = "binding-linux-arm64-gnu-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-arm64-musl@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.64.0.tgz";
    hash = "sha512-v19HSjC/BGXdt26qEvKZtwAHgGmQ2Agcap2kQP+KIqoRZqivVzYth3ui2dJA1i+6/fjpjga85lIOaJJjQ/bOOw==";
    name = "binding-linux-arm64-musl-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-ppc64-gnu@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-0.64.0.tgz";
    hash = "sha512-PElLnOo4xFTBZrxPhgTIj0eHqZXwEBQoNWtb7facUV170T0B0FRET0iNbb3LUeLWTybkUW+vsdyv4ihOdyXGyw==";
    name = "binding-linux-ppc64-gnu-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-riscv64-gnu@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-0.64.0.tgz";
    hash = "sha512-Qzsg15n4F5CH+MorcRW4MkAEMiLzXmeG+DiDSbP/bBTqCmWOH3K9DHryNrve+JHlV0txS+B6Z9P5Xz+cmWeL+g==";
    name = "binding-linux-riscv64-gnu-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-riscv64-musl@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-0.64.0.tgz";
    hash = "sha512-/GZ358wnQ/Ez4UVnCcZIi56JkY0sOdZ+B108pqXKqZz3jLS59F4KEAB1Qv3fRlObrFEk+3L2vUQ/xoPx+3vjXw==";
    name = "binding-linux-riscv64-musl-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-s390x-gnu@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-0.64.0.tgz";
    hash = "sha512-/C9We3DXegowfLXtVCYHeNiU9azwCDr5cQkEtCVlc74vyn+lLQSPApJ1CZmxAduqeq/Oi3gQ+IVptyhCaTMtkQ==";
    name = "binding-linux-s390x-gnu-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-x64-gnu@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.64.0.tgz";
    hash = "sha512-91KM2CeRWscIEHlj1NsW2WSnzGeq1Ehq+39bfDowTdkn+fcvK/x4Y1RcyqT7glyBjZio0ldkeCG6Usj3v7ASog==";
    name = "binding-linux-x64-gnu-0.64.0.tgz";
  };
  "@oxfmt/binding-linux-x64-musl@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-x64-musl/-/binding-linux-x64-musl-0.64.0.tgz";
    hash = "sha512-gw7uEk9I+7zoT1EYLra1eWArIzNcz8e3jkv+Noo2+o2T7wPvsNSQbfoa4DSfZlvn1i6mJ05RiZ4/omaXPDNhQg==";
    name = "binding-linux-x64-musl-0.64.0.tgz";
  };
  "@oxfmt/binding-openharmony-arm64@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-openharmony-arm64/-/binding-openharmony-arm64-0.64.0.tgz";
    hash = "sha512-HYHFf616FHSPSO07c09mjmXBfQ73wIVM3m0txOiooa5XZkGoxFd6B14PVj0LB0DXIqJ6wAO/dDR/NX/5UUaqnw==";
    name = "binding-openharmony-arm64-0.64.0.tgz";
  };
  "@oxfmt/binding-win32-arm64-msvc@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-0.64.0.tgz";
    hash = "sha512-uQjFp081IZSWD6VAofX2iO2z01awAdHmfC+NrieWIPKrT2hZKQDyq/U18M7ifC0sm0Wz8aHY/p6+FDYIzs/CrQ==";
    name = "binding-win32-arm64-msvc-0.64.0.tgz";
  };
  "@oxfmt/binding-win32-ia32-msvc@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-0.64.0.tgz";
    hash = "sha512-lNM6byTAQ881jugzFu8juJTbNRgsUTlswMA6pJmwi1XDvmIqnnb49lcUAs5gz94fCJLrVN+/X3s3jOKqx23WIQ==";
    name = "binding-win32-ia32-msvc-0.64.0.tgz";
  };
  "@oxfmt/binding-win32-x64-msvc@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-x64-msvc/-/binding-win32-x64-msvc-0.64.0.tgz";
    hash = "sha512-BtmbtL/QjMtF1a6C3CqoDluH2IfB6fJt62E+B9RFfUPtFk4Iz9PFS6+y/SzzOvSxc7aUk2Kphwg7Dh8lMbwu6g==";
    name = "binding-win32-x64-msvc-0.64.0.tgz";
  };
  "@oxlint-tsgolint/darwin-arm64@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/darwin-arm64/-/darwin-arm64-7.0.2001.tgz";
    hash = "sha512-CUJEdbSZ54+Xy9OXqOhWLTKZKV0BBiV7C2i/ygyVmXtkUNXx5YCzN8DpSSshTAKktoL7S+tnQ/ftFG/i7X896w==";
    name = "darwin-arm64-7.0.2001.tgz";
  };
  "@oxlint-tsgolint/darwin-x64@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/darwin-x64/-/darwin-x64-7.0.2001.tgz";
    hash = "sha512-pXfBb5BqONCcgrXQNUZWXgiYmRSWJzd97S8i41VVOh6ut0tyo+cJ5FKFpczDHxiVNfj/3e7c9B4MtztNdpIVCw==";
    name = "darwin-x64-7.0.2001.tgz";
  };
  "@oxlint-tsgolint/linux-arm64@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/linux-arm64/-/linux-arm64-7.0.2001.tgz";
    hash = "sha512-roP7zujb/QDPzDwEKsFFpzNHHy91/Y7oX9vQXk78ekyZtcQj1QXDIMH33gjDdHBfRl4K9pZ36xhRgrP4Zr+R8A==";
    name = "linux-arm64-7.0.2001.tgz";
  };
  "@oxlint-tsgolint/linux-x64@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/linux-x64/-/linux-x64-7.0.2001.tgz";
    hash = "sha512-UDezNqdECVmngu2TPnjaS1YoAmcTaBoI5lV9vk3VahBxoi+I5r9k3iJTT7qZoYWOXTD/7T7bNcwRgrocR6BscQ==";
    name = "linux-x64-7.0.2001.tgz";
  };
  "@oxlint-tsgolint/win32-arm64@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/win32-arm64/-/win32-arm64-7.0.2001.tgz";
    hash = "sha512-uJZhqB6pdXLuN+AD1F5082byyQti/NPmJA77GtcFlmT2HzRelqbNls3SaIqxpjdFgvSBF9g0yOKGBkGFg7kX8Q==";
    name = "win32-arm64-7.0.2001.tgz";
  };
  "@oxlint-tsgolint/win32-x64@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/win32-x64/-/win32-x64-7.0.2001.tgz";
    hash = "sha512-FkDRm8hx9OwzGQqyWG1tO5QrTLRApff9DzSgpz9QZau37BR8d1VYKOxMLGf6shPZntJFoTwIIJYT68VndYDCog==";
    name = "win32-x64-7.0.2001.tgz";
  };
  "@oxlint/binding-android-arm-eabi@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-android-arm-eabi/-/binding-android-arm-eabi-1.79.0.tgz";
    hash = "sha512-TebFaaMklO/RXzTv7PucaCq9l3X6D1gA+C8H6K4njtjFOV+zWE9MKLpulcJZN9bzytbUbQIY0mZuz12nQ5Kv4Q==";
    name = "binding-android-arm-eabi-1.79.0.tgz";
  };
  "@oxlint/binding-android-arm64@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-android-arm64/-/binding-android-arm64-1.79.0.tgz";
    hash = "sha512-KqqnOtAVgNsPPF0YSodkFZA1O80jcKoCZCTu3bgsszxA+MrMP9TLzfXitKjEj1FmrPprKDMdRDMmY3weESO9sg==";
    name = "binding-android-arm64-1.79.0.tgz";
  };
  "@oxlint/binding-darwin-arm64@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-darwin-arm64/-/binding-darwin-arm64-1.79.0.tgz";
    hash = "sha512-BVC2nsMzqQzRDPc5RhixkZ+m1p7iH4bxRRvqkbwDXX0PlQKm1BPy8J8cRjnAFafOq2QzI+BfO3vE8w2GZ3CBag==";
    name = "binding-darwin-arm64-1.79.0.tgz";
  };
  "@oxlint/binding-darwin-x64@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-darwin-x64/-/binding-darwin-x64-1.79.0.tgz";
    hash = "sha512-p6Lm+snmhGuLKL1+CpCV8L6ijkE/qJzK2H2jG9+eKJT0n31RbY4FLsdhexekgP3bLpw4Kgde+9DZuDZQ4yIInA==";
    name = "binding-darwin-x64-1.79.0.tgz";
  };
  "@oxlint/binding-freebsd-x64@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-freebsd-x64/-/binding-freebsd-x64-1.79.0.tgz";
    hash = "sha512-qDMm0dXZnoHyRqSL4N4xUq82T4sqK5cbKSjvd/dF/YbMUXc2R1wEPf+vmA5S0qUmi0nwXfNbjXBtZaIqzQLIMg==";
    name = "binding-freebsd-x64-1.79.0.tgz";
  };
  "@oxlint/binding-linux-arm-gnueabihf@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.79.0.tgz";
    hash = "sha512-2od7s0nuKPzqyUZAWk9KkCyGg7eI9dwFPZg+20lB15fKFkVZ0c9ZFxqPfiBAyDTlTkh9stPI0t+JlPCqMbItVA==";
    name = "binding-linux-arm-gnueabihf-1.79.0.tgz";
  };
  "@oxlint/binding-linux-arm-musleabihf@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-1.79.0.tgz";
    hash = "sha512-ZOQUjkzDnvlhSE3+tWC3YXx94MMl+sYMlwH+u1+YGApGHOJP/YAc8ZBRFOXZ6eOBmxtXAWuS/fBcdZr8qqNO1A==";
    name = "binding-linux-arm-musleabihf-1.79.0.tgz";
  };
  "@oxlint/binding-linux-arm64-gnu@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.79.0.tgz";
    hash = "sha512-lu158FR4nGqGeRS3BQvtG85wRgU/Fy4MD5Cxp1hzJXizGiLo6u2742wJSCDKh8cFcZntvX7fcxlq4mMmfryH1g==";
    name = "binding-linux-arm64-gnu-1.79.0.tgz";
  };
  "@oxlint/binding-linux-arm64-musl@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.79.0.tgz";
    hash = "sha512-mbpKQeE2aflTjddaHK7MP8KP/OFbUM++lt5M635ENM8IyIdK0jm2t9pb+2v9mVVIvhF6TqA4l7F79Pll1mi+uw==";
    name = "binding-linux-arm64-musl-1.79.0.tgz";
  };
  "@oxlint/binding-linux-ppc64-gnu@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.79.0.tgz";
    hash = "sha512-WpGNua7gaxaHnpSDeog2ji8IDHn/QLPl9LPzwkR/FvVv58vT5BcXjRXnU+wbu3N75cpeha8CdC7ho/U2OIsB4g==";
    name = "binding-linux-ppc64-gnu-1.79.0.tgz";
  };
  "@oxlint/binding-linux-riscv64-gnu@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-1.79.0.tgz";
    hash = "sha512-tK1E93A5LVzISg4ngpKJnfTs7EqtIUceGI7MQ4GyDjJiLi8wPCkEyKlj2xkyKWZ1yzkDJyLHTBJ5/iFWRdnJvg==";
    name = "binding-linux-riscv64-gnu-1.79.0.tgz";
  };
  "@oxlint/binding-linux-riscv64-musl@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-1.79.0.tgz";
    hash = "sha512-qhQvUIrngXivA2A9pQ+xPCychztn/5qUv7yS3gDwXv3w7Rag+eTeeXWmRyx+t7XsW5x6LuY/8AsTq36UgFIblg==";
    name = "binding-linux-riscv64-musl-1.79.0.tgz";
  };
  "@oxlint/binding-linux-s390x-gnu@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.79.0.tgz";
    hash = "sha512-sv6AaVgU/eE6u+6WFiQVDcPPwTxP6IJMSB9k701W2r/r6Tx465e8vPvVyRxquNH4Vy6KwRNu90mVbxXJN8+5gg==";
    name = "binding-linux-s390x-gnu-1.79.0.tgz";
  };
  "@oxlint/binding-linux-x64-gnu@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.79.0.tgz";
    hash = "sha512-iFZL02deziHslb3jEX9KdqlAkYoo4fGyotchKDzdfK1f5mxlIBeiQeHhvK3iFpuEJSB4ma/qeFn9oxPiwnhUPQ==";
    name = "binding-linux-x64-gnu-1.79.0.tgz";
  };
  "@oxlint/binding-linux-x64-musl@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-x64-musl/-/binding-linux-x64-musl-1.79.0.tgz";
    hash = "sha512-3DtZR2raqObnh7wXZoFYFd0Fw7skBvcb3f7A+/lkEiDuh8hrE6vv9b/62Qxao1a9/OeHLw/FcXlXzgsW9wTRFg==";
    name = "binding-linux-x64-musl-1.79.0.tgz";
  };
  "@oxlint/binding-openharmony-arm64@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-openharmony-arm64/-/binding-openharmony-arm64-1.79.0.tgz";
    hash = "sha512-Oatt4GuA1WJkqzk2ozx4HrWROOi7opV3AKDw/U8qDIqeTqzsjn5K2x3REJMNjU3/KU/Bkq96Zi3CknaiDTaC/Q==";
    name = "binding-openharmony-arm64-1.79.0.tgz";
  };
  "@oxlint/binding-win32-arm64-msvc@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.79.0.tgz";
    hash = "sha512-NAgZr9Qp8nIA9rpo0JEvwiabTF/2UVqBNnupBG9X4kxXcQoScJUTi+qHhvabb9s/thgj5wQ4XcIaJvb+ZMgoKw==";
    name = "binding-win32-arm64-msvc-1.79.0.tgz";
  };
  "@oxlint/binding-win32-ia32-msvc@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-1.79.0.tgz";
    hash = "sha512-+KyXjIvcpaXmWW/j9NNY5yWjrIVxaX18VyIheQy3jwc2GSYgpCr7MGI/HxIGQ/shAL5IWEKbhsqoMpAO5Stiog==";
    name = "binding-win32-ia32-msvc-1.79.0.tgz";
  };
  "@oxlint/binding-win32-x64-msvc@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.79.0.tgz";
    hash = "sha512-mEelcCMMBS57sIXh2veGMNy+pQwuGtcMxHxGIZWQ5Ba9pJ5jCCUFOZB9E2JhBaxGsURe+WGe0zJp4RVre52gpQ==";
    name = "binding-win32-x64-msvc-1.79.0.tgz";
  };
  "@oxlint/plugins@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/plugins/-/plugins-1.79.0.tgz";
    hash = "sha512-S0uyoxakDINJ4DPgqxGlEEvrdSMeQb7Z2lKVjxoY2gwsbZbfg2Xr8Klfeo5ZeraHmmdBCELFUHkSe6KEmBpMvg==";
    name = "plugins-1.79.0.tgz";
  };
  "@polka/url@1.0.0-next.29" = fetchurl {
    url = "https://npm.flatt.tech/@polka/url/-/url-1.0.0-next.29.tgz";
    hash = "sha512-wwQAWhWSuHaag8c4q/KN/vCoeOJYshAIvMQwD4GpSb3OiZklFfvAgmj0VCBBImRpuF/aFgIRzllXlVX93Jevww==";
    name = "url-1.0.0-next.29.tgz";
  };
  "@rolldown/binding-android-arm-eabi@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-android-arm-eabi/-/binding-android-arm-eabi-1.2.8.tgz";
    hash = "sha512-tN5aztYkKCte4i5SIrrz5yK/HMjEuCqCSCJa418jOV8tZ1cBY3YF2otxB1ktPxzsLA1BeTqwapK0bfjxNvHJVw==";
    name = "binding-android-arm-eabi-1.2.8.tgz";
  };
  "@rolldown/binding-android-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-android-arm64/-/binding-android-arm64-1.2.8.tgz";
    hash = "sha512-dIYTWl9XprMUiQFoc55KUyk/oS8SKYH3zFl0LTR7RT0Xj4hgSVyuJcroH8JUu8RcpF8fTB6E0aOwCkZoYPcDSQ==";
    name = "binding-android-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-darwin-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-darwin-arm64/-/binding-darwin-arm64-1.2.8.tgz";
    hash = "sha512-PCSDQGXD2IyTEFrcgPyBM8jJuGmrbCMuoIOXdbEGVemruKACXoLQJrb+A45Z0L5t1RQkdfJprAYPkikbh7dzdA==";
    name = "binding-darwin-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-darwin-x64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-darwin-x64/-/binding-darwin-x64-1.2.8.tgz";
    hash = "sha512-Uk7lRsGhPFHVX/sAUC6D5H9Ol30dFHd6iquokll2th3LpdJ3F5CzQB+7DHn0Ri2mG+U7k2zXiPHDrwZenXhwSA==";
    name = "binding-darwin-x64-1.2.8.tgz";
  };
  "@rolldown/binding-freebsd-x64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-freebsd-x64/-/binding-freebsd-x64-1.2.8.tgz";
    hash = "sha512-DjszaTEVogPqA5bYzsEeqDCQxbcp2fexQwKcRspYji2yzR68fCf+e4fx6kBSRDwX5/brZaHw/hWS9+A/+/w9sQ==";
    name = "binding-freebsd-x64-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm-gnueabihf@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.2.8.tgz";
    hash = "sha512-zmwa7FTmdzB6aaEEuuls18H6Ap5JmJPSoPTuXixeJZV6tG40SyLkApQtz1g8ptZtiEKqj9OM0oNLPh1AgvE31Q==";
    name = "binding-linux-arm-gnueabihf-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.2.8.tgz";
    hash = "sha512-KdYQDPHwJVnbFwdTGMgxsI9SqblBlz6STGM+w1We/d5B8OWWidYH0MwkU/uA1wM5fIpO2MkOVxXrNzzuZhw9ew==";
    name = "binding-linux-arm64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm64-musl@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.2.8.tgz";
    hash = "sha512-jFJTifHnNPY+yzOoNZQfSIysrVyXzEQPhPnOUjmD1bcQGHH6s7c8cViKWar8YplQImE5N9JRqMCLrM2CdxOrZA==";
    name = "binding-linux-arm64-musl-1.2.8.tgz";
  };
  "@rolldown/binding-linux-ppc64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.2.8.tgz";
    hash = "sha512-FhiOziBDWPBjbcmRzfLyIJnaP7AVMFXT7YCXPjXxj7wKU3vx24RjrCNN/zjvVa+N2vVoHJwCoUBvsrN/DG3zIA==";
    name = "binding-linux-ppc64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-s390x-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.2.8.tgz";
    hash = "sha512-WnHfADMzOV2Y55wlx1hzzQnar/wDt/VdvWSD99r18Mz9ylNieIGOkRx3UV21h7m/eJvjySYJkO26VvGNFkwsIQ==";
    name = "binding-linux-s390x-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-x64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.2.8.tgz";
    hash = "sha512-H9tRr5ibfXFVLxbPOseVewewFpl28zcEdjRDt2FTUZU7odxP0gEv1ki4/kGmcGOh78oRwZuuQllGLZ9zTJp84g==";
    name = "binding-linux-x64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-x64-musl@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-x64-musl/-/binding-linux-x64-musl-1.2.8.tgz";
    hash = "sha512-UefiqfM3D6IVNlZ8tSGs9+Ejjud2T+oxO0IHADU45Y+lyEjD2dVFyZHbkfX0LUb5Zugo/oIv1eCO/KVYhgYJYA==";
    name = "binding-linux-x64-musl-1.2.8.tgz";
  };
  "@rolldown/binding-openharmony-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-openharmony-arm64/-/binding-openharmony-arm64-1.2.8.tgz";
    hash = "sha512-637Ke4kWSy6rp9cxQ9gMOXlxPgIw/c1beASV4M//3+9I4uwBVOOl74G+e3zyU3u19U7RkRl/HuewixZ/Z6+Rjg==";
    name = "binding-openharmony-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-win32-arm64-msvc@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.2.8.tgz";
    hash = "sha512-xWBkPOF1Q9k/Gv1nQXnVdLxKu74jXppuOM4Z3mnypVUJJJwLsMl7hNJGRAUJoG8A5MgOI1ACKM+wBFxSJzKy4A==";
    name = "binding-win32-arm64-msvc-1.2.8.tgz";
  };
  "@rolldown/binding-win32-x64-msvc@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.2.8.tgz";
    hash = "sha512-uz2ZvfgXbxqNwijjjbxrnvALwpyODDcgc1T1N8N3rf/DXKQmaFwmB4LX4yyjggpwN2obdQLb2rgirX5ffCWYng==";
    name = "binding-win32-x64-msvc-1.2.8.tgz";
  };
  "@rolldown/pluginutils@1.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/pluginutils/-/pluginutils-1.0.1.tgz";
    hash = "sha512-2j9bGt5Jh8hj+vPtgzPtl72j0yRxHAyumoo6TNfAjsLB04UtpSvPbPcDcBMxz7n+9CYB0c1GxQFxYRg2jimqGw==";
    name = "pluginutils-1.0.1.tgz";
  };
  "@standard-schema/spec@1.1.0" = fetchurl {
    url = "https://npm.flatt.tech/@standard-schema/spec/-/spec-1.1.0.tgz";
    hash = "sha512-l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
    name = "spec-1.1.0.tgz";
  };
  "@testing-library/dom@10.4.1" = fetchurl {
    url = "https://npm.flatt.tech/@testing-library/dom/-/dom-10.4.1.tgz";
    hash = "sha512-o4PXJQidqJl82ckFaXUeoAW+XysPLauYI43Abki5hABd853iMhitooc6znOnczgbTYmEP6U6/y1ZyKAIsvMKGg==";
    name = "dom-10.4.1.tgz";
  };
  "@testing-library/user-event@14.6.7" = fetchurl {
    url = "https://npm.flatt.tech/@testing-library/user-event/-/user-event-14.6.7.tgz";
    hash = "sha512-MPCpX8bxe8zS+JmmTwLp8jd0dy1rAm60Te/SL8JrQM3qvQJcBOs1d7IefJMyZzqM3EWBrDn/LWDt1BCGu4ASfg==";
    name = "user-event-14.6.7.tgz";
  };
  "@types/aria-query@5.0.4" = fetchurl {
    url = "https://npm.flatt.tech/@types/aria-query/-/aria-query-5.0.4.tgz";
    hash = "sha512-rfT93uj5s0PRL7EzccGMs3brplhcrghnDoV26NqKhCAS1hVo+WdNsPvE/yb6ilfr5hi2MEk6d5EWJTKdxg8jVw==";
    name = "aria-query-5.0.4.tgz";
  };
  "@types/chai@5.2.3" = fetchurl {
    url = "https://npm.flatt.tech/@types/chai/-/chai-5.2.3.tgz";
    hash = "sha512-Mw558oeA9fFbv65/y4mHtXDs9bPnFMZAL/jxdPFUpOHHIXX91mcgEHbS5Lahr+pwZFR8A7GQleRWeI6cGFC2UA==";
    name = "chai-5.2.3.tgz";
  };
  "@types/deep-eql@4.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@types/deep-eql/-/deep-eql-4.0.2.tgz";
    hash = "sha512-c9h9dVVMigMPc4bwTvC5dxqtqJZwQPePsWjPlpSOnojbor6pGqdk541lfA7AqFQr5pB1BRdq0juY9db81BwyFw==";
    name = "deep-eql-4.0.2.tgz";
  };
  "@types/estree@1.0.9" = fetchurl {
    url = "https://npm.flatt.tech/@types/estree/-/estree-1.0.9.tgz";
    hash = "sha512-GhdPgy1el4/ImP05X05Uw4cw2/M93BCUmnEvWZNStlCzEKME4Fkk+YpoA5OiHNQmoS7Cafb8Xa3Pya8m1Qrzeg==";
    name = "estree-1.0.9.tgz";
  };
  "@types/node@24.13.4" = fetchurl {
    url = "https://npm.flatt.tech/@types/node/-/node-24.13.4.tgz";
    hash = "sha512-YJ7EqCstVTzIr0fMr7qul/977en+pQHrfmuKIo6Zr9i75Be21dr3MovcfvGtyvi2HAUrRerWps5sMO9I7WaxDw==";
    name = "node-24.13.4.tgz";
  };
  "@typescript/typescript-aix-ppc64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-aix-ppc64/-/typescript-aix-ppc64-7.0.2.tgz";
    hash = "sha512-MTKKkWB7p/0E9xi1d1tHtZ5PiLkGEMIq88pK2CubZjOsLtYTLqhgIgi6zepFa+9GHZ6h05NMCkQxGKiPXMxXtQ==";
    name = "typescript-aix-ppc64-7.0.2.tgz";
  };
  "@typescript/typescript-darwin-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-darwin-arm64/-/typescript-darwin-arm64-7.0.2.tgz";
    hash = "sha512-gowzar9MwS/aRWp6f3a4KUqzRjAZjOsmGNCM6LcTgXum+dBfgsBVMN+AgvOCCbguXyick6LJhpBszxMebJ8syA==";
    name = "typescript-darwin-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-darwin-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-darwin-x64/-/typescript-darwin-x64-7.0.2.tgz";
    hash = "sha512-SZ9xZInqApNlNGc9s0W1VSsktYSOe9cFqNOIqmN1Gs8SmkjKZYFt017G4VwPxASInODuAdbTW7sXiFUf893RgA==";
    name = "typescript-darwin-x64-7.0.2.tgz";
  };
  "@typescript/typescript-freebsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-freebsd-arm64/-/typescript-freebsd-arm64-7.0.2.tgz";
    hash = "sha512-W5NH4y/J0plIIS5b2xvTEkU7JFxyqdMAOgf+Ilhl0vHQXKO5dZoxd+C/jEtq56c4F3wk71RB4BMRQ2XdI+bwYQ==";
    name = "typescript-freebsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-freebsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-freebsd-x64/-/typescript-freebsd-x64-7.0.2.tgz";
    hash = "sha512-UMGDx5sTpzNw3WiPebH7l90IWfJggEd+egHt/q6p7/Cm3zqoV7VxkGXt+3DxPIw8CcmvAB0j3sVVfbhX+M4Tpw==";
    name = "typescript-freebsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-arm64/-/typescript-linux-arm64-7.0.2.tgz";
    hash = "sha512-Qh4eU4/y3yDjnfjjyPYihMj5/ODIlmt+Bzu17OI+fiSRDW57QmU5SiN63exPRNJPKUzcc1INa1NXdrJ+MqHjUQ==";
    name = "typescript-linux-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-arm@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-arm/-/typescript-linux-arm-7.0.2.tgz";
    hash = "sha512-gffT3xPz9sR7j/YJExkyPntrI0P2EP9XbOyWzth2/Gs0RstK+90RBcO0ncXoXy/beYll1SXw846Nf2zdnEz0QQ==";
    name = "typescript-linux-arm-7.0.2.tgz";
  };
  "@typescript/typescript-linux-loong64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-loong64/-/typescript-linux-loong64-7.0.2.tgz";
    hash = "sha512-uEHck9i8hoAzXPiYRib1O7miOnz23SxIeVl6F4LXox+qov1K35jHcEW6VHKvZI+pyvl7fZEP4MCU5LYvIq1GuQ==";
    name = "typescript-linux-loong64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-mips64el@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-mips64el/-/typescript-linux-mips64el-7.0.2.tgz";
    hash = "sha512-R4KvAMnE43W5Qeqb0Ly56O3mWMWIAgsMyz36DCaycd5nbg/9kzm0liw3JocfRqyJY0KPmzFjbswozXyW0DnIYA==";
    name = "typescript-linux-mips64el-7.0.2.tgz";
  };
  "@typescript/typescript-linux-ppc64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-ppc64/-/typescript-linux-ppc64-7.0.2.tgz";
    hash = "sha512-DORx5b3sd/4S7eayxm4FQv+A7CrkUIGRaHiwI8oiHTAI1fAPWhF4J0vAlkC8biAlHSVVwxMQ3tjZ2/DVbnQiiA==";
    name = "typescript-linux-ppc64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-riscv64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-riscv64/-/typescript-linux-riscv64-7.0.2.tgz";
    hash = "sha512-wf0jqEDOjrPRnKwYRyyJDRo11KMbvMFrU+q4zqKyChODBzvlkbhNQfKvLxQCcwTpdDaXSHZTVuh0JoCrKCUMHQ==";
    name = "typescript-linux-riscv64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-s390x@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-s390x/-/typescript-linux-s390x-7.0.2.tgz";
    hash = "sha512-IkwJc3L7yhytWd/ewjyxNDfOmswCm9GWMJT/ue/dU4aZNbwZeYAetq42VyLmsmSjvoX7z74X6ZaYCtzAr0EuGw==";
    name = "typescript-linux-s390x-7.0.2.tgz";
  };
  "@typescript/typescript-linux-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-x64/-/typescript-linux-x64-7.0.2.tgz";
    hash = "sha512-EYdf2cNg7rgCWJnxCdJ+F3V39O8ihb37eHAu1LK8oAFizgTQbPOK7zHHXbPt8rX24COqODXeI3sIf0fCXG7H/A==";
    name = "typescript-linux-x64-7.0.2.tgz";
  };
  "@typescript/typescript-netbsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-netbsd-arm64/-/typescript-netbsd-arm64-7.0.2.tgz";
    hash = "sha512-+polYF4MF04aPpO5FTkHran9yUQDSXqy5GiSDKpsll5jy3l3+g9QLhpf39T+ePtefhXLOGrLl0QIjkQP6VnelA==";
    name = "typescript-netbsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-netbsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-netbsd-x64/-/typescript-netbsd-x64-7.0.2.tgz";
    hash = "sha512-8YIT0EHM/3dq10ZOVF/A7pc/YSMtbcecct4rWtexrnSCHOPcpC2KTLXfTCR6vDpnSiY12heNb1GiN/wu+T/FyA==";
    name = "typescript-netbsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-openbsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-openbsd-arm64/-/typescript-openbsd-arm64-7.0.2.tgz";
    hash = "sha512-APT8+ClYnuYm1u9+kgGXoMj2VzWzcymwh2gNSQVySHfkRDGOTVkoWLjCmOQSaO+PoqQ57B0flRp9SA+7GnnkzQ==";
    name = "typescript-openbsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-openbsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-openbsd-x64/-/typescript-openbsd-x64-7.0.2.tgz";
    hash = "sha512-yX7s+Q0Dln0Dt9tEzZsAjXXR/+ytBM7AlglaqyeMPxQszJ1JhlJdZ6jLA+IzldHtflX81em7lDao1xXu+aRRkg==";
    name = "typescript-openbsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-sunos-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-sunos-x64/-/typescript-sunos-x64-7.0.2.tgz";
    hash = "sha512-dLJDGaLZ1D4HPQn62u1n8mBDkJREwMsAkCdkwd4Ieqw+x3TUyTsqY0YiBCtE6H6OzzgGk3iuZ3vFWRS+E8/d1g==";
    name = "typescript-sunos-x64-7.0.2.tgz";
  };
  "@typescript/typescript-win32-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-win32-arm64/-/typescript-win32-arm64-7.0.2.tgz";
    hash = "sha512-Gyl1Vy6OsWesLzmq+EP0Fb7b4Nid5232AvcA2SFcdYreldpNtYFFofPjnt62y9hQy7VTaZp65ICJjuAQRaVcIQ==";
    name = "typescript-win32-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-win32-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-win32-x64/-/typescript-win32-x64-7.0.2.tgz";
    hash = "sha512-0BQ3HkAHHlKLSp1qRvf3SUhGpGsDuhB/jgFw75guyqbxJqEaS0Cw/VFO8i2nHglJUzQCRtMMR/IBAKE3ETMC4g==";
    name = "typescript-win32-x64-7.0.2.tgz";
  };
  "@vitest/browser-preview@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/browser-preview/-/browser-preview-4.1.11.tgz";
    hash = "sha512-iPKSE6Ibayey6HFgK1V1/aHgyhx7HSRk1YMi+lnBZGmlIiNV5Uc7xRkD9Su8RDylTxDECK23t7kTHdRKoqSYDQ==";
    name = "browser-preview-4.1.11.tgz";
  };
  "@vitest/browser@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/browser/-/browser-4.1.11.tgz";
    hash = "sha512-bwMovvAeuTFOK5kIFevw4VEf+1gVEICv4SYK4k3knJOxl6b1zEWud8mYKD73e1B0odAn174h1MofURy2TPWf3w==";
    name = "browser-4.1.11.tgz";
  };
  "@vitest/expect@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/expect/-/expect-4.1.11.tgz";
    hash = "sha512-VX2x5vNJXET47KAFzwERI+KRMtTTCSWTfSMKsW7JsUsXV4psq++e3DvZpuTDOpHcxytiDs6p2nhVb2tVDiiUYw==";
    name = "expect-4.1.11.tgz";
  };
  "@vitest/mocker@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/mocker/-/mocker-4.1.11.tgz";
    hash = "sha512-2XJVD55d1o5AZous5CCGKS74g/riOj9odEt2bQpCVZeblHyHdnMeFl4jl0XjU21stf4mbjUkew2eXQZt65g5CQ==";
    name = "mocker-4.1.11.tgz";
  };
  "@vitest/pretty-format@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/pretty-format/-/pretty-format-4.1.11.tgz";
    hash = "sha512-yiZzPbGTS9Sr/JpFl8zHrcIkAofNbFV6k21vIgQN/cY/oxZeXhJv5sc/MBJ5jFKWmWs+oJHw0UXLZjmf931+Vw==";
    name = "pretty-format-4.1.11.tgz";
  };
  "@vitest/runner@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/runner/-/runner-4.1.11.tgz";
    hash = "sha512-LztvUgdwMNJMIkj3hQnnxiC2Xy1zNxq928W/xhjCLaNCzqTZOudjwbQf6v9IntZGPw132i2Lq2rgTRZHD3JHNw==";
    name = "runner-4.1.11.tgz";
  };
  "@vitest/snapshot@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/snapshot/-/snapshot-4.1.11.tgz";
    hash = "sha512-pN7ikn1ON7h8ee4gIAp4AzyK+zBtJPzVbqOgu5LCEh4VaJVbPQcgYQYJIMGQPXVeJJq1fnfazis7a5pFNPahog==";
    name = "snapshot-4.1.11.tgz";
  };
  "@vitest/spy@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/spy/-/spy-4.1.11.tgz";
    hash = "sha512-apNa/prQy2qCeywhnixOHPRCgGNhvg7T4Dapfl1GahLp/R+uhBm5cPyFoNVyqsNd2h1nJxL6BqqdIjiABL60YA==";
    name = "spy-4.1.11.tgz";
  };
  "@vitest/utils@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/utils/-/utils-4.1.11.tgz";
    hash = "sha512-zTCVGpyFsGWBhllOyKlTw/vnr6D9qxsfSDyfbyZmTyjHw5N/VuvzHpHoQjm2ZJzn4RJgx5w4r7V0er69CmLgPQ==";
    name = "utils-4.1.11.tgz";
  };
  "@voidzero-dev/vite-plus-core@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-core/-/vite-plus-core-0.3.0.tgz";
    hash = "sha512-aOqoqIWaF+Q/geDU48pC2rVFEVSvLV1GGj/NdvhUiBhCZntoFNbwI+hjUeG8BMaPG67sOV6ey+/sgkdmGmKqaw==";
    name = "vite-plus-core-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-darwin-arm64@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-darwin-arm64/-/vite-plus-darwin-arm64-0.3.0.tgz";
    hash = "sha512-9ADr1egZ8T4tJOqrpQLhoDl95Y74R95+bsvjmin0gy1C0eQVhpmcNnBfb07KFNhJioJp9MMO7F7Dx4fQL5SKsw==";
    name = "vite-plus-darwin-arm64-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-darwin-x64@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-darwin-x64/-/vite-plus-darwin-x64-0.3.0.tgz";
    hash = "sha512-GegasVCwNeDOkNyvhLOuwU1+T2JkjY/Tq+SOvwphUpVcqQ6OOAUq9LlpoXviO2QL/Kq2NbMYjiAfPKVSTLUFQw==";
    name = "vite-plus-darwin-x64-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-arm64-gnu/-/vite-plus-linux-arm64-gnu-0.3.0.tgz";
    hash = "sha512-nYI3KNYXkXjRPsSdR4Lr7J2xMxfR1+TplWlG/dV37qVXWAjbyHpoAlbULjZBAVJMyXRNlcADhBrEwXe4g6s48A==";
    name = "vite-plus-linux-arm64-gnu-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-arm64-musl/-/vite-plus-linux-arm64-musl-0.3.0.tgz";
    hash = "sha512-HRlVA3AOcuGXmOdHhQ+Zv5XAaKbYF9si5rRHoOsKl0UyBo4txA3OoJfmP0WjanfLUNmu85JyO2dO1ptL4C6wgg==";
    name = "vite-plus-linux-arm64-musl-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-x64-gnu/-/vite-plus-linux-x64-gnu-0.3.0.tgz";
    hash = "sha512-9A+dFScPfwcrzF/rRR0zH8++2hOf6xtFmN/5LyzyfUywtw9MILXcC72IMcOeL6QRJwKUMsudi1rFeDE59azNvw==";
    name = "vite-plus-linux-x64-gnu-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-x64-musl@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-x64-musl/-/vite-plus-linux-x64-musl-0.3.0.tgz";
    hash = "sha512-KfIV3qaPdaOOE8JQMRHRE34FtZocl9O86XLTP6JMjDUlcx8FPgf8/fz/HFqJ8g232vM+JsgLI/YTVeXP8LkTKw==";
    name = "vite-plus-linux-x64-musl-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-win32-arm64-msvc/-/vite-plus-win32-arm64-msvc-0.3.0.tgz";
    hash = "sha512-KRhdy5K13AYx9KBfCVHRrK7zSZU+bMW9CL6gTai+UkJgAmDJi1kjdSNboZOjO8mrzUnTCrELgMI2tnstcxSTuA==";
    name = "vite-plus-win32-arm64-msvc-0.3.0.tgz";
  };
  "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-win32-x64-msvc/-/vite-plus-win32-x64-msvc-0.3.0.tgz";
    hash = "sha512-7+G+GxGmxdpQO0zjiGnkZFXKGqm0CrVduebRsJd6ccuOuxCQYPxLcoHq4WOaGrh56SrAGS7XjhnQCrXRkzKUVQ==";
    name = "vite-plus-win32-x64-msvc-0.3.0.tgz";
  };
  "@yuku-codegen/binding-darwin-arm64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-darwin-arm64/-/binding-darwin-arm64-0.5.48.tgz";
    hash = "sha512-yo96Oef12WzqnphInfz/eexVse3+kWgfGS5g2S3rFS3dcGn1ENW9xLFDZUP9rh+yP76DOq38wBoFi1+I9+6qBg==";
    name = "binding-darwin-arm64-0.5.48.tgz";
  };
  "@yuku-codegen/binding-darwin-x64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-darwin-x64/-/binding-darwin-x64-0.5.48.tgz";
    hash = "sha512-aRCTw0EZC4bVosmw//0OMYP5tGWFE0Cu5yUBFkUbhXx/iBzvORcJ2xPNlOp/vtCCo9Ys4vp8b0DigJV6uOVb2g==";
    name = "binding-darwin-x64-0.5.48.tgz";
  };
  "@yuku-codegen/binding-freebsd-x64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-freebsd-x64/-/binding-freebsd-x64-0.5.48.tgz";
    hash = "sha512-CA0AQAEApDkbw51PdLWMtKPJ41/7rvXsS3SJs+phG7fHJI+MuFzWuLbkucZfZoEOiDscmcsfYIdgL8BsfuyKKQ==";
    name = "binding-freebsd-x64-0.5.48.tgz";
  };
  "@yuku-codegen/binding-linux-arm-gnu@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm-gnu/-/binding-linux-arm-gnu-0.5.48.tgz";
    hash = "sha512-DuSQlk8bH4gpmW3/00P0NLagAcMv8jOxjT40cQmxKRkktr+SUOALCfkT89tdDq3qtY95NR2GXOZ7AjNh7KKqCw==";
    name = "binding-linux-arm-gnu-0.5.48.tgz";
  };
  "@yuku-codegen/binding-linux-arm-musl@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm-musl/-/binding-linux-arm-musl-0.5.48.tgz";
    hash = "sha512-bxj4Ee+wlaJcWJwft2ReJXWw5sfl1qavDz6+dlRdU1xfTEtjPSNiAWhiCHnJR0R4Ygd57DnzSQmAVGvFv6RcGw==";
    name = "binding-linux-arm-musl-0.5.48.tgz";
  };
  "@yuku-codegen/binding-linux-arm64-gnu@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.5.48.tgz";
    hash = "sha512-mk5JVWh+0JOe5ue8k17kbYX8uGBoKt3ZqoCyxNh4nYAAcX7+X1tFUiU7jbjctu4vHeejCBFSTdQ021+V31cUCQ==";
    name = "binding-linux-arm64-gnu-0.5.48.tgz";
  };
  "@yuku-codegen/binding-linux-arm64-musl@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.5.48.tgz";
    hash = "sha512-4q3vkrNghbllyxOm2KesFLxCPKHF7r3JyQ7BWZccY1j2Y05yKoIFhoWCqIuQ2W/dpte9RI0+OVfwyxnrKg6fkA==";
    name = "binding-linux-arm64-musl-0.5.48.tgz";
  };
  "@yuku-codegen/binding-linux-x64-gnu@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.5.48.tgz";
    hash = "sha512-csd4M1EVrGaohM8acM6gq1zpUA/Rwe2ulUMBKUcwQXm/k6n7cq1A++qdew78SOVb4do3JH1WE+WFwoGQAcWc1w==";
    name = "binding-linux-x64-gnu-0.5.48.tgz";
  };
  "@yuku-codegen/binding-linux-x64-musl@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-x64-musl/-/binding-linux-x64-musl-0.5.48.tgz";
    hash = "sha512-KcDuEOT+GFoVKdvAWOv1v9iYjwnmvMZlO+j1Rw+5PYdeFLGWGzv/DD11y4SAAdwXIFcil4T0hibeIaF82WStMg==";
    name = "binding-linux-x64-musl-0.5.48.tgz";
  };
  "@yuku-codegen/binding-win32-arm64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-win32-arm64/-/binding-win32-arm64-0.5.48.tgz";
    hash = "sha512-HI8qNrI8dWM5BuqIMKsqornRvTNFrE6sm5zToIJ9YIa9zt5+29P7fJ7Nr39EVf6dAWSb6q7JSpScJnRsQ+FgZA==";
    name = "binding-win32-arm64-0.5.48.tgz";
  };
  "@yuku-codegen/binding-win32-x64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-win32-x64/-/binding-win32-x64-0.5.48.tgz";
    hash = "sha512-X5YWJLO6EfBZpeBqO0AYESnUizbpFDWArcvVD61w0PEWQ3CaFRLnbQXs+kpM4ZZfGMfIE22zfA08QSY67q7TNQ==";
    name = "binding-win32-x64-0.5.48.tgz";
  };
  "@yuku-parser/binding-darwin-arm64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-darwin-arm64/-/binding-darwin-arm64-0.5.48.tgz";
    hash = "sha512-If8mb7HH3vqghJ2NNZ8SuHfhsnjVzOxJpB8xcNOXS5WjYrs2mUhHIh5KOIvK13hDOzh0htGeGK3A6MsiEqE7HQ==";
    name = "binding-darwin-arm64-0.5.48.tgz";
  };
  "@yuku-parser/binding-darwin-x64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-darwin-x64/-/binding-darwin-x64-0.5.48.tgz";
    hash = "sha512-EimvPXfspzxf1K11eB6tCW5oiQEXB8g84T2wP1TwzQagdDKo33bkmmVF0B32vTIpXnk/Ifu5IB61izZ1MylljA==";
    name = "binding-darwin-x64-0.5.48.tgz";
  };
  "@yuku-parser/binding-freebsd-x64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-freebsd-x64/-/binding-freebsd-x64-0.5.48.tgz";
    hash = "sha512-0GcUMrumLHheThY9r5Tp46gaZYzn0irWPS1Zba6WY+vVQfhUtzGiWgXxI6tuXX0N32kEaaEVRpkKctvo6Kx3aQ==";
    name = "binding-freebsd-x64-0.5.48.tgz";
  };
  "@yuku-parser/binding-linux-arm-gnu@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm-gnu/-/binding-linux-arm-gnu-0.5.48.tgz";
    hash = "sha512-8S5T5wjCC73dmmpQeZ49aYsSunIUM3D4Fc6rdK96c+Ayg/p3FmeSPF3xuLZHejcTmqJIIvnbfPlUF+rB6DITjQ==";
    name = "binding-linux-arm-gnu-0.5.48.tgz";
  };
  "@yuku-parser/binding-linux-arm-musl@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm-musl/-/binding-linux-arm-musl-0.5.48.tgz";
    hash = "sha512-tTmbxvnUHcK2/crS9547vk2SMmsajH1yqJ8ltXhIuHJgqR1v+d9n9KT+kSayo/5CS76LegeYxhMFjEivBH2hFA==";
    name = "binding-linux-arm-musl-0.5.48.tgz";
  };
  "@yuku-parser/binding-linux-arm64-gnu@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.5.48.tgz";
    hash = "sha512-KGYCBMqI2zfwyhgq5tpPVNe7jpUeYTBm8DhjdS+zqWNumde/PEC170QE5RHxcOAlsirIDeIUk0jqx+r/axoFSw==";
    name = "binding-linux-arm64-gnu-0.5.48.tgz";
  };
  "@yuku-parser/binding-linux-arm64-musl@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.5.48.tgz";
    hash = "sha512-2wTSMsCSXLTc2lZUjMAuU5X4cje55u205WJqfV5NWNF6j9pW/tXyxr15dJeekj8ziLqBXzIsj4DbRh4sY/WcjA==";
    name = "binding-linux-arm64-musl-0.5.48.tgz";
  };
  "@yuku-parser/binding-linux-x64-gnu@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.5.48.tgz";
    hash = "sha512-d/6v9UnGglVu1WC2JQyv/5aWSi5fXZeGSlidCfmHp4+N65N1GDKUnFtys5MK5eAPeAjTgSHGGtOc/yCcKTlv3A==";
    name = "binding-linux-x64-gnu-0.5.48.tgz";
  };
  "@yuku-parser/binding-linux-x64-musl@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-x64-musl/-/binding-linux-x64-musl-0.5.48.tgz";
    hash = "sha512-gX19gw6u4ApPy7SYMPKfFlEkrtj6WlORvrTKK3sBQqjyV+8+mUAkQgxXNjHw4RnOiAmVYg7TOlZcg8d+Qqod9A==";
    name = "binding-linux-x64-musl-0.5.48.tgz";
  };
  "@yuku-parser/binding-win32-arm64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-win32-arm64/-/binding-win32-arm64-0.5.48.tgz";
    hash = "sha512-w6cQQLbqj3Jcom5Q7ifm103NUOQ9d+Cb4VU5lkrZDjMnwVJ9Hzzg1vCQR7miJuF44vhCXldbme5UryE3giEKlA==";
    name = "binding-win32-arm64-0.5.48.tgz";
  };
  "@yuku-parser/binding-win32-x64@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-win32-x64/-/binding-win32-x64-0.5.48.tgz";
    hash = "sha512-4gO0HmG7fzFxrw1rs0dUdnnaY9YgennjETqDWrTSp7x9fmTUOAoN4VsMfP7YyliQeG1WJJHc55O+rOhmsLppow==";
    name = "binding-win32-x64-0.5.48.tgz";
  };
  "@yuku-toolchain/types@0.5.43" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-toolchain/types/-/types-0.5.43.tgz";
    hash = "sha512-kSpvPntnXw5+lYjO71ffBEnQ5ycQ74KGIYknh0TS4xeyCuBkOqxyJumxZkMhLBBUCLjDAbx2+Icnr3Zh4ftjpQ==";
    name = "types-0.5.43.tgz";
  };
  "ansi-regex@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/ansi-regex/-/ansi-regex-5.0.1.tgz";
    hash = "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
    name = "ansi-regex-5.0.1.tgz";
  };
  "ansi-styles@5.2.0" = fetchurl {
    url = "https://npm.flatt.tech/ansi-styles/-/ansi-styles-5.2.0.tgz";
    hash = "sha512-Cxwpt2SfTzTtXcfOlzGEee8O+c+MmUgGrNiBcXnuWxuFJHe6a5Hz7qwhwe5OgaSYI0IJvkLqWX1ASG+cJOkEiA==";
    name = "ansi-styles-5.2.0.tgz";
  };
  "aria-query@5.3.0" = fetchurl {
    url = "https://npm.flatt.tech/aria-query/-/aria-query-5.3.0.tgz";
    hash = "sha512-b0P0sZPKtyu8HkeRAfCq0IfURZK+SuwMjY1UXGBU27wpAiTwQAIlq56IbIO+ytk/JjS1fMR14ee5WBBfKi5J6A==";
    name = "aria-query-5.3.0.tgz";
  };
  "assertion-error@2.0.1" = fetchurl {
    url = "https://npm.flatt.tech/assertion-error/-/assertion-error-2.0.1.tgz";
    hash = "sha512-Izi8RQcffqCeNVgFigKli1ssklIbpHnCYc6AknXGYoB6grJqyeby7jv12JUQgmTAnIDnbck1uxksT4dzN3PWBA==";
    name = "assertion-error-2.0.1.tgz";
  };
  "chai@6.2.2" = fetchurl {
    url = "https://npm.flatt.tech/chai/-/chai-6.2.2.tgz";
    hash = "sha512-NUPRluOfOiTKBKvWPtSD4PhFvWCqOi0BGStNWs57X9js7XGTprSmFoz5F0tWhR4WPjNeR9jXqdC7/UpSJTnlRg==";
    name = "chai-6.2.2.tgz";
  };
  "convert-source-map@2.0.0" = fetchurl {
    url = "https://npm.flatt.tech/convert-source-map/-/convert-source-map-2.0.0.tgz";
    hash = "sha512-Kvp459HrV2FEJ1CAsi1Ku+MY3kasH19TFykTz2xWmMeq6bk2NU3XXvfJ+Q61m0xktWwt+1HSYf3JZsTms3aRJg==";
    name = "convert-source-map-2.0.0.tgz";
  };
  "dequal@2.0.3" = fetchurl {
    url = "https://npm.flatt.tech/dequal/-/dequal-2.0.3.tgz";
    hash = "sha512-0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
    name = "dequal-2.0.3.tgz";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://npm.flatt.tech/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
    name = "detect-libc-2.1.2.tgz";
  };
  "dom-accessibility-api@0.5.16" = fetchurl {
    url = "https://npm.flatt.tech/dom-accessibility-api/-/dom-accessibility-api-0.5.16.tgz";
    hash = "sha512-X7BJ2yElsnOJ30pZF4uIIDfBEVgF4XEBxL9Bxhy6dnrm5hkzqmsWHGTiHqRiITNhMyFLyAiWndIJP7Z1NTteDg==";
    name = "dom-accessibility-api-0.5.16.tgz";
  };
  "es-module-lexer@2.3.2" = fetchurl {
    url = "https://npm.flatt.tech/es-module-lexer/-/es-module-lexer-2.3.2.tgz";
    hash = "sha512-poHGpORABojJJucnV9KbOavETW8lBVnphkW77ER5/BQ5Fz7oXSoCNek7IH3vR5nRjdsEz926ibFYX8KtLQmdyw==";
    name = "es-module-lexer-2.3.2.tgz";
  };
  "estree-walker@3.0.3" = fetchurl {
    url = "https://npm.flatt.tech/estree-walker/-/estree-walker-3.0.3.tgz";
    hash = "sha512-7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
    name = "estree-walker-3.0.3.tgz";
  };
  "expect-type@1.4.0" = fetchurl {
    url = "https://npm.flatt.tech/expect-type/-/expect-type-1.4.0.tgz";
    hash = "sha512-KfYbmpRm0VbLjEvVa9yGwCi9GI34xvi7A/HXYWQO65CSD2u3MczUJSuwXKFIxlGsgBQizV9q5J9NHj4VG0n+pA==";
    name = "expect-type-1.4.0.tgz";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://npm.flatt.tech/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
    name = "fdir-6.5.0.tgz";
  };
  "fsevents@2.3.3" = fetchurl {
    url = "https://npm.flatt.tech/fsevents/-/fsevents-2.3.3.tgz";
    hash = "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==";
    name = "fsevents-2.3.3.tgz";
  };
  "js-tokens@4.0.0" = fetchurl {
    url = "https://npm.flatt.tech/js-tokens/-/js-tokens-4.0.0.tgz";
    hash = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
    name = "js-tokens-4.0.0.tgz";
  };
  "lightningcss-android-arm64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-android-arm64/-/lightningcss-android-arm64-1.33.0.tgz";
    hash = "sha512-gEpRTalKdosp4Bb8qWtc2iOgE5SeIHlpS1up9bFq2wAyYhl1UdTObYiHe98zEM9SQvSoqQZ1IQD0JNpg3Ml5pg==";
    name = "lightningcss-android-arm64-1.33.0.tgz";
  };
  "lightningcss-darwin-arm64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-darwin-arm64/-/lightningcss-darwin-arm64-1.33.0.tgz";
    hash = "sha512-Sciaz8eenNTKn9b3t7+xr0ipTp9YxKQY4npwQ3mrRuL0BAVHBLyZxofhaKBAVtzmtRZ/zTyo0/to4B1uWG/Djg==";
    name = "lightningcss-darwin-arm64-1.33.0.tgz";
  };
  "lightningcss-darwin-x64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-darwin-x64/-/lightningcss-darwin-x64-1.33.0.tgz";
    hash = "sha512-Z5UPAxzrjlWNNyGy6i65cJzzvgJ5D3T6wMvs+gWpY9d7qRhANrxqAp6LhxIgZhWEw18RfJTGcRxjuLIBr+m8XQ==";
    name = "lightningcss-darwin-x64-1.33.0.tgz";
  };
  "lightningcss-freebsd-x64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-freebsd-x64/-/lightningcss-freebsd-x64-1.33.0.tgz";
    hash = "sha512-QQM/Ti/hQajJwCY+RiWuCZ9sdtI/XQk7nDK5vC8kkdwixezOlDgvDx7+RT+QjK6FcFT4MpsuoBnHIo/O3StRRg==";
    name = "lightningcss-freebsd-x64-1.33.0.tgz";
  };
  "lightningcss-linux-arm-gnueabihf@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm-gnueabihf/-/lightningcss-linux-arm-gnueabihf-1.33.0.tgz";
    hash = "sha512-N7FVBe6iS24MlM6R/4RBTxGhQheZGs7tiQ9U32UtF75NzP5Q7xWPRqLBCKxlRQRk3rY1jCIPLzx7WzOhuUIRLQ==";
    name = "lightningcss-linux-arm-gnueabihf-1.33.0.tgz";
  };
  "lightningcss-linux-arm64-gnu@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm64-gnu/-/lightningcss-linux-arm64-gnu-1.33.0.tgz";
    hash = "sha512-j2v/itmy4HlNxlc6voKXYgBqNi0Ng2LShg4z7GufpEgs05P+2suBVyi9I6YHq5uoVFx9ETin3eCEhLVyXGQnKg==";
    name = "lightningcss-linux-arm64-gnu-1.33.0.tgz";
  };
  "lightningcss-linux-arm64-musl@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm64-musl/-/lightningcss-linux-arm64-musl-1.33.0.tgz";
    hash = "sha512-yiO5ROMuYQgXbC60yjZU5CYSFZGKXL0HFATXt9mHJn1+zW55oCtMI9NfcVhYLMFDL7gV7oBPon/EmMMGg2OvtQ==";
    name = "lightningcss-linux-arm64-musl-1.33.0.tgz";
  };
  "lightningcss-linux-x64-gnu@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.33.0.tgz";
    hash = "sha512-ar+Ju7LmcN0Jo4FpL4hpFybwNG9/3A/Br5KW2n2jyODg3MEZXaDYADdemoNS+BDNfMgKvylJLj4S5tyRActuAg==";
    name = "lightningcss-linux-x64-gnu-1.33.0.tgz";
  };
  "lightningcss-linux-x64-musl@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-x64-musl/-/lightningcss-linux-x64-musl-1.33.0.tgz";
    hash = "sha512-RYiYbkokw0trfKqqzfF55lginwEPrD3OJDfTuJzFs1MK6iFnDenaz1fqLLtX4ITG3OktJQXOeTaw1awrBAlZPw==";
    name = "lightningcss-linux-x64-musl-1.33.0.tgz";
  };
  "lightningcss-win32-arm64-msvc@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-win32-arm64-msvc/-/lightningcss-win32-arm64-msvc-1.33.0.tgz";
    hash = "sha512-1K+MPfLSFVpphzpdbfkhlWk6wBrTObBzS2T6db10PNOZgR9GoVsAWzwNyuhUYYbTp23j+4RrncfujZ4uAzXvwA==";
    name = "lightningcss-win32-arm64-msvc-1.33.0.tgz";
  };
  "lightningcss-win32-x64-msvc@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-win32-x64-msvc/-/lightningcss-win32-x64-msvc-1.33.0.tgz";
    hash = "sha512-OlEICDx/Xl0FqSp4bry8zFnCvGpig3Gl4gCquvYwHuqJKEC1+n9NgDniFvqHGmMv1ZkqDJrDqKKSykTDX+ehuA==";
    name = "lightningcss-win32-x64-msvc-1.33.0.tgz";
  };
  "lightningcss@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss/-/lightningcss-1.33.0.tgz";
    hash = "sha512-WkUDrojuJs0xkgGf2udWxa3yGBRxPtxUkB79i6aCZLRgc7PM8fZe9TosfPDcvEpQZbuFASnHYmRLBLUbmLOIIA==";
    name = "lightningcss-1.33.0.tgz";
  };
  "lz-string@1.5.0" = fetchurl {
    url = "https://npm.flatt.tech/lz-string/-/lz-string-1.5.0.tgz";
    hash = "sha512-h5bgJWpxJNswbU7qCrV0tIKQCaS3blPDrqKWx+QxzuzL1zGUzij9XCWLrSLsJPu5t+eWA/ycetzYAO5IOMcWAQ==";
    name = "lz-string-1.5.0.tgz";
  };
  "magic-string@0.30.21" = fetchurl {
    url = "https://npm.flatt.tech/magic-string/-/magic-string-0.30.21.tgz";
    hash = "sha512-vd2F4YUyEXKGcLHoq+TEyCjxueSeHnFxyyjNp80yg0XV4vUhnDer/lvvlqM/arB5bXQN5K2/3oinyCRyx8T2CQ==";
    name = "magic-string-0.30.21.tgz";
  };
  "mrmime@2.0.1" = fetchurl {
    url = "https://npm.flatt.tech/mrmime/-/mrmime-2.0.1.tgz";
    hash = "sha512-Y3wQdFg2Va6etvQ5I82yUhGdsKrcYox6p7FfL1LbK2J4V01F9TGlepTIhnK24t7koZibmg82KGglhA1XK5IsLQ==";
    name = "mrmime-2.0.1.tgz";
  };
  "nanoid@3.3.19" = fetchurl {
    url = "https://npm.flatt.tech/nanoid/-/nanoid-3.3.19.tgz";
    hash = "sha512-Y2tUNy4ouw6tq5oDSKeQYGOyhkUBhNOcGV/02KC+6kd9eDGqdZd++mjMiIDilrBYvjEnCYvVtsuHCuP+okSfug==";
    name = "nanoid-3.3.19.tgz";
  };
  "obug@2.2.1" = fetchurl {
    url = "https://npm.flatt.tech/obug/-/obug-2.2.1.tgz";
    hash = "sha512-XrsrhT5sybtKI6wakr2SPOlGZWWYbUXZ7a0jT8/QOeAPau+1X/bSegNe5YR75oJmEZQbKningirmGOEJCIk61Q==";
    name = "obug-2.2.1.tgz";
  };
  "oxfmt@0.64.0" = fetchurl {
    url = "https://npm.flatt.tech/oxfmt/-/oxfmt-0.64.0.tgz";
    hash = "sha512-XZ4GFBN/PLbXKq+0zrgpQfPKYuJlUuj+nzZJY7UpIbFMNyefNLCdN9EwViycNqnYcv0wrn0jXcQLlqJp8RCKBg==";
    name = "oxfmt-0.64.0.tgz";
  };
  "oxlint-tsgolint@7.0.2001" = fetchurl {
    url = "https://npm.flatt.tech/oxlint-tsgolint/-/oxlint-tsgolint-7.0.2001.tgz";
    hash = "sha512-KjK/XLcXr1DSyonKhsuFqJRiuKqcyG9j3LJ8nkOsrLzGvodBPqzHOKauy10asLMDI0sUpvb+1sxlzff3udZvfg==";
    name = "oxlint-tsgolint-7.0.2001.tgz";
  };
  "oxlint@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/oxlint/-/oxlint-1.79.0.tgz";
    hash = "sha512-hVJ9hq9m2unPS+Of4eJJgCPdIeCC+3DHEUX3tkmrPJr3OK2hz7PhXwgC+ZP71ZcYu8cCDEtQrqLxWNvxBppBVg==";
    name = "oxlint-1.79.0.tgz";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://npm.flatt.tech/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
    name = "pathe-2.0.3.tgz";
  };
  "picocolors@1.1.1" = fetchurl {
    url = "https://npm.flatt.tech/picocolors/-/picocolors-1.1.1.tgz";
    hash = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
    name = "picocolors-1.1.1.tgz";
  };
  "picomatch@4.0.7" = fetchurl {
    url = "https://npm.flatt.tech/picomatch/-/picomatch-4.0.7.tgz";
    hash = "sha512-qcJu88Q2IWqJsDD529JKMdwGm/dvInW4HvQnRwiH9JtihJvzGOscDtHE3x1pBKeUOTysQ8kVmLnJ2kJu7yhcGA==";
    name = "picomatch-4.0.7.tgz";
  };
  "pngjs@7.0.0" = fetchurl {
    url = "https://npm.flatt.tech/pngjs/-/pngjs-7.0.0.tgz";
    hash = "sha512-LKWqWJRhstyYo9pGvgor/ivk2w94eSjE3RGVuzLGlr3NmD8bf7RcYGze1mNdEHRP6TRP6rMuDHk5t44hnTRyow==";
    name = "pngjs-7.0.0.tgz";
  };
  "postcss@8.5.28" = fetchurl {
    url = "https://npm.flatt.tech/postcss/-/postcss-8.5.28.tgz";
    hash = "sha512-RRuzqDtt5Y9h3quz5hWhK+TPnsmVs6WwSU6LkJMeY4HstUEDuYTG8UJSdawMRzmzAtV+KEoG8N3Qg2qLy5vM/A==";
    name = "postcss-8.5.28.tgz";
  };
  "pretty-format@27.5.1" = fetchurl {
    url = "https://npm.flatt.tech/pretty-format/-/pretty-format-27.5.1.tgz";
    hash = "sha512-Qb1gy5OrP5+zDf2Bvnzdl3jsTf1qXVMazbvCoKhtKqVs4/YK4ozX4gKQJJVyNe+cajNPn0KoC0MC3FUmaHWEmQ==";
    name = "pretty-format-27.5.1.tgz";
  };
  "react-is@17.0.2" = fetchurl {
    url = "https://npm.flatt.tech/react-is/-/react-is-17.0.2.tgz";
    hash = "sha512-w2GsyukL62IJnlaff/nRegPQR94C/XXamvMWmSHRJ4y7Ts/4ocGRmTHvOs8PSE6pB3dWOrD/nueuU5sduBsQ4w==";
    name = "react-is-17.0.2.tgz";
  };
  "rolldown@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/rolldown/-/rolldown-1.2.8.tgz";
    hash = "sha512-Z67nTmhZe7anqnM/EjI392w5i/ANUinjip7QYsOyN37oayduxt3ksdX0hf5OOamkAd53BiIHfbfSzfUmzKFQqQ==";
    name = "rolldown-1.2.8.tgz";
  };
  "siginfo@2.0.0" = fetchurl {
    url = "https://npm.flatt.tech/siginfo/-/siginfo-2.0.0.tgz";
    hash = "sha512-ybx0WO1/8bSBLEWXZvEd7gMW3Sn3JFlW3TvX1nREbDLRNQNaeNN8WK0meBwPdAaOI7TtRRRJn/Es1zhrrCHu7g==";
    name = "siginfo-2.0.0.tgz";
  };
  "sirv@3.0.2" = fetchurl {
    url = "https://npm.flatt.tech/sirv/-/sirv-3.0.2.tgz";
    hash = "sha512-2wcC/oGxHis/BoHkkPwldgiPSYcpZK3JU28WoMVv55yHJgcZ8rlXvuG9iZggz+sU1d4bRgIGASwyWqjxu3FM0g==";
    name = "sirv-3.0.2.tgz";
  };
  "source-map-js@1.2.1" = fetchurl {
    url = "https://npm.flatt.tech/source-map-js/-/source-map-js-1.2.1.tgz";
    hash = "sha512-UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
    name = "source-map-js-1.2.1.tgz";
  };
  "stackback@0.0.2" = fetchurl {
    url = "https://npm.flatt.tech/stackback/-/stackback-0.0.2.tgz";
    hash = "sha512-1XMJE5fQo1jGH6Y/7ebnwPOBEkIEnT4QF32d5R1+VXdXveM0IBMJt8zfaxX1P3QhVwrYe+576+jkANtSS2mBbw==";
    name = "stackback-0.0.2.tgz";
  };
  "std-env@4.2.0" = fetchurl {
    url = "https://npm.flatt.tech/std-env/-/std-env-4.2.0.tgz";
    hash = "sha512-oCUKSupKTHX53EyjDtuZQ64pjLJ6yYCtpmEw0goYxtjG9KpbRe8KAsl2tBUGU9DyMcJ0RwJ8GqJAFzMXcXW1Rw==";
    name = "std-env-4.2.0.tgz";
  };
  "tinybench@2.9.0" = fetchurl {
    url = "https://npm.flatt.tech/tinybench/-/tinybench-2.9.0.tgz";
    hash = "sha512-0+DUvqWMValLmha6lr4kD8iAMK1HzV0/aKnCtWb9v9641TnP/MFb7Pc2bxoxQjTXAErryXVgUOfv2YqNllqGeg==";
    name = "tinybench-2.9.0.tgz";
  };
  "tinyexec@1.3.1" = fetchurl {
    url = "https://npm.flatt.tech/tinyexec/-/tinyexec-1.3.1.tgz";
    hash = "sha512-GCvB3aoys96IuDFBMcTB46JOR6mdMtAToqwiW8JlWhsoh1mhHi/xn9ss/Dg7N555GiJyEt2qzoG/NHCwM6h1EA==";
    name = "tinyexec-1.3.1.tgz";
  };
  "tinyglobby@0.2.17" = fetchurl {
    url = "https://npm.flatt.tech/tinyglobby/-/tinyglobby-0.2.17.tgz";
    hash = "sha512-wXR/dYpcqKmfWpEdZjiKJOwCNFndD0DMnrW/cYjVGttEkBfVgcLFHoNrlj47mjOVic9yyNu65alsgF4NQyTa2g==";
    name = "tinyglobby-0.2.17.tgz";
  };
  "tinypool@2.1.0" = fetchurl {
    url = "https://npm.flatt.tech/tinypool/-/tinypool-2.1.0.tgz";
    hash = "sha512-Pugqs6M0m7Lv1I7FtxN4aoyToKg1C4tu+/381vH35y8oENM/Ai7f7C4StcoK4/+BSw9ebcS8jRiVrORFKCALLw==";
    name = "tinypool-2.1.0.tgz";
  };
  "tinyrainbow@3.1.1" = fetchurl {
    url = "https://npm.flatt.tech/tinyrainbow/-/tinyrainbow-3.1.1.tgz";
    hash = "sha512-yau8yJdTt989Mm0Bd/236QnzEiPf2xLLTqUZRUJOo/3CB078LSwzei343DgtJVmfJKJE3TMINY1u42SQsP6mXw==";
    name = "tinyrainbow-3.1.1.tgz";
  };
  "totalist@3.0.1" = fetchurl {
    url = "https://npm.flatt.tech/totalist/-/totalist-3.0.1.tgz";
    hash = "sha512-sf4i37nQ2LBx4m3wB74y+ubopq6W/dIzXg0FDGjsYnZHVa1Da8FH853wlL2gtUhg+xJXjfk3kUZS3BRoQeoQBQ==";
    name = "totalist-3.0.1.tgz";
  };
  "typescript@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/typescript/-/typescript-7.0.2.tgz";
    hash = "sha512-8FYau96o3NKOhbjKi/qNvG/W5jhzxkbdm5sj9AbZ/5T5sWqn3hJgLfGx27sRKZWTvyzCP8dLRBTf5tBTSRVUNA==";
    name = "typescript-7.0.2.tgz";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://npm.flatt.tech/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
    name = "undici-types-7.18.2.tgz";
  };
  "vite-plus@0.3.0" = fetchurl {
    url = "https://npm.flatt.tech/vite-plus/-/vite-plus-0.3.0.tgz";
    hash = "sha512-GNWbWuWD37frCSFrz6MLzUo62bTv5IOJozHEgZYOkxsLkuQtTwm4TowzpfoGrSsfwhAAtfPd/sK1Y0+v1SwhZA==";
    name = "vite-plus-0.3.0.tgz";
  };
  "vite@8.3.0" = fetchurl {
    url = "https://npm.flatt.tech/vite/-/vite-8.3.0.tgz";
    hash = "sha512-lhZBVvEHefgE+HQZC9O7EBJgCU/nVzFNl7vkS4RE0APtWLP02/8QVIkQtzBxPquh7lq5/78NHipTj7ODQ6XuyQ==";
    name = "vite-8.3.0.tgz";
  };
  "vitest@4.1.11" = fetchurl {
    url = "https://npm.flatt.tech/vitest/-/vitest-4.1.11.tgz";
    hash = "sha512-fhACrNXUidIbGSBr5FlbuBkO7VWC1ZyLl0DO4CU2DrQoAPxX84Ysxs+HeGQpii5lZWV1Q4gBZTTu49mF+A6Edw==";
    name = "vitest-4.1.11.tgz";
  };
  "why-is-node-running@2.3.0" = fetchurl {
    url = "https://npm.flatt.tech/why-is-node-running/-/why-is-node-running-2.3.0.tgz";
    hash = "sha512-hUrmaWBdVDcxvYqnyh09zunKzROWjbZTiNy8dBEjkS7ehEDQibXJ7XvlmtbwuTclUiIyN+CyXQD4Vmko8fNm8w==";
    name = "why-is-node-running-2.3.0.tgz";
  };
  "ws@8.21.3" = fetchurl {
    url = "https://npm.flatt.tech/ws/-/ws-8.21.3.tgz";
    hash = "sha512-201TZ/kPWxoPr/OKWjquZR1SWKXcvxdH+e1xrx89b3YbmzLMFCLfnaG1HFIgWzJOEWZ7MvpK++odZufgYR50Rw==";
    name = "ws-8.21.3.tgz";
  };
  "yuku-codegen@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/yuku-codegen/-/yuku-codegen-0.5.48.tgz";
    hash = "sha512-p7HxD5Xl4jzDzqMrGePAOeSHmRY4g58h4HuGq15weQFPxuPWd/W6e7nqp/+Lea6JfpOdBwJOAyXFqIZ/J9Zfnw==";
    name = "yuku-codegen-0.5.48.tgz";
  };
  "yuku-parser@0.5.48" = fetchurl {
    url = "https://npm.flatt.tech/yuku-parser/-/yuku-parser-0.5.48.tgz";
    hash = "sha512-OWBfhrpgK9+/4+IXG9oT8Bao4AhViQA7vdyNNH7EUg8dQYgwa70XtIBWTpCEme1P1ECyoDNYkn0wT63f8XRcVA==";
    name = "yuku-parser-0.5.48.tgz";
  };
}