# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@babel/code-frame@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/code-frame/-/code-frame-7.29.7.tgz";
    hash = "sha512-Aup7aUOfpbAUg2ROOJN6Iw5f9DMBlzu0mIkm/malLQFN/YQgO48wCj0Kxa3sEHJvPVFg7siR+qRInwXd2qhQKw==";
    name = "code-frame-7.29.7.tgz";
  };
  "@babel/helper-validator-identifier@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/helper-validator-identifier/-/helper-validator-identifier-7.29.7.tgz";
    hash = "sha512-qehxGkRj55h/ff8EMaJ+cYhyaKlHIxqYDn682wQD7RNp9UujOQsHog2uS0r2vzr4pW+sXf90NeeayjcNaX3fFg==";
    name = "helper-validator-identifier-7.29.7.tgz";
  };
  "@babel/runtime@7.29.7" = fetchurl {
    url = "https://npm.flatt.tech/@babel/runtime/-/runtime-7.29.7.tgz";
    hash = "sha512-Nq8OhGWiZIZGV6hLHoyAKLLcJihP/xFeBMGJoUrxTX2psI8dCifzLhZISFb+VWS3wFMRDmCGw5R+dOySCqPLhw==";
    name = "runtime-7.29.7.tgz";
  };
  "@blazediff/core@1.10.0" = fetchurl {
    url = "https://npm.flatt.tech/@blazediff/core/-/core-1.10.0.tgz";
    hash = "sha512-AOQff0zgR7cGsZL+4E7hVkmujoPUpm0J9xzWGWZj5wCjd3gmxESXAPfKyuzs93VdpQNFhHlBhfOjrcZ+XTERtQ==";
    name = "core-1.10.0.tgz";
  };
  "@jridgewell/resolve-uri@3.1.2" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
    hash = "sha512-bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
    name = "resolve-uri-3.1.2.tgz";
  };
  "@jridgewell/sourcemap-codec@1.6.0" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.6.0.tgz";
    hash = "sha512-T7jf+5zgsZHwNJ4lvQ7/aezbyk0nNX+zJVWpmHA7VYsEx7a7qr5Rg5IbtJFqkgze5Y2sruq1RUY8Q837Od7iFw==";
    name = "sourcemap-codec-1.6.0.tgz";
  };
  "@jridgewell/trace-mapping@0.3.31" = fetchurl {
    url = "https://npm.flatt.tech/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
    hash = "sha512-zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
    name = "trace-mapping-0.3.31.tgz";
  };
  "@oxc-project/runtime@0.151.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/runtime/-/runtime-0.151.0.tgz";
    hash = "sha512-fNuliiqGTseerW2FTbxq6UOQavKL/NvNh9K3peJZZVNi1NbM4Ehscwp3MX9nu+9bfbSfmPUEivF779XQU5exiw==";
    name = "runtime-0.151.0.tgz";
  };
  "@oxc-project/types@0.149.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/types/-/types-0.149.0.tgz";
    hash = "sha512-Efcc+iF0j3Bf67YjEqIqWXbX5XddXoK/Mw4K1/JuXwRCZ8N16VR7iT23nlCc9XrveFVh/E5Rqs2StT0V8v9LdA==";
    name = "types-0.149.0.tgz";
  };
  "@oxc-project/types@0.151.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxc-project/types/-/types-0.151.0.tgz";
    hash = "sha512-J1yXrIlNDZVzE3ada310xeAw7nH8yCAyLPuUIsjKatFPmfn5bS1oW+cM+QsGOtVWd5nhSpbwZWx/rue+r5Z+PA==";
    name = "types-0.151.0.tgz";
  };
  "@oxfmt/binding-android-arm-eabi@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-android-arm-eabi/-/binding-android-arm-eabi-0.70.0.tgz";
    hash = "sha512-Xd7YO4/T2axEj6FTLcj4Why3mTBqFMg+x24xtorT4Lb2+1g82090GH0a/4U1m0pABGYiix2bq1pqkYrmV3f0Sw==";
    name = "binding-android-arm-eabi-0.70.0.tgz";
  };
  "@oxfmt/binding-android-arm64@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-android-arm64/-/binding-android-arm64-0.70.0.tgz";
    hash = "sha512-x9rlMYyKXdgKdYyUJzGsK1ZV8P4di/J32ipzcS6Jet6p9r9UAh28neXIMtdlSaJJycdi61Z4YkcLKLpk8ueFjg==";
    name = "binding-android-arm64-0.70.0.tgz";
  };
  "@oxfmt/binding-darwin-arm64@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-darwin-arm64/-/binding-darwin-arm64-0.70.0.tgz";
    hash = "sha512-IUTUPvrBVYy7POh4stXzRdz4IVC/1QSaviCWoyenSlOhGu0X9j5K07vCTM9biLjAA2Zs31l0Rj5vvRpj9n95wA==";
    name = "binding-darwin-arm64-0.70.0.tgz";
  };
  "@oxfmt/binding-darwin-x64@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-darwin-x64/-/binding-darwin-x64-0.70.0.tgz";
    hash = "sha512-vw745q870oTd6J517O24asoX4/E+eK0nxYIFoedSLqgJ+nI5En7+ZS82iZSHZ69zevQrnOXiyHP01dA+t8xD8w==";
    name = "binding-darwin-x64-0.70.0.tgz";
  };
  "@oxfmt/binding-freebsd-x64@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-freebsd-x64/-/binding-freebsd-x64-0.70.0.tgz";
    hash = "sha512-NO14EgSM9dFkcg+MfGPxvsKqXYs9LKaxPrOKXpv1R0rLokGGFDcCq6dBMq18dE4wlpFOovX0UZY2uh1P30O7QA==";
    name = "binding-freebsd-x64-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-arm-gnueabihf@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-0.70.0.tgz";
    hash = "sha512-139OEhHarj9CYoJ/i9gXlPv4KLBGtLj2toseOWYFf09QwlhklaZk+wW3aOvlqoeZtuayvkoSNVWra7WJ21s3VQ==";
    name = "binding-linux-arm-gnueabihf-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-arm-musleabihf@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-0.70.0.tgz";
    hash = "sha512-GEh2PY3IWTE0M24eNhTduountANSbWyDmMnzFSQE/nGg/bjPugbUgiGuFu+xdqcQSd/HKSwH80/F2yVVD48yhA==";
    name = "binding-linux-arm-musleabihf-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-arm64-gnu@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.70.0.tgz";
    hash = "sha512-En5i+UJmZSPxuSf47F2Hl5YOzKB0bicQLnGQkeTCMQ35cWLtbrSwACJKfiLqRZrk05DwSnsJkhBRaM3OURtIaA==";
    name = "binding-linux-arm64-gnu-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-arm64-musl@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.70.0.tgz";
    hash = "sha512-WWOoV5W9Im3flVwOVrWn/2DUlOF8v5vcCip+kcNuaMpulRCh6nzzt1Su2vcL2F908YJIXNV3HvegbBHuyLwKHg==";
    name = "binding-linux-arm64-musl-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-ppc64-gnu@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-0.70.0.tgz";
    hash = "sha512-YUouneIqW+5n7aE8xx/zeZ6/utr/KH7oykcGoFyd8Uz8uh591T1oKlnoWA3BsRq/ZR42oY1w4MUYvS/0e/MQOA==";
    name = "binding-linux-ppc64-gnu-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-riscv64-gnu@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-0.70.0.tgz";
    hash = "sha512-iEnMf21S5aGVa4hViDGY8sAQ/AHyCu2JPyrQF8P06wtHhSkD1YJBeT4m/KiGewgf7+a5XCYSCRIPcRQa1xwEoQ==";
    name = "binding-linux-riscv64-gnu-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-riscv64-musl@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-0.70.0.tgz";
    hash = "sha512-91Sdniaj20fQzyMeCxMDzTP4c9s4RB8dGQ308xHhDR0n6U7+1Xq7N9klE7mfXq8iV3lRmIGSXi5X23Hn/0XX/g==";
    name = "binding-linux-riscv64-musl-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-s390x-gnu@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-0.70.0.tgz";
    hash = "sha512-uUV30M6E+2TKKGMaKiwfeL4RZrviHXlUxsrYJ/jFBb+1EZy+pnFT+hF73eeWdzh5NqPOAnw0iiMAIqjqiLZPFg==";
    name = "binding-linux-s390x-gnu-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-x64-gnu@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.70.0.tgz";
    hash = "sha512-ivMcX6kNDPhqtbOaBt/ItFlLlTlXNHLgRuNmxP6Na6UuYXRT10llpJcAPbGeRgjjb3Qzv4jwPp3fB0hui50WNQ==";
    name = "binding-linux-x64-gnu-0.70.0.tgz";
  };
  "@oxfmt/binding-linux-x64-musl@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-linux-x64-musl/-/binding-linux-x64-musl-0.70.0.tgz";
    hash = "sha512-w+S+fERxYmlZSyZlJK/U292FjyBoH8cCEj21/tYJX6atX5kNSn+HDkhlFQKT2zcMwUW0uAtUL/bOrlwJZwqRdA==";
    name = "binding-linux-x64-musl-0.70.0.tgz";
  };
  "@oxfmt/binding-openharmony-arm64@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-openharmony-arm64/-/binding-openharmony-arm64-0.70.0.tgz";
    hash = "sha512-Zlom1Xkx257R8bk4ZI4zJsrGno2opknz1+5v5baka3nn4FPyvNSdh8JUL4CdN1S1OWRMvJ9UJQ+RfIqGGCUEfA==";
    name = "binding-openharmony-arm64-0.70.0.tgz";
  };
  "@oxfmt/binding-win32-arm64-msvc@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-0.70.0.tgz";
    hash = "sha512-FQgPW5R17vzt7cgrJ8eG/dqX00o2xHsqFeLfw4xzA9FRHpN/DjFo9YDonvIIXGxiEuS9F/jZPnGO+KHNKuCo4Q==";
    name = "binding-win32-arm64-msvc-0.70.0.tgz";
  };
  "@oxfmt/binding-win32-ia32-msvc@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-0.70.0.tgz";
    hash = "sha512-ZfZublNhZ+XBndMiXhkiLlPE+XyGRDa0CweeTL6t1fZypfCh1LTg7e5CvnOeTBunq15MskOcRempumSPGAaCQA==";
    name = "binding-win32-ia32-msvc-0.70.0.tgz";
  };
  "@oxfmt/binding-win32-x64-msvc@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxfmt/binding-win32-x64-msvc/-/binding-win32-x64-msvc-0.70.0.tgz";
    hash = "sha512-HlIZEn+WzLQL0DszNzldiRl/DPRCX5R0Vkt6qeUPR1YHwy52hZZo4x6HoTOVmKRP2wUiwPGtKsihNY/f8KRaBg==";
    name = "binding-win32-x64-msvc-0.70.0.tgz";
  };
  "@oxlint-tsgolint/darwin-arm64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/darwin-arm64/-/darwin-arm64-7.0.2003.tgz";
    hash = "sha512-TgV33rXr6ueXBwvc+0nssUkTBSXHJxv77I8p4RCjDjCnvexHtmoPiudVRDfj3S3puMDdeQdHW6jdUgUPy3nr/w==";
    name = "darwin-arm64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/darwin-x64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/darwin-x64/-/darwin-x64-7.0.2003.tgz";
    hash = "sha512-hY3FMAjIaPDdK3FNxyRXRfHPOFeoBn6dmnLyKZgQ2IbTTD1adXhl6PfCIqHhCPvurigv7nf7mYuWZZ19MmJzmg==";
    name = "darwin-x64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/linux-arm64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/linux-arm64/-/linux-arm64-7.0.2003.tgz";
    hash = "sha512-eAET4JpyfBbg8SO0K74o4R55tEjVC292pIyxGOw2XGf8x/HrPNyxwQ478jMYOM54FIVOHc8sJ6VRHxluy6lucw==";
    name = "linux-arm64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/linux-x64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/linux-x64/-/linux-x64-7.0.2003.tgz";
    hash = "sha512-GXdyO/XyqDJ3s/llR/oOktLsYNjZtWSQBy0JMc+/0gsNPvTcseKPhn9c6KcFyWmnr6H4vljYALbujonqSzzEGw==";
    name = "linux-x64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/win32-arm64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/win32-arm64/-/win32-arm64-7.0.2003.tgz";
    hash = "sha512-TWauXnPfet0VgpmrstoAK58eJ4gbuwPUuUTQmYQAzE/RG1CpnxXtrKUJULf6lyerPE4KN3gM+DflIA1hOH+38Q==";
    name = "win32-arm64-7.0.2003.tgz";
  };
  "@oxlint-tsgolint/win32-x64@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint-tsgolint/win32-x64/-/win32-x64-7.0.2003.tgz";
    hash = "sha512-DoRmfe7j8VqNlukp8liRVW45GQDhzRccNenjD/pdzelgtffW47pCMd1xbJLkPaPbKnTwID3onn3VZlL7JbebEA==";
    name = "win32-x64-7.0.2003.tgz";
  };
  "@oxlint/binding-android-arm-eabi@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-android-arm-eabi/-/binding-android-arm-eabi-1.85.0.tgz";
    hash = "sha512-q2KO/Zso9UT+OMn0NF9ywn4E4t0MI3yxiDhNyhsQ7DyQJrC4FhFE4TXOi4bktFnOWXTMds8qZSbpv2XwRaNOBg==";
    name = "binding-android-arm-eabi-1.85.0.tgz";
  };
  "@oxlint/binding-android-arm64@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-android-arm64/-/binding-android-arm64-1.85.0.tgz";
    hash = "sha512-SxLN3ALjoT9NNdvpjEevGeHvfzTAFrF0NBYB5tzK7/GtCKMze3j1e/m/X2ozqGj2U9hfGG/dg/OG8vpVK4PiDA==";
    name = "binding-android-arm64-1.85.0.tgz";
  };
  "@oxlint/binding-darwin-arm64@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-darwin-arm64/-/binding-darwin-arm64-1.85.0.tgz";
    hash = "sha512-Y/Sup/J4f0f9UGsSd/xyCNTeWL+gepO63GBdEDAfue9nBsnk9zMmnIXx1O6b1V8C90vB5nucYNZ0pbMXAp8zJA==";
    name = "binding-darwin-arm64-1.85.0.tgz";
  };
  "@oxlint/binding-darwin-x64@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-darwin-x64/-/binding-darwin-x64-1.85.0.tgz";
    hash = "sha512-ApOSNC04ynpDTwvBD+//0wyfODRSbEzvRoKpX8teffmc27z8AockwSNeMXGJXn5KP85eahDgR/2llICWLkzcnw==";
    name = "binding-darwin-x64-1.85.0.tgz";
  };
  "@oxlint/binding-freebsd-x64@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-freebsd-x64/-/binding-freebsd-x64-1.85.0.tgz";
    hash = "sha512-bNrVrCOA/kHky3Tu79IXWXe5bhIgLXfUuUEDHlAGOHUk96MkvDZ1ecaQF19rwstrnaqfP1o9nBTqzIr9+ZHkUg==";
    name = "binding-freebsd-x64-1.85.0.tgz";
  };
  "@oxlint/binding-linux-arm-gnueabihf@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.85.0.tgz";
    hash = "sha512-NUrzOJ1s/EqsVvfn2L/1D8Wro2LPIZUbihL8kOJLh5fEdGEN3rdOGUYq3HwnUIL8sjpoP+4N6RaGrgmMJnaMPw==";
    name = "binding-linux-arm-gnueabihf-1.85.0.tgz";
  };
  "@oxlint/binding-linux-arm-musleabihf@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm-musleabihf/-/binding-linux-arm-musleabihf-1.85.0.tgz";
    hash = "sha512-UJXrAT3E/RWkEqXLIs2ehETja1qfgkPb+5gwLIIS+o/6cf+grHvoOXTa5997a/YNQfcJS0DRBTOfZt95cvOI1g==";
    name = "binding-linux-arm-musleabihf-1.85.0.tgz";
  };
  "@oxlint/binding-linux-arm64-gnu@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.85.0.tgz";
    hash = "sha512-lK40QLjI0HxigO7CjDDshEtfYIeiYS0020v5BHFPqN4uuQBQxd2K9LNom2dW15o9F1937quSCRVp4ZsVhdbYdg==";
    name = "binding-linux-arm64-gnu-1.85.0.tgz";
  };
  "@oxlint/binding-linux-arm64-musl@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.85.0.tgz";
    hash = "sha512-c2zbdBwGKreHXwRx3gWBuFGJxLhxgsg6YlZ+3H+RgRusU/UEV9jNwJ3HGYK+nRo0LvBa7mt6Kj86xoVotUo8cw==";
    name = "binding-linux-arm64-musl-1.85.0.tgz";
  };
  "@oxlint/binding-linux-ppc64-gnu@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.85.0.tgz";
    hash = "sha512-tlt/Hy8lZ97/lCPmCgw/B3k/mwh+BzaIPbPkldZEly7TwLmx0xe2CQcaW2g/rR0dOgS9JNGCZsMEqLhUNMGvaw==";
    name = "binding-linux-ppc64-gnu-1.85.0.tgz";
  };
  "@oxlint/binding-linux-riscv64-gnu@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-riscv64-gnu/-/binding-linux-riscv64-gnu-1.85.0.tgz";
    hash = "sha512-3tNR9Xey82X0zKuY1d8hJ6Rc9gwRDurmqGLnQZa5xqOXy8/YyiqFXjAtugkKLY82obOlpK1eSiDRlgcNPuxtIg==";
    name = "binding-linux-riscv64-gnu-1.85.0.tgz";
  };
  "@oxlint/binding-linux-riscv64-musl@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-riscv64-musl/-/binding-linux-riscv64-musl-1.85.0.tgz";
    hash = "sha512-wbGRd5PqCcjkJFHhZuZ2OBSUQY9czlQsoA/cQQB9JK/L9mC5MQgGoKAh+xd8QjA5V+0D3j+Qd1lAWn1I8zlelA==";
    name = "binding-linux-riscv64-musl-1.85.0.tgz";
  };
  "@oxlint/binding-linux-s390x-gnu@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.85.0.tgz";
    hash = "sha512-3Sn0kSrE4DPZCWV/8o+n4x3aFZxI9ulMnkYlwCbJ8eUVkwRK2IerohE/A/z3SNbCwoPFOCJmGE5Avrq0rrvdvQ==";
    name = "binding-linux-s390x-gnu-1.85.0.tgz";
  };
  "@oxlint/binding-linux-x64-gnu@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.85.0.tgz";
    hash = "sha512-JY2pxxYfB62bAGfejljVCqc44etItehPuAyaeSAdMuEMtwNA00ggMnS66lC1oIhos6oOXUkuU6mZ9bpFh3BqWg==";
    name = "binding-linux-x64-gnu-1.85.0.tgz";
  };
  "@oxlint/binding-linux-x64-musl@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-linux-x64-musl/-/binding-linux-x64-musl-1.85.0.tgz";
    hash = "sha512-5k74vZ6qJBjBHEOlBk9B/iv68Yu0F1Afw/vvT2ar6OGCqEeXLaSjXz2n/IPCbhLG22UoKoYEJTzpYraRdcp6PA==";
    name = "binding-linux-x64-musl-1.85.0.tgz";
  };
  "@oxlint/binding-openharmony-arm64@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-openharmony-arm64/-/binding-openharmony-arm64-1.85.0.tgz";
    hash = "sha512-GbAl5qt5TCkPLXTaIISZJnugrcBhra6rodcXc9jYt620UtdsTt71NlNmJmm0frxzFpd54x/G+MkitEJA8I/BoA==";
    name = "binding-openharmony-arm64-1.85.0.tgz";
  };
  "@oxlint/binding-win32-arm64-msvc@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.85.0.tgz";
    hash = "sha512-kjmws5MK0et2swk4ND85D7NVQyDHw162i6whtZDLUA/lo6FQyBZDcmMRCMcVZcNrAhIaftVb00x9ChGDOjjNJA==";
    name = "binding-win32-arm64-msvc-1.85.0.tgz";
  };
  "@oxlint/binding-win32-ia32-msvc@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-ia32-msvc/-/binding-win32-ia32-msvc-1.85.0.tgz";
    hash = "sha512-eSsIJx9n4yxvOqYTZyPEMyEXRmE60XH7xGAU7i0Qbsn1lf6Za3CWJ9aRd82oSFKXaxhp+sA6/yMJVRIpLpna6A==";
    name = "binding-win32-ia32-msvc-1.85.0.tgz";
  };
  "@oxlint/binding-win32-x64-msvc@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.85.0.tgz";
    hash = "sha512-pBebIPUpKKhWrhSMWhy8TdAZBewiXnfxmaAGxhzxM1068GagqFaTwgKlU6e+UyJ2sPR+VoHouhXuGJkQjsrDvA==";
    name = "binding-win32-x64-msvc-1.85.0.tgz";
  };
  "@oxlint/plugins@1.79.0" = fetchurl {
    url = "https://npm.flatt.tech/@oxlint/plugins/-/plugins-1.79.0.tgz";
    hash = "sha512-S0uyoxakDINJ4DPgqxGlEEvrdSMeQb7Z2lKVjxoY2gwsbZbfg2Xr8Klfeo5ZeraHmmdBCELFUHkSe6KEmBpMvg==";
    name = "plugins-1.79.0.tgz";
  };
  "@polka/url@1.0.0-next.29" = fetchurl {
    url = "https://npm.flatt.tech/@polka/url/-/url-1.0.0-next.29.tgz";
    hash = "sha512-wwQAWhWSuHaag8c4q/KN/vCoeOJYshAIvMQwD4GpSb3OiZklFfvAgmj0VCBBImRpuF/aFgIRzllXlVX93Jevww==";
    name = "url-1.0.0-next.29.tgz";
  };
  "@rolldown/binding-android-arm-eabi@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-android-arm-eabi/-/binding-android-arm-eabi-1.2.8.tgz";
    hash = "sha512-tN5aztYkKCte4i5SIrrz5yK/HMjEuCqCSCJa418jOV8tZ1cBY3YF2otxB1ktPxzsLA1BeTqwapK0bfjxNvHJVw==";
    name = "binding-android-arm-eabi-1.2.8.tgz";
  };
  "@rolldown/binding-android-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-android-arm64/-/binding-android-arm64-1.2.8.tgz";
    hash = "sha512-dIYTWl9XprMUiQFoc55KUyk/oS8SKYH3zFl0LTR7RT0Xj4hgSVyuJcroH8JUu8RcpF8fTB6E0aOwCkZoYPcDSQ==";
    name = "binding-android-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-darwin-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-darwin-arm64/-/binding-darwin-arm64-1.2.8.tgz";
    hash = "sha512-PCSDQGXD2IyTEFrcgPyBM8jJuGmrbCMuoIOXdbEGVemruKACXoLQJrb+A45Z0L5t1RQkdfJprAYPkikbh7dzdA==";
    name = "binding-darwin-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-darwin-x64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-darwin-x64/-/binding-darwin-x64-1.2.8.tgz";
    hash = "sha512-Uk7lRsGhPFHVX/sAUC6D5H9Ol30dFHd6iquokll2th3LpdJ3F5CzQB+7DHn0Ri2mG+U7k2zXiPHDrwZenXhwSA==";
    name = "binding-darwin-x64-1.2.8.tgz";
  };
  "@rolldown/binding-freebsd-x64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-freebsd-x64/-/binding-freebsd-x64-1.2.8.tgz";
    hash = "sha512-DjszaTEVogPqA5bYzsEeqDCQxbcp2fexQwKcRspYji2yzR68fCf+e4fx6kBSRDwX5/brZaHw/hWS9+A/+/w9sQ==";
    name = "binding-freebsd-x64-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm-gnueabihf@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.2.8.tgz";
    hash = "sha512-zmwa7FTmdzB6aaEEuuls18H6Ap5JmJPSoPTuXixeJZV6tG40SyLkApQtz1g8ptZtiEKqj9OM0oNLPh1AgvE31Q==";
    name = "binding-linux-arm-gnueabihf-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.2.8.tgz";
    hash = "sha512-KdYQDPHwJVnbFwdTGMgxsI9SqblBlz6STGM+w1We/d5B8OWWidYH0MwkU/uA1wM5fIpO2MkOVxXrNzzuZhw9ew==";
    name = "binding-linux-arm64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-arm64-musl@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.2.8.tgz";
    hash = "sha512-jFJTifHnNPY+yzOoNZQfSIysrVyXzEQPhPnOUjmD1bcQGHH6s7c8cViKWar8YplQImE5N9JRqMCLrM2CdxOrZA==";
    name = "binding-linux-arm64-musl-1.2.8.tgz";
  };
  "@rolldown/binding-linux-ppc64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.2.8.tgz";
    hash = "sha512-FhiOziBDWPBjbcmRzfLyIJnaP7AVMFXT7YCXPjXxj7wKU3vx24RjrCNN/zjvVa+N2vVoHJwCoUBvsrN/DG3zIA==";
    name = "binding-linux-ppc64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-s390x-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.2.8.tgz";
    hash = "sha512-WnHfADMzOV2Y55wlx1hzzQnar/wDt/VdvWSD99r18Mz9ylNieIGOkRx3UV21h7m/eJvjySYJkO26VvGNFkwsIQ==";
    name = "binding-linux-s390x-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-x64-gnu@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.2.8.tgz";
    hash = "sha512-H9tRr5ibfXFVLxbPOseVewewFpl28zcEdjRDt2FTUZU7odxP0gEv1ki4/kGmcGOh78oRwZuuQllGLZ9zTJp84g==";
    name = "binding-linux-x64-gnu-1.2.8.tgz";
  };
  "@rolldown/binding-linux-x64-musl@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-linux-x64-musl/-/binding-linux-x64-musl-1.2.8.tgz";
    hash = "sha512-UefiqfM3D6IVNlZ8tSGs9+Ejjud2T+oxO0IHADU45Y+lyEjD2dVFyZHbkfX0LUb5Zugo/oIv1eCO/KVYhgYJYA==";
    name = "binding-linux-x64-musl-1.2.8.tgz";
  };
  "@rolldown/binding-openharmony-arm64@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-openharmony-arm64/-/binding-openharmony-arm64-1.2.8.tgz";
    hash = "sha512-637Ke4kWSy6rp9cxQ9gMOXlxPgIw/c1beASV4M//3+9I4uwBVOOl74G+e3zyU3u19U7RkRl/HuewixZ/Z6+Rjg==";
    name = "binding-openharmony-arm64-1.2.8.tgz";
  };
  "@rolldown/binding-win32-arm64-msvc@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.2.8.tgz";
    hash = "sha512-xWBkPOF1Q9k/Gv1nQXnVdLxKu74jXppuOM4Z3mnypVUJJJwLsMl7hNJGRAUJoG8A5MgOI1ACKM+wBFxSJzKy4A==";
    name = "binding-win32-arm64-msvc-1.2.8.tgz";
  };
  "@rolldown/binding-win32-x64-msvc@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.2.8.tgz";
    hash = "sha512-uz2ZvfgXbxqNwijjjbxrnvALwpyODDcgc1T1N8N3rf/DXKQmaFwmB4LX4yyjggpwN2obdQLb2rgirX5ffCWYng==";
    name = "binding-win32-x64-msvc-1.2.8.tgz";
  };
  "@rolldown/pluginutils@1.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@rolldown/pluginutils/-/pluginutils-1.0.1.tgz";
    hash = "sha512-2j9bGt5Jh8hj+vPtgzPtl72j0yRxHAyumoo6TNfAjsLB04UtpSvPbPcDcBMxz7n+9CYB0c1GxQFxYRg2jimqGw==";
    name = "pluginutils-1.0.1.tgz";
  };
  "@testing-library/dom@10.4.1" = fetchurl {
    url = "https://npm.flatt.tech/@testing-library/dom/-/dom-10.4.1.tgz";
    hash = "sha512-o4PXJQidqJl82ckFaXUeoAW+XysPLauYI43Abki5hABd853iMhitooc6znOnczgbTYmEP6U6/y1ZyKAIsvMKGg==";
    name = "dom-10.4.1.tgz";
  };
  "@testing-library/user-event@14.6.7" = fetchurl {
    url = "https://npm.flatt.tech/@testing-library/user-event/-/user-event-14.6.7.tgz";
    hash = "sha512-MPCpX8bxe8zS+JmmTwLp8jd0dy1rAm60Te/SL8JrQM3qvQJcBOs1d7IefJMyZzqM3EWBrDn/LWDt1BCGu4ASfg==";
    name = "user-event-14.6.7.tgz";
  };
  "@tsconfig/node-ts@23.6.4" = fetchurl {
    url = "https://npm.flatt.tech/@tsconfig/node-ts/-/node-ts-23.6.4.tgz";
    hash = "sha512-37BMJvNQZ+vTgd1xG2TGBkJ6ENeT4eO4Wh2CHrnn0IwH7ybLFCzh4Uc//kc7UIvqiRac4uGdIc1meKOjMSlKzw==";
    name = "node-ts-23.6.4.tgz";
  };
  "@tsconfig/strictest@2.0.8" = fetchurl {
    url = "https://npm.flatt.tech/@tsconfig/strictest/-/strictest-2.0.8.tgz";
    hash = "sha512-XnQ7vNz5HRN0r88GYf1J9JJjqtZPiHt2woGJOo2dYqyHGGcd6OLGqSlBB6p1j9mpzja6Oe5BoPqWmeDx6X9rLw==";
    name = "strictest-2.0.8.tgz";
  };
  "@types/aria-query@5.0.4" = fetchurl {
    url = "https://npm.flatt.tech/@types/aria-query/-/aria-query-5.0.4.tgz";
    hash = "sha512-rfT93uj5s0PRL7EzccGMs3brplhcrghnDoV26NqKhCAS1hVo+WdNsPvE/yb6ilfr5hi2MEk6d5EWJTKdxg8jVw==";
    name = "aria-query-5.0.4.tgz";
  };
  "@types/chai@5.2.3" = fetchurl {
    url = "https://npm.flatt.tech/@types/chai/-/chai-5.2.3.tgz";
    hash = "sha512-Mw558oeA9fFbv65/y4mHtXDs9bPnFMZAL/jxdPFUpOHHIXX91mcgEHbS5Lahr+pwZFR8A7GQleRWeI6cGFC2UA==";
    name = "chai-5.2.3.tgz";
  };
  "@types/deep-eql@4.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@types/deep-eql/-/deep-eql-4.0.2.tgz";
    hash = "sha512-c9h9dVVMigMPc4bwTvC5dxqtqJZwQPePsWjPlpSOnojbor6pGqdk541lfA7AqFQr5pB1BRdq0juY9db81BwyFw==";
    name = "deep-eql-4.0.2.tgz";
  };
  "@types/estree@1.0.9" = fetchurl {
    url = "https://npm.flatt.tech/@types/estree/-/estree-1.0.9.tgz";
    hash = "sha512-GhdPgy1el4/ImP05X05Uw4cw2/M93BCUmnEvWZNStlCzEKME4Fkk+YpoA5OiHNQmoS7Cafb8Xa3Pya8m1Qrzeg==";
    name = "estree-1.0.9.tgz";
  };
  "@types/node@24.13.4" = fetchurl {
    url = "https://npm.flatt.tech/@types/node/-/node-24.13.4.tgz";
    hash = "sha512-YJ7EqCstVTzIr0fMr7qul/977en+pQHrfmuKIo6Zr9i75Be21dr3MovcfvGtyvi2HAUrRerWps5sMO9I7WaxDw==";
    name = "node-24.13.4.tgz";
  };
  "@typescript/typescript-aix-ppc64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-aix-ppc64/-/typescript-aix-ppc64-7.0.2.tgz";
    hash = "sha512-MTKKkWB7p/0E9xi1d1tHtZ5PiLkGEMIq88pK2CubZjOsLtYTLqhgIgi6zepFa+9GHZ6h05NMCkQxGKiPXMxXtQ==";
    name = "typescript-aix-ppc64-7.0.2.tgz";
  };
  "@typescript/typescript-darwin-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-darwin-arm64/-/typescript-darwin-arm64-7.0.2.tgz";
    hash = "sha512-gowzar9MwS/aRWp6f3a4KUqzRjAZjOsmGNCM6LcTgXum+dBfgsBVMN+AgvOCCbguXyick6LJhpBszxMebJ8syA==";
    name = "typescript-darwin-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-darwin-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-darwin-x64/-/typescript-darwin-x64-7.0.2.tgz";
    hash = "sha512-SZ9xZInqApNlNGc9s0W1VSsktYSOe9cFqNOIqmN1Gs8SmkjKZYFt017G4VwPxASInODuAdbTW7sXiFUf893RgA==";
    name = "typescript-darwin-x64-7.0.2.tgz";
  };
  "@typescript/typescript-freebsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-freebsd-arm64/-/typescript-freebsd-arm64-7.0.2.tgz";
    hash = "sha512-W5NH4y/J0plIIS5b2xvTEkU7JFxyqdMAOgf+Ilhl0vHQXKO5dZoxd+C/jEtq56c4F3wk71RB4BMRQ2XdI+bwYQ==";
    name = "typescript-freebsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-freebsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-freebsd-x64/-/typescript-freebsd-x64-7.0.2.tgz";
    hash = "sha512-UMGDx5sTpzNw3WiPebH7l90IWfJggEd+egHt/q6p7/Cm3zqoV7VxkGXt+3DxPIw8CcmvAB0j3sVVfbhX+M4Tpw==";
    name = "typescript-freebsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-arm64/-/typescript-linux-arm64-7.0.2.tgz";
    hash = "sha512-Qh4eU4/y3yDjnfjjyPYihMj5/ODIlmt+Bzu17OI+fiSRDW57QmU5SiN63exPRNJPKUzcc1INa1NXdrJ+MqHjUQ==";
    name = "typescript-linux-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-arm@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-arm/-/typescript-linux-arm-7.0.2.tgz";
    hash = "sha512-gffT3xPz9sR7j/YJExkyPntrI0P2EP9XbOyWzth2/Gs0RstK+90RBcO0ncXoXy/beYll1SXw846Nf2zdnEz0QQ==";
    name = "typescript-linux-arm-7.0.2.tgz";
  };
  "@typescript/typescript-linux-loong64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-loong64/-/typescript-linux-loong64-7.0.2.tgz";
    hash = "sha512-uEHck9i8hoAzXPiYRib1O7miOnz23SxIeVl6F4LXox+qov1K35jHcEW6VHKvZI+pyvl7fZEP4MCU5LYvIq1GuQ==";
    name = "typescript-linux-loong64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-mips64el@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-mips64el/-/typescript-linux-mips64el-7.0.2.tgz";
    hash = "sha512-R4KvAMnE43W5Qeqb0Ly56O3mWMWIAgsMyz36DCaycd5nbg/9kzm0liw3JocfRqyJY0KPmzFjbswozXyW0DnIYA==";
    name = "typescript-linux-mips64el-7.0.2.tgz";
  };
  "@typescript/typescript-linux-ppc64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-ppc64/-/typescript-linux-ppc64-7.0.2.tgz";
    hash = "sha512-DORx5b3sd/4S7eayxm4FQv+A7CrkUIGRaHiwI8oiHTAI1fAPWhF4J0vAlkC8biAlHSVVwxMQ3tjZ2/DVbnQiiA==";
    name = "typescript-linux-ppc64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-riscv64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-riscv64/-/typescript-linux-riscv64-7.0.2.tgz";
    hash = "sha512-wf0jqEDOjrPRnKwYRyyJDRo11KMbvMFrU+q4zqKyChODBzvlkbhNQfKvLxQCcwTpdDaXSHZTVuh0JoCrKCUMHQ==";
    name = "typescript-linux-riscv64-7.0.2.tgz";
  };
  "@typescript/typescript-linux-s390x@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-s390x/-/typescript-linux-s390x-7.0.2.tgz";
    hash = "sha512-IkwJc3L7yhytWd/ewjyxNDfOmswCm9GWMJT/ue/dU4aZNbwZeYAetq42VyLmsmSjvoX7z74X6ZaYCtzAr0EuGw==";
    name = "typescript-linux-s390x-7.0.2.tgz";
  };
  "@typescript/typescript-linux-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-linux-x64/-/typescript-linux-x64-7.0.2.tgz";
    hash = "sha512-EYdf2cNg7rgCWJnxCdJ+F3V39O8ihb37eHAu1LK8oAFizgTQbPOK7zHHXbPt8rX24COqODXeI3sIf0fCXG7H/A==";
    name = "typescript-linux-x64-7.0.2.tgz";
  };
  "@typescript/typescript-netbsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-netbsd-arm64/-/typescript-netbsd-arm64-7.0.2.tgz";
    hash = "sha512-+polYF4MF04aPpO5FTkHran9yUQDSXqy5GiSDKpsll5jy3l3+g9QLhpf39T+ePtefhXLOGrLl0QIjkQP6VnelA==";
    name = "typescript-netbsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-netbsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-netbsd-x64/-/typescript-netbsd-x64-7.0.2.tgz";
    hash = "sha512-8YIT0EHM/3dq10ZOVF/A7pc/YSMtbcecct4rWtexrnSCHOPcpC2KTLXfTCR6vDpnSiY12heNb1GiN/wu+T/FyA==";
    name = "typescript-netbsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-openbsd-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-openbsd-arm64/-/typescript-openbsd-arm64-7.0.2.tgz";
    hash = "sha512-APT8+ClYnuYm1u9+kgGXoMj2VzWzcymwh2gNSQVySHfkRDGOTVkoWLjCmOQSaO+PoqQ57B0flRp9SA+7GnnkzQ==";
    name = "typescript-openbsd-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-openbsd-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-openbsd-x64/-/typescript-openbsd-x64-7.0.2.tgz";
    hash = "sha512-yX7s+Q0Dln0Dt9tEzZsAjXXR/+ytBM7AlglaqyeMPxQszJ1JhlJdZ6jLA+IzldHtflX81em7lDao1xXu+aRRkg==";
    name = "typescript-openbsd-x64-7.0.2.tgz";
  };
  "@typescript/typescript-sunos-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-sunos-x64/-/typescript-sunos-x64-7.0.2.tgz";
    hash = "sha512-dLJDGaLZ1D4HPQn62u1n8mBDkJREwMsAkCdkwd4Ieqw+x3TUyTsqY0YiBCtE6H6OzzgGk3iuZ3vFWRS+E8/d1g==";
    name = "typescript-sunos-x64-7.0.2.tgz";
  };
  "@typescript/typescript-win32-arm64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-win32-arm64/-/typescript-win32-arm64-7.0.2.tgz";
    hash = "sha512-Gyl1Vy6OsWesLzmq+EP0Fb7b4Nid5232AvcA2SFcdYreldpNtYFFofPjnt62y9hQy7VTaZp65ICJjuAQRaVcIQ==";
    name = "typescript-win32-arm64-7.0.2.tgz";
  };
  "@typescript/typescript-win32-x64@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/@typescript/typescript-win32-x64/-/typescript-win32-x64-7.0.2.tgz";
    hash = "sha512-0BQ3HkAHHlKLSp1qRvf3SUhGpGsDuhB/jgFw75guyqbxJqEaS0Cw/VFO8i2nHglJUzQCRtMMR/IBAKE3ETMC4g==";
    name = "typescript-win32-x64-7.0.2.tgz";
  };
  "@vitest/browser-preview@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/browser-preview/-/browser-preview-5.0.1.tgz";
    hash = "sha512-NagNnZD6A8ccl+pycLWX2b/e9YJtH5NuDUyiiadQjptMRuZVBAB9r9I3itdKm6exxtcl+rOTv2rWt6vu5uOm1A==";
    name = "browser-preview-5.0.1.tgz";
  };
  "@vitest/browser@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/browser/-/browser-5.0.1.tgz";
    hash = "sha512-s2UroEhP2BZPoen1qrXXTtVqnUcs6y2sxMLGCZ8tZDkH2iM/6tTC2GVTPCgF+oVF3X5M6wC/X2O0MvvoHNmH0Q==";
    name = "browser-5.0.1.tgz";
  };
  "@vitest/mocker@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/mocker/-/mocker-5.0.1.tgz";
    hash = "sha512-6K1DoBNAPGvuOcSsGA4D6x+5zEEff/KmOOP3uetT2TrGpVfI+HRHRnJJfKi5ib/g1vx8IYHQD8s0pbJz8WQI7Q==";
    name = "mocker-5.0.1.tgz";
  };
  "@vitest/pretty-format@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/pretty-format/-/pretty-format-5.0.1.tgz";
    hash = "sha512-6guWwj5d9bguuefTOvJoq387tfpkzSv554YdUEGzjJH2PnnmvzTLQ1UQSuAk5wBFVhf2CUmy/S/palOcb6dmpA==";
    name = "pretty-format-5.0.1.tgz";
  };
  "@vitest/snapshot@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/snapshot/-/snapshot-5.0.1.tgz";
    hash = "sha512-aEW4fuQVg1i3fnC781qvwxC5QNptUvb+JjIUfX1WuWJqkjCgpiU8+I89mMcJmxOPLdaGAwEPFFVk02rGKYexvw==";
    name = "snapshot-5.0.1.tgz";
  };
  "@vitest/spy@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/spy/-/spy-5.0.1.tgz";
    hash = "sha512-rbto/mF/SGERxEgYOek7Xm6B9b+y+mVoo+f4b2LymYO8zM1b7uB5nHuhVMTP2hxdzgxvGiZYGxGIaMvL5y180Q==";
    name = "spy-5.0.1.tgz";
  };
  "@vitest/ui@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/ui/-/ui-5.0.1.tgz";
    hash = "sha512-7PvQu/X9/pQoHYfNLAYL22qsD4/+sx2k7zpUA7XvjW0sc40r3/r0lGZ2fsEyOHMuO8Q1KjiO1QQVjJdnWUy/WQ==";
    name = "ui-5.0.1.tgz";
  };
  "@vitest/utils@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/@vitest/utils/-/utils-5.0.1.tgz";
    hash = "sha512-E9+yEA+jsfaoxZcUHFzEqUrQcoNh2EwrPT5efIqkUPUwD5Ua2Li9BRWaYeRwvzvdLgTSVrre8oKNeyrfg7KkdQ==";
    name = "utils-5.0.1.tgz";
  };
  "@voidzero-dev/vite-plus-core@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-core/-/vite-plus-core-1.0.0.tgz";
    hash = "sha512-GHCd6d7h3JVojI/yxe/EAHwX5gn+OI7G932VBnYoTiwATLJrvHOs+okx7Ek2LGEJ57NJRENwCFgVYefjwPLfFA==";
    name = "vite-plus-core-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-darwin-arm64@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-darwin-arm64/-/vite-plus-darwin-arm64-1.0.0.tgz";
    hash = "sha512-lR+0rHOCYQTUo4Un0Sy14Xi1NBqoPXRnhsRyc0Joe53fomZ+wPtgErk15tkvWQdSLGNOr8hDDWJKo/kzI0Y37w==";
    name = "vite-plus-darwin-arm64-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-darwin-x64@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-darwin-x64/-/vite-plus-darwin-x64-1.0.0.tgz";
    hash = "sha512-MW3YnWpYP6wxvpd5KLFYTdtHTcAVnN0mVoLrmA9KCKWfOzO8nanr8hpuyEIdLMQT3r/7VNKRvgROI0CZZDP9/A==";
    name = "vite-plus-darwin-x64-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-arm64-gnu@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-arm64-gnu/-/vite-plus-linux-arm64-gnu-1.0.0.tgz";
    hash = "sha512-n4onkD4oT+g4jLj9rR37TM4i2IbaYvIiU68p1A/5KrwnIHzbv2maO0BqBYdIRnBy1Mil8pIx9HsT8riWCjZeTw==";
    name = "vite-plus-linux-arm64-gnu-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-arm64-musl@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-arm64-musl/-/vite-plus-linux-arm64-musl-1.0.0.tgz";
    hash = "sha512-EZfgINa0FL/eIsLkL3MfQz7+Dc4VDAeIrf1UZDlitt//8NIOqI6nVMPnIFzMZThaIncIose+cVWsEkKLAKMM/A==";
    name = "vite-plus-linux-arm64-musl-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-x64-gnu@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-x64-gnu/-/vite-plus-linux-x64-gnu-1.0.0.tgz";
    hash = "sha512-R6+/oVLCSEvatOG1utYo0d0I++QPjWuRt2moD21+UUu2mQ8VyZHaaQLgoxrQG9shA9o0RBDmwxhGUXL20Rk1FA==";
    name = "vite-plus-linux-x64-gnu-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-linux-x64-musl@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-linux-x64-musl/-/vite-plus-linux-x64-musl-1.0.0.tgz";
    hash = "sha512-B1Ottn22hn9RZ6XIVrWCXAAMfCOQRJ4KWoKbPL4JxC+UgvEiY9kC1ZFPqEAI89zIbW8eLdP3BeT14NQ0h1rtxw==";
    name = "vite-plus-linux-x64-musl-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-win32-arm64-msvc@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-win32-arm64-msvc/-/vite-plus-win32-arm64-msvc-1.0.0.tgz";
    hash = "sha512-XXK6N5xMkGVIcqMaVDjqDh44z0Z00DA8dYn2BWUkFOQflUU1Z3IWt+bPm/1Y7LjkwBWj5qD2zsQY1ANDCeX9QA==";
    name = "vite-plus-win32-arm64-msvc-1.0.0.tgz";
  };
  "@voidzero-dev/vite-plus-win32-x64-msvc@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/@voidzero-dev/vite-plus-win32-x64-msvc/-/vite-plus-win32-x64-msvc-1.0.0.tgz";
    hash = "sha512-XabdwdAsJ9QqEVSpSOuiiyJjiEwbwOspGahei9svQUGjs7e8MPuj4y/ltBHJZpyCBdZI6fhlc7Xaps9bUtl7Og==";
    name = "vite-plus-win32-x64-msvc-1.0.0.tgz";
  };
  "@yuku-codegen/binding-android-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-android-arm64/-/binding-android-arm64-0.9.5.tgz";
    hash = "sha512-jrOY5WM+AaAqkv51fHP1x28ifto4WgcZVzodLUyMU1jMWn5Sq+VciRdk/n8E0Ey5w4p4cWWE+m5GfXWOYh7Kzw==";
    name = "binding-android-arm64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-darwin-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-darwin-arm64/-/binding-darwin-arm64-0.9.5.tgz";
    hash = "sha512-4O4lkCQIzPZGjiNB1GORSI6hBECbiiSBS/APZXPvNKYH+nhY4uuqv03LNXA+SET3hoBjvr95P5rIhY8KQaQUBA==";
    name = "binding-darwin-arm64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-darwin-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-darwin-x64/-/binding-darwin-x64-0.9.5.tgz";
    hash = "sha512-9EvoUO0SEhD6/d8VHdWuPerepPMSR1y84+UEgz8Un1Ope14Oe7xMvePpEQLTLovoIFZ8Zg3iZ8z8E11pZMqC3g==";
    name = "binding-darwin-x64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-freebsd-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-freebsd-x64/-/binding-freebsd-x64-0.9.5.tgz";
    hash = "sha512-HqT78WwgHTmp8lwujoUa9CrIortX4DdpuiVC18ZPSGvuuJf4ylpIEI6QrQEM78Zwz3muhAWAOXZ5irdiYY+AyA==";
    name = "binding-freebsd-x64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm-gnu/-/binding-linux-arm-gnu-0.9.5.tgz";
    hash = "sha512-QJXwIW6Ms3QIawbcBIedmrmXnfdpuAOjZJ/eAABq5XTzWvSxZ7lutu9W5yIHahlaTaFnBo7ikrVMD1szLTpPUw==";
    name = "binding-linux-arm-gnu-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm-musl/-/binding-linux-arm-musl-0.9.5.tgz";
    hash = "sha512-eHbFy3IHGb+IYarrYwAo0yWSEQV3eAmEn6VrsKA6I1Wy1YPJxWqSJlV69JhqsHtJuJlljUIF3ex0y46yaKIu9w==";
    name = "binding-linux-arm-musl-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.9.5.tgz";
    hash = "sha512-ByoJMbySTaDhjAXSu8q6Lh7HKg3YoesXpcT72aYk0Aiw4PCznmY4ybpLTq0RCvp0RIPhFm/6yECFiGBwyCC1nw==";
    name = "binding-linux-arm64-gnu-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-arm64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.9.5.tgz";
    hash = "sha512-gD9vfXIoBw1toSxhO9rgmSu/FEfy3PMznJAxVjIuH8DrWEiDKXmJO0pJKfj1Ltbe/TmtWVZR+TjISqeSIGQzMg==";
    name = "binding-linux-arm64-musl-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-x64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.9.5.tgz";
    hash = "sha512-BARvdnvqMGjOr5Iel2JH+9H5vAIE0R6H0Z2fsT02xrvmI/1ZXNB8lkuX+ZGevPhZb3zJ9WeC/R8JZstrsUOK5g==";
    name = "binding-linux-x64-gnu-0.9.5.tgz";
  };
  "@yuku-codegen/binding-linux-x64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-linux-x64-musl/-/binding-linux-x64-musl-0.9.5.tgz";
    hash = "sha512-x8flcevS1fbb7ESrmpOY/pON4eInSaE/7Ktjqx2udOE2W33BNSZmJuwpyUgo54AoHNqrcaM7szqydyJn5fNvew==";
    name = "binding-linux-x64-musl-0.9.5.tgz";
  };
  "@yuku-codegen/binding-win32-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-win32-arm64/-/binding-win32-arm64-0.9.5.tgz";
    hash = "sha512-KOL/rBatWqH4ZpCNoF8ZtSNdOJbAxBJLmk/VeRciepGROPTbPum1A9t67GpFgOU7qrkUWlPJdJ+KHKbvbmOt+w==";
    name = "binding-win32-arm64-0.9.5.tgz";
  };
  "@yuku-codegen/binding-win32-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-codegen/binding-win32-x64/-/binding-win32-x64-0.9.5.tgz";
    hash = "sha512-FxENahEjWSan59Syh/us/Kf4wNq8qrJLFJ3R2N4Oiwtb6yNdz/rWLNTIoNSssnsp7IoWJdUP6o/Z8ppg7lXMcg==";
    name = "binding-win32-x64-0.9.5.tgz";
  };
  "@yuku-parser/binding-android-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-android-arm64/-/binding-android-arm64-0.9.5.tgz";
    hash = "sha512-A2JCFCSHfnficqYEw4Iujpx7XrkMM3UfFcgJFmYpZSo9zM4nyhmdIIE0FogSduuU60lhM0/UcfuUBXIVNBMlGQ==";
    name = "binding-android-arm64-0.9.5.tgz";
  };
  "@yuku-parser/binding-darwin-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-darwin-arm64/-/binding-darwin-arm64-0.9.5.tgz";
    hash = "sha512-3PiyU+Eare4YuKaQ22N98/yAiROPY5o/NQJHraICzDvk4pgS+m+bgLKOvkGBRn33OnV95Vdv1Mn38b+MQHpULQ==";
    name = "binding-darwin-arm64-0.9.5.tgz";
  };
  "@yuku-parser/binding-darwin-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-darwin-x64/-/binding-darwin-x64-0.9.5.tgz";
    hash = "sha512-blFMAFI7AInI83XaiOF8cIeiRM46Nz9EfpZtZPRLbKxSA9aAr5v8aHYpmfN6NoyXxAv/10pwS4gsAuc1W6fy5Q==";
    name = "binding-darwin-x64-0.9.5.tgz";
  };
  "@yuku-parser/binding-freebsd-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-freebsd-x64/-/binding-freebsd-x64-0.9.5.tgz";
    hash = "sha512-TsNuL4qsZdO0tHp5GW43Y5fHeLPpPHA675wdcPNTcdq2ZO5AvsQWFFoiDg8CH4oBktfsQ9tdvKhjLnLYwKvp4g==";
    name = "binding-freebsd-x64-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm-gnu/-/binding-linux-arm-gnu-0.9.5.tgz";
    hash = "sha512-b0afYK5gHeV8RdmOcqAlgM8ONsye4cax4DMnIBaoJyPMd1UTGvTbpkqQcPVdhmHlcfcGVGMV1laeVovlr/dscw==";
    name = "binding-linux-arm-gnu-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm-musl/-/binding-linux-arm-musl-0.9.5.tgz";
    hash = "sha512-fD3lKzl+r6j6n8DwiMY53qnh5DLqD8KJjCp+NbVud54Nnh3Q9Wprqss3YzyMHP3NSJk663Wlg1E1X5qOuFVFig==";
    name = "binding-linux-arm-musl-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-0.9.5.tgz";
    hash = "sha512-aRU/aCphV1MWCl/lvI6NX8LgucHQ68Fx+vz7NBb/5MEr2EuzCxiPOQqeFcMdWh+2AED/p0AvAREch0c+cSnlhA==";
    name = "binding-linux-arm64-gnu-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-arm64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-arm64-musl/-/binding-linux-arm64-musl-0.9.5.tgz";
    hash = "sha512-5+Guro0l8H473YXlEjVNBRLN/IbPbJdnQh1zo0OLt49xxnON+XMJRRaEyTOTfkn9QSRg0+BhEKGR4W9Gu2uZJQ==";
    name = "binding-linux-arm64-musl-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-x64-gnu@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-x64-gnu/-/binding-linux-x64-gnu-0.9.5.tgz";
    hash = "sha512-pwwSyV9q+GlvzSXlsMZBMlgk22L5bud714/vqZCdeUTivzeUVltQzUaf3IQXOGXdpc59JYTeuMCtbGquaAUoCA==";
    name = "binding-linux-x64-gnu-0.9.5.tgz";
  };
  "@yuku-parser/binding-linux-x64-musl@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-linux-x64-musl/-/binding-linux-x64-musl-0.9.5.tgz";
    hash = "sha512-z18j6JN3lBHH8vzN7gG1M8fI0nlgItSfnC9PfbmUbt97iHViKfw2iA2G9fGwRMe5LyPRZBrejIlapbygPbpdaw==";
    name = "binding-linux-x64-musl-0.9.5.tgz";
  };
  "@yuku-parser/binding-win32-arm64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-win32-arm64/-/binding-win32-arm64-0.9.5.tgz";
    hash = "sha512-s6Gwttb1dQvtPX6Bgkw+UPC9IO3UBDXc6Zezog8MMgvu3UfJBBB9TQqKBX/2quu0Eyh+lLSAyNlIyyecaagUPg==";
    name = "binding-win32-arm64-0.9.5.tgz";
  };
  "@yuku-parser/binding-win32-x64@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-parser/binding-win32-x64/-/binding-win32-x64-0.9.5.tgz";
    hash = "sha512-FrERt9YWatY3bJfSUdi4YWY+6iQcyo3MzCC821BxlWM5TFZEHijnpz/bknR79VHlXY/9CvXz8ZlaAGPsTtN3nw==";
    name = "binding-win32-x64-0.9.5.tgz";
  };
  "@yuku-toolchain/types@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/@yuku-toolchain/types/-/types-0.9.5.tgz";
    hash = "sha512-KiuLNNgX9uNealaWAR+G3/cMXnRk9x4TY2EkYe/KIag+UPdwiA0RRf1hr1WAxzTP8KGzCTkqUdLPvqh32sEO3w==";
    name = "types-0.9.5.tgz";
  };
  "ansi-regex@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/ansi-regex/-/ansi-regex-5.0.1.tgz";
    hash = "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
    name = "ansi-regex-5.0.1.tgz";
  };
  "ansi-styles@5.2.0" = fetchurl {
    url = "https://npm.flatt.tech/ansi-styles/-/ansi-styles-5.2.0.tgz";
    hash = "sha512-Cxwpt2SfTzTtXcfOlzGEee8O+c+MmUgGrNiBcXnuWxuFJHe6a5Hz7qwhwe5OgaSYI0IJvkLqWX1ASG+cJOkEiA==";
    name = "ansi-styles-5.2.0.tgz";
  };
  "aria-query@5.3.0" = fetchurl {
    url = "https://npm.flatt.tech/aria-query/-/aria-query-5.3.0.tgz";
    hash = "sha512-b0P0sZPKtyu8HkeRAfCq0IfURZK+SuwMjY1UXGBU27wpAiTwQAIlq56IbIO+ytk/JjS1fMR14ee5WBBfKi5J6A==";
    name = "aria-query-5.3.0.tgz";
  };
  "assertion-error@2.0.1" = fetchurl {
    url = "https://npm.flatt.tech/assertion-error/-/assertion-error-2.0.1.tgz";
    hash = "sha512-Izi8RQcffqCeNVgFigKli1ssklIbpHnCYc6AknXGYoB6grJqyeby7jv12JUQgmTAnIDnbck1uxksT4dzN3PWBA==";
    name = "assertion-error-2.0.1.tgz";
  };
  "chai@6.2.2" = fetchurl {
    url = "https://npm.flatt.tech/chai/-/chai-6.2.2.tgz";
    hash = "sha512-NUPRluOfOiTKBKvWPtSD4PhFvWCqOi0BGStNWs57X9js7XGTprSmFoz5F0tWhR4WPjNeR9jXqdC7/UpSJTnlRg==";
    name = "chai-6.2.2.tgz";
  };
  "convert-source-map@2.0.0" = fetchurl {
    url = "https://npm.flatt.tech/convert-source-map/-/convert-source-map-2.0.0.tgz";
    hash = "sha512-Kvp459HrV2FEJ1CAsi1Ku+MY3kasH19TFykTz2xWmMeq6bk2NU3XXvfJ+Q61m0xktWwt+1HSYf3JZsTms3aRJg==";
    name = "convert-source-map-2.0.0.tgz";
  };
  "dequal@2.0.3" = fetchurl {
    url = "https://npm.flatt.tech/dequal/-/dequal-2.0.3.tgz";
    hash = "sha512-0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
    name = "dequal-2.0.3.tgz";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://npm.flatt.tech/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
    name = "detect-libc-2.1.2.tgz";
  };
  "dom-accessibility-api@0.5.16" = fetchurl {
    url = "https://npm.flatt.tech/dom-accessibility-api/-/dom-accessibility-api-0.5.16.tgz";
    hash = "sha512-X7BJ2yElsnOJ30pZF4uIIDfBEVgF4XEBxL9Bxhy6dnrm5hkzqmsWHGTiHqRiITNhMyFLyAiWndIJP7Z1NTteDg==";
    name = "dom-accessibility-api-0.5.16.tgz";
  };
  "es-module-lexer@2.3.2" = fetchurl {
    url = "https://npm.flatt.tech/es-module-lexer/-/es-module-lexer-2.3.2.tgz";
    hash = "sha512-poHGpORABojJJucnV9KbOavETW8lBVnphkW77ER5/BQ5Fz7oXSoCNek7IH3vR5nRjdsEz926ibFYX8KtLQmdyw==";
    name = "es-module-lexer-2.3.2.tgz";
  };
  "estree-walker@3.0.3" = fetchurl {
    url = "https://npm.flatt.tech/estree-walker/-/estree-walker-3.0.3.tgz";
    hash = "sha512-7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
    name = "estree-walker-3.0.3.tgz";
  };
  "expect-type@1.4.0" = fetchurl {
    url = "https://npm.flatt.tech/expect-type/-/expect-type-1.4.0.tgz";
    hash = "sha512-KfYbmpRm0VbLjEvVa9yGwCi9GI34xvi7A/HXYWQO65CSD2u3MczUJSuwXKFIxlGsgBQizV9q5J9NHj4VG0n+pA==";
    name = "expect-type-1.4.0.tgz";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://npm.flatt.tech/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
    name = "fdir-6.5.0.tgz";
  };
  "fflate@0.8.3" = fetchurl {
    url = "https://npm.flatt.tech/fflate/-/fflate-0.8.3.tgz";
    hash = "sha512-tbZNuJrLwGUp3zshBtdy4W+ORxZuIh8a5ilyIEQDC5rY1f3U20JMry0Ll3WBzU58EZKsEuJFXhb5gwv8CsPvgA==";
    name = "fflate-0.8.3.tgz";
  };
  "flatted@3.4.4" = fetchurl {
    url = "https://npm.flatt.tech/flatted/-/flatted-3.4.4.tgz";
    hash = "sha512-5+ybhBZANEJxaH3X5evAFatUxLfEHSr7n6kYJ+1Qd0mUqr4eu9gIf6GDbWHf8RJijHrjjO8G+la14SlL2SeS1Q==";
    name = "flatted-3.4.4.tgz";
  };
  "fsevents@2.3.3" = fetchurl {
    url = "https://npm.flatt.tech/fsevents/-/fsevents-2.3.3.tgz";
    hash = "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==";
    name = "fsevents-2.3.3.tgz";
  };
  "js-tokens@4.0.0" = fetchurl {
    url = "https://npm.flatt.tech/js-tokens/-/js-tokens-4.0.0.tgz";
    hash = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
    name = "js-tokens-4.0.0.tgz";
  };
  "lightningcss-android-arm64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-android-arm64/-/lightningcss-android-arm64-1.33.0.tgz";
    hash = "sha512-gEpRTalKdosp4Bb8qWtc2iOgE5SeIHlpS1up9bFq2wAyYhl1UdTObYiHe98zEM9SQvSoqQZ1IQD0JNpg3Ml5pg==";
    name = "lightningcss-android-arm64-1.33.0.tgz";
  };
  "lightningcss-darwin-arm64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-darwin-arm64/-/lightningcss-darwin-arm64-1.33.0.tgz";
    hash = "sha512-Sciaz8eenNTKn9b3t7+xr0ipTp9YxKQY4npwQ3mrRuL0BAVHBLyZxofhaKBAVtzmtRZ/zTyo0/to4B1uWG/Djg==";
    name = "lightningcss-darwin-arm64-1.33.0.tgz";
  };
  "lightningcss-darwin-x64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-darwin-x64/-/lightningcss-darwin-x64-1.33.0.tgz";
    hash = "sha512-Z5UPAxzrjlWNNyGy6i65cJzzvgJ5D3T6wMvs+gWpY9d7qRhANrxqAp6LhxIgZhWEw18RfJTGcRxjuLIBr+m8XQ==";
    name = "lightningcss-darwin-x64-1.33.0.tgz";
  };
  "lightningcss-freebsd-x64@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-freebsd-x64/-/lightningcss-freebsd-x64-1.33.0.tgz";
    hash = "sha512-QQM/Ti/hQajJwCY+RiWuCZ9sdtI/XQk7nDK5vC8kkdwixezOlDgvDx7+RT+QjK6FcFT4MpsuoBnHIo/O3StRRg==";
    name = "lightningcss-freebsd-x64-1.33.0.tgz";
  };
  "lightningcss-linux-arm-gnueabihf@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm-gnueabihf/-/lightningcss-linux-arm-gnueabihf-1.33.0.tgz";
    hash = "sha512-N7FVBe6iS24MlM6R/4RBTxGhQheZGs7tiQ9U32UtF75NzP5Q7xWPRqLBCKxlRQRk3rY1jCIPLzx7WzOhuUIRLQ==";
    name = "lightningcss-linux-arm-gnueabihf-1.33.0.tgz";
  };
  "lightningcss-linux-arm64-gnu@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm64-gnu/-/lightningcss-linux-arm64-gnu-1.33.0.tgz";
    hash = "sha512-j2v/itmy4HlNxlc6voKXYgBqNi0Ng2LShg4z7GufpEgs05P+2suBVyi9I6YHq5uoVFx9ETin3eCEhLVyXGQnKg==";
    name = "lightningcss-linux-arm64-gnu-1.33.0.tgz";
  };
  "lightningcss-linux-arm64-musl@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-arm64-musl/-/lightningcss-linux-arm64-musl-1.33.0.tgz";
    hash = "sha512-yiO5ROMuYQgXbC60yjZU5CYSFZGKXL0HFATXt9mHJn1+zW55oCtMI9NfcVhYLMFDL7gV7oBPon/EmMMGg2OvtQ==";
    name = "lightningcss-linux-arm64-musl-1.33.0.tgz";
  };
  "lightningcss-linux-x64-gnu@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.33.0.tgz";
    hash = "sha512-ar+Ju7LmcN0Jo4FpL4hpFybwNG9/3A/Br5KW2n2jyODg3MEZXaDYADdemoNS+BDNfMgKvylJLj4S5tyRActuAg==";
    name = "lightningcss-linux-x64-gnu-1.33.0.tgz";
  };
  "lightningcss-linux-x64-musl@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-linux-x64-musl/-/lightningcss-linux-x64-musl-1.33.0.tgz";
    hash = "sha512-RYiYbkokw0trfKqqzfF55lginwEPrD3OJDfTuJzFs1MK6iFnDenaz1fqLLtX4ITG3OktJQXOeTaw1awrBAlZPw==";
    name = "lightningcss-linux-x64-musl-1.33.0.tgz";
  };
  "lightningcss-win32-arm64-msvc@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-win32-arm64-msvc/-/lightningcss-win32-arm64-msvc-1.33.0.tgz";
    hash = "sha512-1K+MPfLSFVpphzpdbfkhlWk6wBrTObBzS2T6db10PNOZgR9GoVsAWzwNyuhUYYbTp23j+4RrncfujZ4uAzXvwA==";
    name = "lightningcss-win32-arm64-msvc-1.33.0.tgz";
  };
  "lightningcss-win32-x64-msvc@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss-win32-x64-msvc/-/lightningcss-win32-x64-msvc-1.33.0.tgz";
    hash = "sha512-OlEICDx/Xl0FqSp4bry8zFnCvGpig3Gl4gCquvYwHuqJKEC1+n9NgDniFvqHGmMv1ZkqDJrDqKKSykTDX+ehuA==";
    name = "lightningcss-win32-x64-msvc-1.33.0.tgz";
  };
  "lightningcss@1.33.0" = fetchurl {
    url = "https://npm.flatt.tech/lightningcss/-/lightningcss-1.33.0.tgz";
    hash = "sha512-WkUDrojuJs0xkgGf2udWxa3yGBRxPtxUkB79i6aCZLRgc7PM8fZe9TosfPDcvEpQZbuFASnHYmRLBLUbmLOIIA==";
    name = "lightningcss-1.33.0.tgz";
  };
  "lz-string@1.5.0" = fetchurl {
    url = "https://npm.flatt.tech/lz-string/-/lz-string-1.5.0.tgz";
    hash = "sha512-h5bgJWpxJNswbU7qCrV0tIKQCaS3blPDrqKWx+QxzuzL1zGUzij9XCWLrSLsJPu5t+eWA/ycetzYAO5IOMcWAQ==";
    name = "lz-string-1.5.0.tgz";
  };
  "magic-string@1.4.3" = fetchurl {
    url = "https://npm.flatt.tech/magic-string/-/magic-string-1.4.3.tgz";
    hash = "sha512-z12OxmaPGE0F4xlpGdjuAUckipLpQlTAuAmyGhNoD7ODpYUzvDfvtxUbjM/jwznyP178oju/KDdyi220wNJ0RQ==";
    name = "magic-string-1.4.3.tgz";
  };
  "mrmime@2.0.1" = fetchurl {
    url = "https://npm.flatt.tech/mrmime/-/mrmime-2.0.1.tgz";
    hash = "sha512-Y3wQdFg2Va6etvQ5I82yUhGdsKrcYox6p7FfL1LbK2J4V01F9TGlepTIhnK24t7koZibmg82KGglhA1XK5IsLQ==";
    name = "mrmime-2.0.1.tgz";
  };
  "nanoid@3.3.19" = fetchurl {
    url = "https://npm.flatt.tech/nanoid/-/nanoid-3.3.19.tgz";
    hash = "sha512-Y2tUNy4ouw6tq5oDSKeQYGOyhkUBhNOcGV/02KC+6kd9eDGqdZd++mjMiIDilrBYvjEnCYvVtsuHCuP+okSfug==";
    name = "nanoid-3.3.19.tgz";
  };
  "obug@2.2.1" = fetchurl {
    url = "https://npm.flatt.tech/obug/-/obug-2.2.1.tgz";
    hash = "sha512-XrsrhT5sybtKI6wakr2SPOlGZWWYbUXZ7a0jT8/QOeAPau+1X/bSegNe5YR75oJmEZQbKningirmGOEJCIk61Q==";
    name = "obug-2.2.1.tgz";
  };
  "oxfmt@0.70.0" = fetchurl {
    url = "https://npm.flatt.tech/oxfmt/-/oxfmt-0.70.0.tgz";
    hash = "sha512-IsHxZ4y0wQLLMhnrJblBJgZsLDzfULrJnAw5j/QqsTlMa/m3AqsbToi+W71uhBGaqlqq/PbbjvHc09TJwdv3Tw==";
    name = "oxfmt-0.70.0.tgz";
  };
  "oxlint-tsgolint@7.0.2003" = fetchurl {
    url = "https://npm.flatt.tech/oxlint-tsgolint/-/oxlint-tsgolint-7.0.2003.tgz";
    hash = "sha512-VnK4zlqgmgq/7ZcjzCk/WpN8kKFsYGcB85Io9qT3wL4K8Un3RKmJkp793crNETieMusPMKOA4a+Mw2wbteI6TQ==";
    name = "oxlint-tsgolint-7.0.2003.tgz";
  };
  "oxlint@1.85.0" = fetchurl {
    url = "https://npm.flatt.tech/oxlint/-/oxlint-1.85.0.tgz";
    hash = "sha512-bc26s97nuvPj1ViyPsqmKecVkUWFMEdtayO8MaQ6oiLfs1pj94cQlZZhrh4BPNlr9HQosjhIlwgZKsfcwmcNgg==";
    name = "oxlint-1.85.0.tgz";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://npm.flatt.tech/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
    name = "pathe-2.0.3.tgz";
  };
  "picocolors@1.1.1" = fetchurl {
    url = "https://npm.flatt.tech/picocolors/-/picocolors-1.1.1.tgz";
    hash = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
    name = "picocolors-1.1.1.tgz";
  };
  "picomatch@4.0.7" = fetchurl {
    url = "https://npm.flatt.tech/picomatch/-/picomatch-4.0.7.tgz";
    hash = "sha512-qcJu88Q2IWqJsDD529JKMdwGm/dvInW4HvQnRwiH9JtihJvzGOscDtHE3x1pBKeUOTysQ8kVmLnJ2kJu7yhcGA==";
    name = "picomatch-4.0.7.tgz";
  };
  "pngjs@7.0.0" = fetchurl {
    url = "https://npm.flatt.tech/pngjs/-/pngjs-7.0.0.tgz";
    hash = "sha512-LKWqWJRhstyYo9pGvgor/ivk2w94eSjE3RGVuzLGlr3NmD8bf7RcYGze1mNdEHRP6TRP6rMuDHk5t44hnTRyow==";
    name = "pngjs-7.0.0.tgz";
  };
  "postcss@8.5.28" = fetchurl {
    url = "https://npm.flatt.tech/postcss/-/postcss-8.5.28.tgz";
    hash = "sha512-RRuzqDtt5Y9h3quz5hWhK+TPnsmVs6WwSU6LkJMeY4HstUEDuYTG8UJSdawMRzmzAtV+KEoG8N3Qg2qLy5vM/A==";
    name = "postcss-8.5.28.tgz";
  };
  "pretty-format@27.5.1" = fetchurl {
    url = "https://npm.flatt.tech/pretty-format/-/pretty-format-27.5.1.tgz";
    hash = "sha512-Qb1gy5OrP5+zDf2Bvnzdl3jsTf1qXVMazbvCoKhtKqVs4/YK4ozX4gKQJJVyNe+cajNPn0KoC0MC3FUmaHWEmQ==";
    name = "pretty-format-27.5.1.tgz";
  };
  "react-is@17.0.2" = fetchurl {
    url = "https://npm.flatt.tech/react-is/-/react-is-17.0.2.tgz";
    hash = "sha512-w2GsyukL62IJnlaff/nRegPQR94C/XXamvMWmSHRJ4y7Ts/4ocGRmTHvOs8PSE6pB3dWOrD/nueuU5sduBsQ4w==";
    name = "react-is-17.0.2.tgz";
  };
  "rolldown@1.2.8" = fetchurl {
    url = "https://npm.flatt.tech/rolldown/-/rolldown-1.2.8.tgz";
    hash = "sha512-Z67nTmhZe7anqnM/EjI392w5i/ANUinjip7QYsOyN37oayduxt3ksdX0hf5OOamkAd53BiIHfbfSzfUmzKFQqQ==";
    name = "rolldown-1.2.8.tgz";
  };
  "siginfo@2.0.0" = fetchurl {
    url = "https://npm.flatt.tech/siginfo/-/siginfo-2.0.0.tgz";
    hash = "sha512-ybx0WO1/8bSBLEWXZvEd7gMW3Sn3JFlW3TvX1nREbDLRNQNaeNN8WK0meBwPdAaOI7TtRRRJn/Es1zhrrCHu7g==";
    name = "siginfo-2.0.0.tgz";
  };
  "sirv@3.0.2" = fetchurl {
    url = "https://npm.flatt.tech/sirv/-/sirv-3.0.2.tgz";
    hash = "sha512-2wcC/oGxHis/BoHkkPwldgiPSYcpZK3JU28WoMVv55yHJgcZ8rlXvuG9iZggz+sU1d4bRgIGASwyWqjxu3FM0g==";
    name = "sirv-3.0.2.tgz";
  };
  "source-map-js@1.2.1" = fetchurl {
    url = "https://npm.flatt.tech/source-map-js/-/source-map-js-1.2.1.tgz";
    hash = "sha512-UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
    name = "source-map-js-1.2.1.tgz";
  };
  "stackback@0.0.2" = fetchurl {
    url = "https://registry.npmjs.org/stackback/-/stackback-0.0.2.tgz";
    hash = "sha512-1XMJE5fQo1jGH6Y/7ebnwPOBEkIEnT4QF32d5R1+VXdXveM0IBMJt8zfaxX1P3QhVwrYe+576+jkANtSS2mBbw==";
  };
  "std-env@4.2.0" = fetchurl {
    url = "https://npm.flatt.tech/std-env/-/std-env-4.2.0.tgz";
    hash = "sha512-oCUKSupKTHX53EyjDtuZQ64pjLJ6yYCtpmEw0goYxtjG9KpbRe8KAsl2tBUGU9DyMcJ0RwJ8GqJAFzMXcXW1Rw==";
    name = "std-env-4.2.0.tgz";
  };
  "tinybench@6.1.4" = fetchurl {
    url = "https://npm.flatt.tech/tinybench/-/tinybench-6.1.4.tgz";
    hash = "sha512-9APumHG7r4yOk4X4WlkmE71aZcv1gvin1czO3OQ1U9iJcFA5Ja/ygyb0vPOVHTthFozUYs8CLoLUlM8grb2lTQ==";
    name = "tinybench-6.1.4.tgz";
  };
  "tinyexec@1.3.0" = fetchurl {
    url = "https://npm.flatt.tech/tinyexec/-/tinyexec-1.3.0.tgz";
    hash = "sha512-QKAl9m8gWWGHV8jZcPeym6j+XULi6tOf1mT83WYJ4Lk2ytW/uwAWkrP0uFsdoYMdueVJ0qs26wZ+23xeB4ibNQ==";
    name = "tinyexec-1.3.0.tgz";
  };
  "tinyglobby@0.2.17" = fetchurl {
    url = "https://npm.flatt.tech/tinyglobby/-/tinyglobby-0.2.17.tgz";
    hash = "sha512-wXR/dYpcqKmfWpEdZjiKJOwCNFndD0DMnrW/cYjVGttEkBfVgcLFHoNrlj47mjOVic9yyNu65alsgF4NQyTa2g==";
    name = "tinyglobby-0.2.17.tgz";
  };
  "tinypool@2.1.2" = fetchurl {
    url = "https://npm.flatt.tech/tinypool/-/tinypool-2.1.2.tgz";
    hash = "sha512-9YodfrxS9g9IbFr/KOjE5bAeJ0p61n3bW6mqvy0jtoeKd1kTW1Cxm0oulm6KX2lyM9Gl6WIe8nEbY7LWv5ZJww==";
    name = "tinypool-2.1.2.tgz";
  };
  "tinyrainbow@3.1.1" = fetchurl {
    url = "https://npm.flatt.tech/tinyrainbow/-/tinyrainbow-3.1.1.tgz";
    hash = "sha512-yau8yJdTt989Mm0Bd/236QnzEiPf2xLLTqUZRUJOo/3CB078LSwzei343DgtJVmfJKJE3TMINY1u42SQsP6mXw==";
    name = "tinyrainbow-3.1.1.tgz";
  };
  "totalist@3.0.1" = fetchurl {
    url = "https://npm.flatt.tech/totalist/-/totalist-3.0.1.tgz";
    hash = "sha512-sf4i37nQ2LBx4m3wB74y+ubopq6W/dIzXg0FDGjsYnZHVa1Da8FH853wlL2gtUhg+xJXjfk3kUZS3BRoQeoQBQ==";
    name = "totalist-3.0.1.tgz";
  };
  "typescript@7.0.2" = fetchurl {
    url = "https://npm.flatt.tech/typescript/-/typescript-7.0.2.tgz";
    hash = "sha512-8FYau96o3NKOhbjKi/qNvG/W5jhzxkbdm5sj9AbZ/5T5sWqn3hJgLfGx27sRKZWTvyzCP8dLRBTf5tBTSRVUNA==";
    name = "typescript-7.0.2.tgz";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://npm.flatt.tech/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
    name = "undici-types-7.18.2.tgz";
  };
  "vite-plus@1.0.0" = fetchurl {
    url = "https://npm.flatt.tech/vite-plus/-/vite-plus-1.0.0.tgz";
    hash = "sha512-2ezzBWt+AVO+I2F9Cpb2Of0J12Lat35kWZ/FRL2monMnKZuACKfkYAA/nMqdDo1KwB8sWjTKzmD9mRCh1Q1n+g==";
    name = "vite-plus-1.0.0.tgz";
  };
  "vite@8.3.0" = fetchurl {
    url = "https://npm.flatt.tech/vite/-/vite-8.3.0.tgz";
    hash = "sha512-lhZBVvEHefgE+HQZC9O7EBJgCU/nVzFNl7vkS4RE0APtWLP02/8QVIkQtzBxPquh7lq5/78NHipTj7ODQ6XuyQ==";
    name = "vite-8.3.0.tgz";
  };
  "vitest@5.0.1" = fetchurl {
    url = "https://npm.flatt.tech/vitest/-/vitest-5.0.1.tgz";
    hash = "sha512-iA95lQbKEkvrtTkdAgnWbXfbipWiiWe/hDl2P5tMi6WFwD76G0NxXAGp/M9EOcYupeGJRr6wppMc7CoA41TQjg==";
    name = "vitest-5.0.1.tgz";
  };
  "why-is-node-running@2.3.0" = fetchurl {
    url = "https://npm.flatt.tech/why-is-node-running/-/why-is-node-running-2.3.0.tgz";
    hash = "sha512-hUrmaWBdVDcxvYqnyh09zunKzROWjbZTiNy8dBEjkS7ehEDQibXJ7XvlmtbwuTclUiIyN+CyXQD4Vmko8fNm8w==";
    name = "why-is-node-running-2.3.0.tgz";
  };
  "ws@8.21.3" = fetchurl {
    url = "https://npm.flatt.tech/ws/-/ws-8.21.3.tgz";
    hash = "sha512-201TZ/kPWxoPr/OKWjquZR1SWKXcvxdH+e1xrx89b3YbmzLMFCLfnaG1HFIgWzJOEWZ7MvpK++odZufgYR50Rw==";
    name = "ws-8.21.3.tgz";
  };
  "yuku-ast@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/yuku-ast/-/yuku-ast-0.9.5.tgz";
    hash = "sha512-Q8qW8WwQnN5Cm0ZZivdRIfv0sRLTjUq0YumXJkw8CYN1aCdICH9rk4C47/4n6kA5EqDtlj+F608twoTSV2MwdQ==";
    name = "yuku-ast-0.9.5.tgz";
  };
  "yuku-codegen@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/yuku-codegen/-/yuku-codegen-0.9.5.tgz";
    hash = "sha512-zGUVyDpSK4b6c9B0yyxi2P0wujn1XZTbG9dCb7d6gyAoP63EMgyLzUwPUvwxPG5jgYqhlI7w+S3oCyapqGr4PA==";
    name = "yuku-codegen-0.9.5.tgz";
  };
  "yuku-parser@0.9.5" = fetchurl {
    url = "https://npm.flatt.tech/yuku-parser/-/yuku-parser-0.9.5.tgz";
    hash = "sha512-IBnAdNVMswWbJcM7woPluOudectJzFjJ1N8jVRxP9Uq4CIv5hZdBIcdmtRbFDYF/Ph2j2gVup4YJ4N9mh0jYFA==";
    name = "yuku-parser-0.9.5.tgz";
  };
}